"""Center a PCB on its engineering drawing sheet (``kct pcb center-on-sheet``).

Boards generated by kicad-tools historically placed the outline origin at a
fixed ``(100, 100)`` on an A4 sheet (large boards then overlap the title
block), or shrank the sheet to a tight ``(paper "User" W H)`` page (the board
hugs the top-left frame corner and the default title block overlaps copper).
On kicad-tools.org's interactive viewer (KiCanvas renders the worksheet frame
and title block) both look wrong.

This module rigidly translates **all** board geometry by a single ``(dx, dy)``
so the Edge.Cuts bounding box sits centered in the sheet's *usable drawing
area* -- inside the frame border and above the title-block band -- like a
proper engineering drawing.

Sheet geometry model (KiCad default worksheet, which KiCanvas also renders):

* Frame margin: 10 mm on every side (``left/right/top/bottom_margin`` in
  KiCad's default drawing sheet).
* Title block: the default worksheet's title-block outline rect spans 34 mm
  above the bottom frame line (its ``(rect (start 110 34) ...)`` node is
  anchored to the bottom-right frame corner).  We reserve a 35 mm band --
  the 34 mm outline plus 1 mm breathing room -- across the **full** sheet
  width.  Reserving the full width (not just the 110 mm-wide block) keeps
  centering symmetric and boards visually clear of the block.

``(paper "User" W H)`` sheets have no meaningful frame to center in (they
were sized to the board, which is exactly why those boards hug the corner),
so by default they are switched to the smallest standard landscape size
whose usable area fits the board with at least 15 mm of slack per side.

The transform is **pure text editing** with decimal-string arithmetic: the
only bytes that change are the X/Y atoms of coordinate nodes (and the
``(paper ...)`` node when the sheet size changes).  ``dx``/``dy`` are snapped
to a 0.05 mm grid and added to each coordinate exactly (via ``Decimal``), so
45-degree geometry stays exactly 45 degrees, via grids stay on-grid, and no
float noise is introduced.  Footprints are moved by their top-level
``(at ...)`` only -- pad/text nodes inside are footprint-relative and are
left untouched.

Used by ``kct pcb center-on-sheet``.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path

from kicad_tools.pcb.models3d import _find_matching_paren, _skip_string

__all__ = [
    "DEFAULT_FRAME_MARGIN_MM",
    "DEFAULT_GRID_MM",
    "DEFAULT_PAPER_SLACK_MM",
    "DEFAULT_TITLE_BLOCK_MM",
    "STANDARD_LANDSCAPE_PAPERS",
    "CenterReport",
    "center_on_sheet",
    "center_pcb_text",
    "centered_origin",
    "edge_cuts_bbox",
    "select_paper",
    "translate_pcb_text",
    "usable_area",
]


DEFAULT_FRAME_MARGIN_MM = 10.0
"""Frame border inset of the KiCad default worksheet (10 mm per side)."""

DEFAULT_TITLE_BLOCK_MM = 35.0
"""Reserved title-block band above the bottom frame line.

The KiCad default worksheet's title-block outline extends 34 mm above the
bottom frame line; 35 mm covers it with 1 mm of clearance.
"""

DEFAULT_PAPER_SLACK_MM = 15.0
"""Minimum per-side slack required when auto-selecting a standard paper."""

DEFAULT_GRID_MM = 0.05
"""Grid the translation delta is snapped to (keeps via grids / 45s exact)."""

STANDARD_LANDSCAPE_PAPERS: tuple[tuple[str, float, float], ...] = (
    ("A4", 297.0, 210.0),
    ("A3", 420.0, 297.0),
    ("A2", 594.0, 420.0),
    ("A1", 841.0, 594.0),
    ("A0", 1189.0, 841.0),
)
"""Standard landscape sheet sizes, smallest first (name, width, height)."""

_PAPER_SIZES = {name: (w, h) for name, w, h in STANDARD_LANDSCAPE_PAPERS}

# Top-level items whose coordinates are sheet-absolute and must all shift.
# (Footprints are handled separately: only their top-level ``(at ...)``
# moves; nested pad/text coordinates are footprint-relative.)
_ITEM_TAGS = frozenset(
    {
        "segment",
        "via",
        "arc",
        "zone",
        "gr_line",
        "gr_arc",
        "gr_rect",
        "gr_circle",
        "gr_poly",
        "gr_curve",
        "gr_text",
        "gr_text_box",
        "gr_bbox",
        "text",
        "textbox",
        "dimension",
        "target",
        "image",
        "table",
    }
)

# Coordinate node tags: the first two atoms are an absolute X, Y pair.
# Trailing atoms (e.g. the rotation angle of ``(at X Y ANGLE)``) never move.
_COORD_TAGS = frozenset({"at", "start", "end", "mid", "center", "xy"})

_NM_PER_MM = 1_000_000


# --------------------------------------------------------------------------
# Sheet geometry
# --------------------------------------------------------------------------


def usable_area(
    paper_w: float,
    paper_h: float,
    *,
    margin: float = DEFAULT_FRAME_MARGIN_MM,
    title_block: float = DEFAULT_TITLE_BLOCK_MM,
) -> tuple[float, float, float, float]:
    """Usable drawing area ``(x0, y0, x1, y1)`` of a sheet.

    Inside the frame border on all sides and above the title-block band at
    the bottom.
    """
    return (margin, margin, paper_w - margin, paper_h - margin - title_block)


def select_paper(
    board_w: float,
    board_h: float,
    *,
    slack: float = DEFAULT_PAPER_SLACK_MM,
    margin: float = DEFAULT_FRAME_MARGIN_MM,
    title_block: float = DEFAULT_TITLE_BLOCK_MM,
) -> str | None:
    """Smallest standard landscape paper fitting the board with per-side slack.

    Returns ``None`` if the board does not fit even A0.
    """
    for name, w, h in STANDARD_LANDSCAPE_PAPERS:
        x0, y0, x1, y1 = usable_area(w, h, margin=margin, title_block=title_block)
        if (x1 - x0) - board_w >= 2 * slack and (y1 - y0) - board_h >= 2 * slack:
            return name
    return None


def centered_origin(
    board_w: float,
    board_h: float,
    paper: str = "A4",
    *,
    margin: float = DEFAULT_FRAME_MARGIN_MM,
    title_block: float = DEFAULT_TITLE_BLOCK_MM,
    grid: float = DEFAULT_GRID_MM,
) -> tuple[float, float]:
    """Top-left board-outline origin that centers the board on *paper*.

    For board generators: place the outline at this origin (and everything
    else relative to it) so a fresh build is already centered in the sheet's
    usable drawing area -- no post-hoc translation needed.

    The origin is snapped to *grid* so all derived coordinates stay exact.
    """
    if paper not in _PAPER_SIZES:
        raise ValueError(f"Unknown paper size {paper!r}. Supported: {', '.join(_PAPER_SIZES)}")
    pw, ph = _PAPER_SIZES[paper]
    x0, y0, x1, y1 = usable_area(pw, ph, margin=margin, title_block=title_block)
    ox = (x0 + x1 - board_w) / 2
    oy = (y0 + y1 - board_h) / 2
    return (round(round(ox / grid) * grid, 6), round(round(oy / grid) * grid, 6))


# --------------------------------------------------------------------------
# S-expression text scanning
# --------------------------------------------------------------------------


def _read_tag(text: str, open_idx: int) -> str:
    """Tag of the node whose ``(`` is at *open_idx*."""
    i = open_idx + 1
    n = len(text)
    start = i
    while i < n and text[i] not in ' \t\r\n()"':
        i += 1
    return text[start:i]


def _iter_child_blocks(text: str, open_idx: int, close_idx: int):
    """Yield ``(tag, start, end)`` for each direct child node of a block."""
    i = open_idx + 1
    while i < close_idx:
        c = text[i]
        if c == '"':
            i = _skip_string(text, i)
            continue
        if c == "(":
            end = _find_matching_paren(text, i)
            yield (_read_tag(text, i), i, end)
            i = end + 1
            continue
        i += 1


def _find_root(text: str) -> tuple[int, int]:
    """Locate the ``(kicad_pcb ...)`` root node. Returns (open, close)."""
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i = _skip_string(text, i)
            continue
        if c == "(":
            if _read_tag(text, i) == "kicad_pcb":
                return (i, _find_matching_paren(text, i))
            i = _find_matching_paren(text, i) + 1
            continue
        i += 1
    raise ValueError("No (kicad_pcb ...) root node found")


def _iter_atoms(text: str, open_idx: int, close_idx: int):
    """Yield ``(start, end)`` spans of the bare atoms of a leaf node.

    Stops at the first nested ``(`` (coordinate nodes are leaves; anything
    nested is not part of the X/Y atoms).  Quoted strings are yielded with
    their quotes included.
    """
    tag = _read_tag(text, open_idx)
    i = open_idx + 1 + len(tag)
    while i < close_idx:
        c = text[i]
        if c in " \t\r\n":
            i += 1
            continue
        if c == "(":
            return
        if c == '"':
            end = _skip_string(text, i)
            yield (i, end)
            i = end
            continue
        start = i
        while i < close_idx and text[i] not in ' \t\r\n()"':
            i += 1
        yield (start, i)


# --------------------------------------------------------------------------
# Rigid translation (pure text, exact decimal arithmetic)
# --------------------------------------------------------------------------


def _shift_mm(token: str, delta_nm: int) -> str:
    """Add an exact nm-grid delta to an mm coordinate string.

    Decimal-string arithmetic: no float round-trip, so the result is exact.
    The value is quantized to 6 decimals (KiCad's nm grid) and trailing
    zeros are stripped to match KiCad's own formatting.
    """
    value = Decimal(token) + Decimal(delta_nm) / _NM_PER_MM
    out = format(value.quantize(Decimal("0.000001")), "f")
    if "." in out:
        out = out.rstrip("0").rstrip(".")
    return "0" if out in ("", "-0") else out


def _is_number(token: str) -> bool:
    try:
        Decimal(token)
    except Exception:
        return False
    return True


def _coord_edits(
    text: str, open_idx: int, close_idx: int, dx_nm: int, dy_nm: int
) -> list[tuple[int, int, str]]:
    """Edits shifting the X/Y atoms of the coordinate node at *open_idx*."""
    atoms = list(_iter_atoms(text, open_idx, close_idx))
    if len(atoms) < 2:
        return []
    (xs, xe), (ys, ye) = atoms[0], atoms[1]
    x_tok, y_tok = text[xs:xe], text[ys:ye]
    if not (_is_number(x_tok) and _is_number(y_tok)):
        return []
    return [(xs, xe, _shift_mm(x_tok, dx_nm)), (ys, ye, _shift_mm(y_tok, dy_nm))]


def _collect_item_edits(
    text: str,
    open_idx: int,
    close_idx: int,
    dx_nm: int,
    dy_nm: int,
    edits: list[tuple[int, int, str]],
) -> None:
    """Recursively collect coordinate edits within a sheet-absolute item."""
    tag = _read_tag(text, open_idx)
    if tag in _COORD_TAGS:
        edits.extend(_coord_edits(text, open_idx, close_idx, dx_nm, dy_nm))
        return
    for _, s, e in _iter_child_blocks(text, open_idx, close_idx):
        _collect_item_edits(text, s, e, dx_nm, dy_nm, edits)


def _translate_pcb_text(text: str, dx_nm: int, dy_nm: int) -> tuple[str, int]:
    """Rigidly translate all board geometry in raw ``.kicad_pcb`` text.

    Returns ``(new_text, translated_item_count)``.  Only the X/Y atoms of
    coordinate nodes change; every other byte is preserved.
    """
    root_open, root_close = _find_root(text)
    edits: list[tuple[int, int, str]] = []
    items = 0
    for tag, s, e in _iter_child_blocks(text, root_open, root_close):
        if tag == "footprint":
            # Move only the footprint's own (at ...); children are relative.
            for ctag, cs, ce in _iter_child_blocks(text, s, e):
                if ctag == "at":
                    edits.extend(_coord_edits(text, cs, ce, dx_nm, dy_nm))
                    break
            items += 1
        elif tag in _ITEM_TAGS:
            _collect_item_edits(text, s, e, dx_nm, dy_nm, edits)
            items += 1
    return _apply_edits(text, edits), items


def _apply_edits(text: str, edits: list[tuple[int, int, str]]) -> str:
    if not edits:
        return text
    edits.sort(key=lambda t: t[0])
    out: list[str] = []
    prev = 0
    for s, e, repl in edits:
        out.append(text[prev:s])
        out.append(repl)
        prev = e
    out.append(text[prev:])
    return "".join(out)


def translate_pcb_text(
    text: str,
    dx_mm: float,
    dy_mm: float,
    *,
    grid: float = DEFAULT_GRID_MM,
) -> str:
    """Rigidly translate all board geometry by ``(dx_mm, dy_mm)``.

    The same exact decimal-string transform ``center_pcb_text`` applies, but
    with an explicit caller-chosen delta instead of a computed centering
    delta.  ``(dx_mm, dy_mm)`` is snapped once to *grid* in integer
    nanometres and added identically to every sheet-absolute coordinate, so
    45-degree copper stays exactly 45 degrees and the transform is exactly
    invertible (translating by the negated delta restores every coordinate).

    Used by board recipes that route in a fixed historical frame and place
    the artifact on the sheet as a final step (see board 07's
    ``generate_design.py``: the negotiated router's escape/rip-up dynamics
    are empirically sensitive to the board's absolute position, so the
    recipe keeps the routing frame invariant and translates artifacts).
    """
    grid_nm = round(grid * _NM_PER_MM)
    dx_nm = round(round(dx_mm * _NM_PER_MM / grid_nm) * grid_nm)
    dy_nm = round(round(dy_mm * _NM_PER_MM / grid_nm) * grid_nm)
    new_text, _items = _translate_pcb_text(text, dx_nm, dy_nm)
    return new_text


# --------------------------------------------------------------------------
# Paper node parsing / rewriting
# --------------------------------------------------------------------------


def _find_paper_node(text: str) -> tuple[int, int, str, float, float] | None:
    """Locate the top-level ``(paper ...)`` node.

    Returns ``(start, end, name, width_mm, height_mm)`` or ``None``.
    Width/height reflect landscape defaults for standard sizes, the explicit
    W/H atoms for ``User`` paper, and honor a trailing ``portrait`` token.
    """
    root_open, root_close = _find_root(text)
    for tag, s, e in _iter_child_blocks(text, root_open, root_close):
        if tag != "paper":
            continue
        atoms = [text[a:b] for a, b in _iter_atoms(text, s, e)]
        if not atoms:
            return None
        name = atoms[0].strip('"')
        if name == "User":
            if len(atoms) >= 3 and _is_number(atoms[1]) and _is_number(atoms[2]):
                return (s, e, name, float(atoms[1]), float(atoms[2]))
            return (s, e, name, 0.0, 0.0)
        size = _PAPER_SIZES.get(name)
        if size is None:
            return (s, e, name, 0.0, 0.0)
        w, h = size
        if "portrait" in atoms[1:]:
            w, h = h, w
        return (s, e, name, w, h)
    return None


# --------------------------------------------------------------------------
# Public entry points
# --------------------------------------------------------------------------


@dataclass
class CenterReport:
    """Summary of a ``center_pcb_text`` / ``center_on_sheet`` run."""

    paper_before: str
    paper_after: str
    bbox_before: tuple[float, float, float, float]
    bbox_after: tuple[float, float, float, float]
    dx_mm: float
    dy_mm: float
    translated_items: int
    usable_area: tuple[float, float, float, float]

    @property
    def paper_changed(self) -> bool:
        return self.paper_before != self.paper_after

    @property
    def changed(self) -> bool:
        return self.paper_changed or self.dx_mm != 0.0 or self.dy_mm != 0.0


def edge_cuts_bbox(text: str) -> tuple[float, float, float, float] | None:
    """Bounding box of all top-level Edge.Cuts graphics in raw PCB text.

    Arc extents are approximated by their start/mid/end points (same
    approximation as ``PCB._edge_cuts_bbox_sexp``).
    """
    xs: list[float] = []
    ys: list[float] = []
    root_open, root_close = _find_root(text)
    for tag, s, e in _iter_child_blocks(text, root_open, root_close):
        if tag not in ("gr_rect", "gr_line", "gr_arc", "gr_circle", "gr_poly", "gr_curve"):
            continue
        on_edge = False
        for ctag, cs, ce in _iter_child_blocks(text, s, e):
            if ctag == "layer":
                atoms = [text[a:b] for a, b in _iter_atoms(text, cs, ce)]
                on_edge = bool(atoms) and atoms[0].strip('"') == "Edge.Cuts"
                break
        if not on_edge:
            continue
        edits: list[tuple[int, int, str]] = []
        _collect_item_edits(text, s, e, 0, 0, edits)
        # Reuse the coordinate discovery: each coord node contributed an
        # (unchanged) X edit then Y edit, in atom order.
        for i in range(0, len(edits) - 1, 2):
            xs.append(float(edits[i][2]))
            ys.append(float(edits[i + 1][2]))
    if not xs:
        return None
    return (min(xs), min(ys), max(xs), max(ys))


def center_pcb_text(
    text: str,
    *,
    paper: str = "auto",
    margin: float = DEFAULT_FRAME_MARGIN_MM,
    title_block: float = DEFAULT_TITLE_BLOCK_MM,
    slack: float = DEFAULT_PAPER_SLACK_MM,
    grid: float = DEFAULT_GRID_MM,
) -> tuple[str, CenterReport]:
    """Center the board in its sheet's usable drawing area (pure text).

    Args:
        text: Raw ``.kicad_pcb`` file text.
        paper: ``"auto"`` (default) keeps a standard sheet when the board
            fits its usable area, escalates to the smallest standard
            landscape size otherwise, and always upgrades ``User`` sheets to
            a standard size.  ``"keep"`` never changes the sheet (errors if
            the board cannot fit a ``User`` sheet's usable area).  A specific
            size name (``"A4"``...``"A0"``) forces that sheet.
        margin: Frame border inset per side in mm.
        title_block: Reserved title-block band height in mm.
        slack: Required per-side slack for auto paper selection.
        grid: Grid to snap the translation delta to (mm).

    Returns:
        ``(new_text, CenterReport)``.  When nothing needs to change the
        original text object is returned unchanged (idempotent).
    """
    bbox = edge_cuts_bbox(text)
    if bbox is None:
        raise ValueError("center-on-sheet requires an Edge.Cuts board outline; none found.")
    min_x, min_y, max_x, max_y = bbox
    board_w = max_x - min_x
    board_h = max_y - min_y

    paper_node = _find_paper_node(text)
    if paper_node is None:
        raise ValueError("No (paper ...) node found in PCB.")
    p_start, p_end, cur_name, cur_w, cur_h = paper_node

    def fits(pw: float, ph: float) -> bool:
        x0, y0, x1, y1 = usable_area(pw, ph, margin=margin, title_block=title_block)
        return board_w <= (x1 - x0) and board_h <= (y1 - y0)

    new_name = cur_name
    if paper == "keep":
        if not fits(cur_w, cur_h):
            raise ValueError(
                f"Board ({board_w:g} x {board_h:g} mm) does not fit the usable "
                f"area of the current {cur_name} sheet ({cur_w:g} x {cur_h:g} mm) "
                f"with margin={margin:g} and title_block={title_block:g}."
            )
    elif paper == "auto":
        if cur_name == "User" or cur_name not in _PAPER_SIZES or not fits(cur_w, cur_h):
            selected = select_paper(
                board_w, board_h, slack=slack, margin=margin, title_block=title_block
            )
            if selected is None:
                raise ValueError(
                    f"Board ({board_w:g} x {board_h:g} mm) does not fit any "
                    f"standard sheet up to A0 with {slack:g} mm slack per side."
                )
            new_name = selected
    else:
        if paper not in _PAPER_SIZES:
            raise ValueError(
                f"Unknown paper {paper!r}. Use 'auto', 'keep' or one of: {', '.join(_PAPER_SIZES)}"
            )
        if not fits(*_PAPER_SIZES[paper]):
            raise ValueError(
                f"Board ({board_w:g} x {board_h:g} mm) does not fit the usable area of {paper}."
            )
        new_name = paper

    if new_name == cur_name:
        new_w, new_h = cur_w, cur_h
    else:
        new_w, new_h = _PAPER_SIZES[new_name]

    x0, y0, x1, y1 = usable_area(new_w, new_h, margin=margin, title_block=title_block)
    target_cx = (x0 + x1) / 2
    target_cy = (y0 + y1) / 2
    cur_cx = (min_x + max_x) / 2
    cur_cy = (min_y + max_y) / 2

    # Snap the delta ONCE to the grid, in exact integer nanometres; every
    # coordinate then shifts by this identical delta (true rigid translation).
    grid_nm = round(grid * _NM_PER_MM)
    dx_nm = round(round((target_cx - cur_cx) * _NM_PER_MM / grid_nm)) * grid_nm
    dy_nm = round(round((target_cy - cur_cy) * _NM_PER_MM / grid_nm)) * grid_nm

    report = CenterReport(
        paper_before=cur_name,
        paper_after=new_name,
        bbox_before=bbox,
        bbox_after=(
            min_x + dx_nm / _NM_PER_MM,
            min_y + dy_nm / _NM_PER_MM,
            max_x + dx_nm / _NM_PER_MM,
            max_y + dy_nm / _NM_PER_MM,
        ),
        dx_mm=dx_nm / _NM_PER_MM,
        dy_mm=dy_nm / _NM_PER_MM,
        translated_items=0,
        usable_area=(x0, y0, x1, y1),
    )

    if dx_nm == 0 and dy_nm == 0 and new_name == cur_name:
        return text, report  # already centered: no-op

    new_text = text
    if new_name != cur_name:
        new_text = new_text[:p_start] + f'(paper "{new_name}")' + new_text[p_end + 1 :]

    if dx_nm != 0 or dy_nm != 0:
        new_text, items = _translate_pcb_text(new_text, dx_nm, dy_nm)
        report.translated_items = items

    return new_text, report


def center_on_sheet(
    pcb_path: Path | str,
    *,
    output_path: Path | str | None = None,
    paper: str = "auto",
    margin: float = DEFAULT_FRAME_MARGIN_MM,
    title_block: float = DEFAULT_TITLE_BLOCK_MM,
    slack: float = DEFAULT_PAPER_SLACK_MM,
    grid: float = DEFAULT_GRID_MM,
    dry_run: bool = False,
) -> CenterReport:
    """Center a ``.kicad_pcb`` file on its drawing sheet.

    See :func:`center_pcb_text` for parameter semantics.  When *dry_run* is
    True nothing is written; otherwise the result is written to
    *output_path* (default: in place) only if something changed.
    """
    pcb_path = Path(pcb_path)
    text = pcb_path.read_text()
    new_text, report = center_pcb_text(
        text, paper=paper, margin=margin, title_block=title_block, slack=slack, grid=grid
    )
    if report.changed and not dry_run:
        dest = Path(output_path) if output_path is not None else pcb_path
        dest.write_text(new_text)
    return report
