"""Patch ``(model ...)`` 3D model references into PCB footprints.

Boards generated by kicad-tools embed footprint s-expressions that carry
copper/silkscreen geometry but **no** ``(model ...)`` 3D model references,
so ``kicad-cli pcb render`` draws a bare board (pads only, no component
bodies).  Footprints sourced from the standard KiCad libraries have a
canonical model reference in their ``.kicad_mod`` source (e.g.
``${KICAD10_3DMODEL_DIR}/LED_THT.3dshapes/LED_D5.0mm.step``); this module
copies those references into an existing ``.kicad_pcb`` after the fact.

The patch is **pure text insertion**: for each footprint block whose lib id
resolves to an installed KiCad library footprint that has one or more
``(model ...)`` nodes, the nodes are inserted verbatim (re-indented) just
before the footprint's closing paren.  No other bytes of the file change --
copper, placement, zones and nets are untouched, so DRC results are
guaranteed identical.

Used by ``kct pcb add-3d-models``.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from kicad_tools.footprints.library_path import (
    LibraryPaths,
    detect_kicad_library_path,
    parse_library_id,
)

__all__ = [
    "FootprintBlock",
    "ModelPatchReport",
    "add_model_refs",
    "add_model_refs_to_text",
    "extract_model_blocks",
    "iter_footprint_blocks",
    "make_library_resolver",
]


# --------------------------------------------------------------------------
# Low-level s-expression text scanning (string-aware paren matching)
# --------------------------------------------------------------------------


def _skip_string(text: str, i: int) -> int:
    """Return the index just past a double-quoted string starting at *i*.

    Handles backslash escapes (KiCad escapes embedded quotes as ``\\"``).
    """
    assert text[i] == '"'
    i += 1
    n = len(text)
    while i < n:
        c = text[i]
        if c == "\\":
            i += 2
            continue
        if c == '"':
            return i + 1
        i += 1
    return n  # unterminated string: treat rest of text as the string


def _find_matching_paren(text: str, open_idx: int) -> int:
    """Index of the ``)`` closing the ``(`` at *open_idx* (string-aware)."""
    assert text[open_idx] == "("
    depth = 0
    i = open_idx
    n = len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i = _skip_string(text, i)
            continue
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    raise ValueError("Unbalanced parentheses in s-expression text")


def _contains_token(text: str, token: str) -> bool:
    """True if ``(<token>`` appears outside of quoted strings in *text*."""
    needle = "(" + token
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i = _skip_string(text, i)
            continue
        if c == "(" and text.startswith(needle, i):
            after = i + len(needle)
            if after >= n or text[after] in ' \t\n"()':
                return True
        i += 1
    return False


# --------------------------------------------------------------------------
# Footprint block discovery
# --------------------------------------------------------------------------


@dataclass
class FootprintBlock:
    """A ``(footprint "Lib:Name" ...)`` block located in raw PCB text."""

    lib_id: str
    start: int
    """Index of the opening ``(``."""
    end: int
    """Index of the closing ``)`` (inclusive)."""
    indent: str
    """Leading whitespace of the line containing the opening paren."""


def iter_footprint_blocks(pcb_text: str) -> list[FootprintBlock]:
    """Locate every top-level footprint block in *pcb_text*.

    Blocks are found with a string-aware scanner, so ``(footprint`` inside a
    quoted string is never mis-detected.
    """
    blocks: list[FootprintBlock] = []
    i = 0
    n = len(pcb_text)
    while i < n:
        c = pcb_text[i]
        if c == '"':
            i = _skip_string(pcb_text, i)
            continue
        if c == "(" and pcb_text.startswith("(footprint", i):
            after = i + len("(footprint")
            if after < n and pcb_text[after] in ' \t\n"':
                end = _find_matching_paren(pcb_text, i)
                # lib id is the first quoted string after the token
                q = pcb_text.find('"', after, end)
                lib_id = ""
                if q != -1:
                    q_end = _skip_string(pcb_text, q)
                    lib_id = pcb_text[q + 1 : q_end - 1]
                line_start = pcb_text.rfind("\n", 0, i) + 1
                indent = pcb_text[line_start:i]
                if indent.strip() == "":
                    blocks.append(FootprintBlock(lib_id=lib_id, start=i, end=end, indent=indent))
                i = end + 1
                continue
        i += 1
    return blocks


# --------------------------------------------------------------------------
# Model block extraction from .kicad_mod sources
# --------------------------------------------------------------------------


def extract_model_blocks(mod_text: str) -> list[str]:
    """Extract every ``(model ...)`` node from ``.kicad_mod`` text.

    Returns the raw node texts *dedented* so the first line starts with
    ``(model`` and continuation lines keep only their indentation relative
    to the node (tabs).
    """
    blocks: list[str] = []
    i = 0
    n = len(mod_text)
    while i < n:
        c = mod_text[i]
        if c == '"':
            i = _skip_string(mod_text, i)
            continue
        if c == "(" and mod_text.startswith("(model", i):
            after = i + len("(model")
            if after < n and mod_text[after] in ' \t\n"':
                end = _find_matching_paren(mod_text, i)
                raw = mod_text[i : end + 1]
                line_start = mod_text.rfind("\n", 0, i) + 1
                base_indent = mod_text[line_start:i]
                blocks.append(_dedent_block(raw, base_indent))
                i = end + 1
                continue
        i += 1
    return blocks


def _dedent_block(raw: str, base_indent: str) -> str:
    """Strip *base_indent* from the continuation lines of a raw node text."""
    if not base_indent:
        return raw
    lines = raw.split("\n")
    out = [lines[0]]
    for line in lines[1:]:
        out.append(line.removeprefix(base_indent))
    return "\n".join(out)


def _indent_block(block: str, indent: str) -> str:
    """Prefix every line of a dedented node text with *indent*."""
    return "\n".join(indent + line if line else line for line in block.split("\n"))


# --------------------------------------------------------------------------
# Resolvers: lib id -> dedented (model ...) block texts
# --------------------------------------------------------------------------

Resolver = Callable[[str], list[str] | None]


def _find_variant_mod(paths: LibraryPaths, library: str, name: str) -> Path | None:
    """Find a same-library name variant of a footprint (visual fallback).

    KiCad library footprints often exist only as suffixed variants of a
    family name (e.g. ``QFN-24-1EP_4x4mm_P0.5mm`` ships as
    ``QFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm``).  For 3D *models* — pure
    visual metadata — the variant's body is the right shape, so when the
    exact name is missing we accept a footprint in the same library whose
    name extends the requested one at a ``_`` or ``-`` boundary.

    Deterministic choice: plain variants beat ``ThermalVias`` specials,
    then shortest name, then lexicographic.
    """
    lib_dir = paths.get_library_path(library)
    if lib_dir is None:
        return None
    prefixes = (name + "_", name + "-")
    candidates = [p for p in lib_dir.glob("*.kicad_mod") if p.stem.startswith(prefixes)]
    if not candidates:
        return None
    candidates.sort(key=lambda p: ("ThermalVias" in p.stem, len(p.stem), p.stem))
    return candidates[0]


def make_library_resolver(
    library_paths: LibraryPaths | None = None,
    *,
    allow_variants: bool = True,
    variant_log: dict[str, str] | None = None,
) -> Resolver:
    """Build a resolver that reads model refs from installed KiCad libraries.

    The resolver maps a footprint lib id (``"LED_THT:LED_D5.0mm"``) to the
    dedented ``(model ...)`` block(s) found in the corresponding installed
    ``.kicad_mod``.  Returns ``None`` when the library footprint can't be
    found and ``[]`` when it exists but carries no model reference.
    Results are cached per lib id.

    Args:
        library_paths: Explicit library location (default: auto-detect).
        allow_variants: When the exact footprint name is missing, fall back
            to a same-library name variant (see ``_find_variant_mod``).
        variant_log: Optional dict populated with ``lib_id -> variant stem``
            for every fallback match, so callers can report them.
    """
    paths = library_paths if library_paths is not None else detect_kicad_library_path()
    cache: dict[str, list[str] | None] = {}

    def resolve(lib_id: str) -> list[str] | None:
        if lib_id in cache:
            return cache[lib_id]
        result: list[str] | None = None
        if paths.found:
            library, name = parse_library_id(lib_id)
            mod_path = None
            if library:
                mod_path = paths.get_footprint_file(library, name, fallback_search=False)
                if mod_path is None and allow_variants:
                    mod_path = _find_variant_mod(paths, library, name)
                    if mod_path is not None and variant_log is not None:
                        variant_log[lib_id] = mod_path.stem
            if mod_path is not None:
                try:
                    result = extract_model_blocks(mod_path.read_text())
                except OSError:
                    result = None
        cache[lib_id] = result
        return result

    return resolve


# --------------------------------------------------------------------------
# Patching
# --------------------------------------------------------------------------


@dataclass
class ModelPatchReport:
    """Summary of an ``add_model_refs`` run."""

    patched: list[str] = field(default_factory=list)
    """Lib ids that had model refs inserted (one entry per footprint)."""
    already_present: list[str] = field(default_factory=list)
    """Lib ids skipped because the footprint already has a model ref."""
    unresolved: list[str] = field(default_factory=list)
    """Lib ids skipped: not found in the installed KiCad libraries."""
    no_model_in_library: list[str] = field(default_factory=list)
    """Lib ids skipped: library footprint exists but has no model ref."""
    variant_matches: dict[str, str] = field(default_factory=dict)
    """Lib ids whose model came from a same-library name variant
    (``lib_id -> matched footprint name``)."""

    @property
    def changed(self) -> bool:
        return bool(self.patched)


def add_model_refs_to_text(pcb_text: str, resolver: Resolver) -> tuple[str, ModelPatchReport]:
    """Insert missing ``(model ...)`` refs into raw ``.kicad_pcb`` text.

    Pure text insertion: the returned text differs from *pcb_text* only by
    inserted model lines (never removed or reordered bytes), keeping the
    change strictly render-metadata-scoped.
    """
    report = ModelPatchReport()
    insertions: list[tuple[int, str]] = []  # (index, text) sorted ascending

    for block in iter_footprint_blocks(pcb_text):
        body = pcb_text[block.start : block.end + 1]
        if _contains_token(body, "model"):
            report.already_present.append(block.lib_id)
            continue
        models = resolver(block.lib_id)
        if models is None:
            report.unresolved.append(block.lib_id)
            continue
        if not models:
            report.no_model_in_library.append(block.lib_id)
            continue
        # Insert before the line that holds the footprint's closing paren.
        close_line_start = pcb_text.rfind("\n", 0, block.end) + 1
        child_indent = block.indent + "\t"
        text = "".join(_indent_block(m, child_indent) + "\n" for m in models)
        insertions.append((close_line_start, text))
        report.patched.append(block.lib_id)

    if not insertions:
        return pcb_text, report

    out: list[str] = []
    prev = 0
    for idx, text in insertions:
        out.append(pcb_text[prev:idx])
        out.append(text)
        prev = idx
    out.append(pcb_text[prev:])
    return "".join(out), report


def add_model_refs(
    pcb_path: Path | str,
    *,
    output_path: Path | str | None = None,
    library_paths: LibraryPaths | None = None,
    resolver: Resolver | None = None,
    allow_variants: bool = True,
    dry_run: bool = False,
) -> ModelPatchReport:
    """Patch missing 3D model refs into a ``.kicad_pcb`` file.

    Args:
        pcb_path: PCB file to patch.
        output_path: Where to write the patched file (default: in place).
        library_paths: Optional explicit KiCad library location (defaults to
            auto-detection of the installed KiCad footprint libraries).
        resolver: Optional custom lib-id resolver (overrides library_paths).
        allow_variants: Accept same-library footprint-name variants when the
            exact name is missing (visual fallback; reported in
            ``variant_matches``). Ignored when *resolver* is supplied.
        dry_run: When True, nothing is written.

    Returns:
        ModelPatchReport describing what was (or would be) inserted.
    """
    pcb_path = Path(pcb_path)
    text = pcb_path.read_text()
    variant_log: dict[str, str] = {}
    if resolver is None:
        resolver = make_library_resolver(
            library_paths, allow_variants=allow_variants, variant_log=variant_log
        )
    new_text, report = add_model_refs_to_text(text, resolver)
    # Only surface variants that actually got patched in.
    report.variant_matches = {
        lib_id: stem for lib_id, stem in variant_log.items() if lib_id in report.patched
    }
    if report.changed and not dry_run:
        dest = Path(output_path) if output_path is not None else pcb_path
        dest.write_text(new_text)
    return report
