"""Patch ``(model ...)`` 3D model references into PCB footprints.

Boards generated by kicad-tools embed footprint s-expressions that carry
copper/silkscreen geometry but **no** ``(model ...)`` 3D model references,
so ``kicad-cli pcb render`` draws a bare board (pads only, no component
bodies).  Footprints sourced from the standard KiCad libraries have a
canonical model reference in their ``.kicad_mod`` source (e.g.
``${KICAD10_3DMODEL_DIR}/LED_THT.3dshapes/LED_D5.0mm.step``); this module
copies those references into an existing ``.kicad_pcb`` after the fact.

The patch is **pure text insertion**: for each footprint block whose lib id
resolves to an installed KiCad library footprint that has one or more
``(model ...)`` nodes, the nodes are inserted (re-indented) just before the
footprint's closing paren.  No other bytes of the file change -- copper,
placement, zones and nets are untouched, so DRC results are guaranteed
identical.

**Origin-convention offset.**  A STEP model is authored in its *library*
footprint's local frame (pad 1 at the library footprint's pad-1 position).
kicad-tools boards often reuse a canonical footprint *name* while placing
pads on a different origin convention -- e.g. a 2-pad 0.1" header whose pads
sit at ``(0, -1.27)`` / ``(0, +1.27)`` (centered on the origin) instead of
KiCad's ``(0, 0)`` / ``(0, 2.54)`` (pad 1 at origin).  Copying the model with
a zero offset then leaves the body shifted by the pad-1 delta (half the pitch
for a 2-pad part).  So before inserting a ``(model ...)`` node we add the
``target_pad1 - source_pad1`` delta into its ``(offset (xyz ...))`` node,
expressed in the KiCad 3D-model frame (X follows the footprint X, **Y is
negated** relative to the footprint 2D frame, Z is unchanged).  This keeps
the change pure render metadata -- only the newly inserted model block's own
offset numbers differ from the library source; no pre-existing byte moves and
no copper/pad/zone/net geometry changes.  Footprints that already share the
library's origin convention (most SMD parts, e.g. ``R_0805_2012Metric``)
compute a zero delta and are inserted verbatim.

**Orientation-convention rotation.**  Some generators bake a footprint's
rotation into the *pad coordinates* rather than expressing it as the
placement angle ``(at x y angle)`` -- e.g. board-07's 0.1" header lays its
pads along X (``(-10.16, 0)`` … ``(10.16, 0)``) while the canonical library
footprint (and its ``.step`` body) lays them along Y.  The placement angle is
``0`` and the copied model rotate is ``0``, so ``kicad-cli pcb render`` draws
the body 90° off from the copper.  This is the rotation analog of the origin
offset above: we derive the pad-field orientation of both the target block
and the source library footprint from two anchor pads (the pad-1→pad-2
vector), and bake ``theta = target - source`` into the inserted model's
``(rotate (xyz 0 0 ...))``.  Because the model frame's Y is negated versus the
footprint 2D frame, a footprint-2D rotation of ``theta`` maps to a model-frame
Z rotation of ``-theta``.  The centroid offset is composed **in the rotated
frame** (``offset_2d = target_centroid - R_theta * source_centroid``) so the
body still lands on the target pads.  Co-oriented footprints (all SMD parts,
headers already authored on the library convention, the origin-offset case
above) compute ``theta ~= 0`` and keep ``(rotate (xyz 0 0 0))`` plus the
existing offset verbatim.

Used by ``kct pcb add-3d-models``.
"""

from __future__ import annotations

import math
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from kicad_tools.footprints.library_path import (
    LibraryPaths,
    detect_kicad_library_path,
    parse_library_id,
)
from kicad_tools.pcb.model_substitutions import substitute_lib_id

__all__ = [
    "FootprintBlock",
    "ModelPatchReport",
    "ResolvedModels",
    "add_model_refs",
    "add_model_refs_to_text",
    "extract_model_blocks",
    "iter_footprint_blocks",
    "make_library_resolver",
]


# --------------------------------------------------------------------------
# Low-level s-expression text scanning (string-aware paren matching)
# --------------------------------------------------------------------------


def _skip_string(text: str, i: int) -> int:
    """Return the index just past a double-quoted string starting at *i*.

    Handles backslash escapes (KiCad escapes embedded quotes as ``\\"``).
    """
    assert text[i] == '"'
    i += 1
    n = len(text)
    while i < n:
        c = text[i]
        if c == "\\":
            i += 2
            continue
        if c == '"':
            return i + 1
        i += 1
    return n  # unterminated string: treat rest of text as the string


def _find_matching_paren(text: str, open_idx: int) -> int:
    """Index of the ``)`` closing the ``(`` at *open_idx* (string-aware)."""
    assert text[open_idx] == "("
    depth = 0
    i = open_idx
    n = len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i = _skip_string(text, i)
            continue
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    raise ValueError("Unbalanced parentheses in s-expression text")


def _contains_token(text: str, token: str) -> bool:
    """True if ``(<token>`` appears outside of quoted strings in *text*."""
    needle = "(" + token
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i = _skip_string(text, i)
            continue
        if c == "(" and text.startswith(needle, i):
            after = i + len(needle)
            if after >= n or text[after] in ' \t\n"()':
                return True
        i += 1
    return False


# --------------------------------------------------------------------------
# Footprint block discovery
# --------------------------------------------------------------------------


@dataclass
class FootprintBlock:
    """A ``(footprint "Lib:Name" ...)`` block located in raw PCB text."""

    lib_id: str
    start: int
    """Index of the opening ``(``."""
    end: int
    """Index of the closing ``)`` (inclusive)."""
    indent: str
    """Leading whitespace of the line containing the opening paren."""


def iter_footprint_blocks(pcb_text: str) -> list[FootprintBlock]:
    """Locate every top-level footprint block in *pcb_text*.

    Blocks are found with a string-aware scanner, so ``(footprint`` inside a
    quoted string is never mis-detected.
    """
    blocks: list[FootprintBlock] = []
    i = 0
    n = len(pcb_text)
    while i < n:
        c = pcb_text[i]
        if c == '"':
            i = _skip_string(pcb_text, i)
            continue
        if c == "(" and pcb_text.startswith("(footprint", i):
            after = i + len("(footprint")
            if after < n and pcb_text[after] in ' \t\n"':
                end = _find_matching_paren(pcb_text, i)
                # lib id is the first quoted string after the token
                q = pcb_text.find('"', after, end)
                lib_id = ""
                if q != -1:
                    q_end = _skip_string(pcb_text, q)
                    lib_id = pcb_text[q + 1 : q_end - 1]
                line_start = pcb_text.rfind("\n", 0, i) + 1
                indent = pcb_text[line_start:i]
                if indent.strip() == "":
                    blocks.append(FootprintBlock(lib_id=lib_id, start=i, end=end, indent=indent))
                i = end + 1
                continue
        i += 1
    return blocks


# --------------------------------------------------------------------------
# Model block extraction from .kicad_mod sources
# --------------------------------------------------------------------------


def extract_model_blocks(mod_text: str) -> list[str]:
    """Extract every ``(model ...)`` node from ``.kicad_mod`` text.

    Returns the raw node texts *dedented* so the first line starts with
    ``(model`` and continuation lines keep only their indentation relative
    to the node (tabs).
    """
    blocks: list[str] = []
    i = 0
    n = len(mod_text)
    while i < n:
        c = mod_text[i]
        if c == '"':
            i = _skip_string(mod_text, i)
            continue
        if c == "(" and mod_text.startswith("(model", i):
            after = i + len("(model")
            if after < n and mod_text[after] in ' \t\n"':
                end = _find_matching_paren(mod_text, i)
                raw = mod_text[i : end + 1]
                line_start = mod_text.rfind("\n", 0, i) + 1
                base_indent = mod_text[line_start:i]
                blocks.append(_dedent_block(raw, base_indent))
                i = end + 1
                continue
        i += 1
    return blocks


def _dedent_block(raw: str, base_indent: str) -> str:
    """Strip *base_indent* from the continuation lines of a raw node text."""
    if not base_indent:
        return raw
    lines = raw.split("\n")
    out = [lines[0]]
    for line in lines[1:]:
        out.append(line.removeprefix(base_indent))
    return "\n".join(out)


def _indent_block(block: str, indent: str) -> str:
    """Prefix every line of a dedented node text with *indent*."""
    return "\n".join(indent + line if line else line for line in block.split("\n"))


# --------------------------------------------------------------------------
# Pad-1 origin-convention offset
# --------------------------------------------------------------------------


def _pad_anchor(block_text: str) -> tuple[float, float] | None:
    """Return the pad *centroid* of a footprint block, in local coordinates.

    Scans *block_text* (a full ``(footprint ...)`` or ``.kicad_mod`` body,
    string-aware) for every copper ``(pad ...)`` node and averages the ``(at
    x y)`` positions.  The centroid -- not pad 1 alone -- is the anchor for
    the origin-convention offset because a STEP body is centered on the
    footprint's pad field: two footprints that share a centroid (even with
    different pad *pitch*, e.g. ``R_0805`` with 1.0mm vs the library's
    0.9125mm half-pitch) need **zero** offset, while a footprint translated
    off the library origin (e.g. a header re-centered from pad-1-at-origin to
    origin-centered) needs the centroid delta.

    A pad rotation angle (the optional third ``at`` field) is ignored: a
    pad's *position* is already in the footprint-local (unrotated) frame, so
    the centroid delta is well defined regardless of pad rotation.  Returns
    ``None`` when the block has no positioned pads (e.g. a footprint whose
    pads all lack an ``(at ...)``).
    """
    xs: list[float] = []
    ys: list[float] = []
    i = 0
    n = len(block_text)
    needle = "(pad"
    while i < n:
        c = block_text[i]
        if c == '"':
            i = _skip_string(block_text, i)
            continue
        if c == "(" and block_text.startswith(needle, i):
            after = i + len(needle)
            if after < n and block_text[after] in " \t\n":
                pad_end = _find_matching_paren(block_text, i)
                at = _find_first_at(block_text, i, pad_end)
                if at is not None:
                    xs.append(at[0])
                    ys.append(at[1])
                i = pad_end + 1
                continue
        i += 1
    if not xs:
        return None
    return sum(xs) / len(xs), sum(ys) / len(ys)


def _find_first_at(text: str, start: int, end: int) -> tuple[float, float] | None:
    """Return ``(x, y)`` of the first ``(at x y ...)`` in ``text[start:end]``."""
    i = start
    at_needle = "(at"
    while i < end:
        c = text[i]
        if c == '"':
            i = _skip_string(text, i)
            continue
        if c == "(" and text.startswith(at_needle, i):
            after = i + len(at_needle)
            if after < end and text[after] in " \t\n":
                close = _find_matching_paren(text, i)
                fields = text[after:close].split()
                if len(fields) >= 2:
                    try:
                        return float(fields[0]), float(fields[1])
                    except ValueError:
                        return None
                return None
        i += 1
    return None


def _pad_number(text: str, start: int, end: int) -> str:
    """Return the pad number (first quoted field) of a ``(pad ...)`` node.

    ``text[start:end]`` spans the pad node's interior (just past ``(pad``).
    Returns ``""`` when the pad carries no quoted number.
    """
    q = text.find('"', start, end)
    if q == -1:
        return ""
    q_end = _skip_string(text, q)
    return text[q + 1 : q_end - 1]


def _pad_positions(block_text: str) -> list[tuple[str, tuple[float, float]]]:
    """Return ``(pad_number, (x, y))`` for every positioned pad, in order.

    Scans *block_text* (a full ``(footprint ...)`` or ``.kicad_mod`` body,
    string-aware) for every copper ``(pad ...)`` node and records its number
    and ``(at x y)`` position.  Pads without an ``(at ...)`` are skipped.
    """
    out: list[tuple[str, tuple[float, float]]] = []
    i = 0
    n = len(block_text)
    needle = "(pad"
    while i < n:
        c = block_text[i]
        if c == '"':
            i = _skip_string(block_text, i)
            continue
        if c == "(" and block_text.startswith(needle, i):
            after = i + len(needle)
            if after < n and block_text[after] in " \t\n":
                pad_end = _find_matching_paren(block_text, i)
                number = _pad_number(block_text, after, pad_end)
                at = _find_first_at(block_text, i, pad_end)
                if at is not None:
                    out.append((number, at))
                i = pad_end + 1
                continue
        i += 1
    return out


def _pad_field_orientation(block_text: str) -> float | None:
    """Return the pad-field orientation of a footprint block, in degrees.

    The orientation is the angle (``atan2(dy, dx)``, degrees) of the vector
    from pad ``"1"`` to pad ``"2"`` in the footprint-local 2D frame.  When the
    numbered pads ``"1"`` / ``"2"`` are not both present, the first two
    positioned pads (document order) are used as a fallback.

    Returns ``None`` when fewer than two positioned pads exist, or when the two
    anchor pads coincide (no derivable direction) -- callers then fall back to
    zero rotation.  A footprint whose pad field is rotated by ``theta`` from
    its library counterpart yields ``target - source == theta``.
    """
    pads = _pad_positions(block_text)
    if len(pads) < 2:
        return None
    by_number = dict(pads)
    if "1" in by_number and "2" in by_number:
        p1, p2 = by_number["1"], by_number["2"]
    else:
        p1, p2 = pads[0][1], pads[1][1]
    dx = p2[0] - p1[0]
    dy = p2[1] - p1[1]
    if abs(dx) < 1e-9 and abs(dy) < 1e-9:
        return None
    return math.degrees(math.atan2(dy, dx))


def _normalize_angle(deg: float) -> float:
    """Normalize an angle in degrees to the half-open range ``(-180, 180]``."""
    a = deg % 360.0
    if a > 180.0:
        a -= 360.0
    return a


def _rotate_point(point: tuple[float, float], theta_deg: float) -> tuple[float, float]:
    """Rotate *point* about the origin by *theta_deg* (footprint 2D frame, CCW)."""
    rad = math.radians(theta_deg)
    cos_t = math.cos(rad)
    sin_t = math.sin(rad)
    x, y = point
    return (x * cos_t - y * sin_t, x * sin_t + y * cos_t)


def _apply_offset_delta(model_block: str, dx: float, dy: float) -> str:
    """Return *model_block* with ``(dx, -dy)`` added into its ``(offset ...)``.

    KiCad's 3D-model ``(offset (xyz ...))`` lives in the model frame whose X
    matches the footprint X but whose **Y is negated** relative to the
    footprint 2D frame (Z is unchanged).  A pad-1 delta of ``(dx, dy)`` in
    footprint-local 2D coordinates therefore maps to a model offset delta of
    ``(dx, -dy, 0)``.

    Only the ``x`` and ``y`` numbers of the model's own ``(offset (xyz ...))``
    are rewritten; every other byte of the node is preserved.  When *dx* and
    *dy* are both (near) zero (target shares the library origin convention)
    the block is returned unchanged so already-correct footprints get a
    verbatim insert -- a 1nm tolerance absorbs centroid-averaging FP noise.
    """
    if abs(dx) < 1e-6 and abs(dy) < 1e-6:
        return model_block
    # Locate (offset ... (xyz X Y Z) ...) inside the model node.
    off_idx = model_block.find("(offset")
    if off_idx == -1:
        return model_block
    off_end = _find_matching_paren(model_block, off_idx)
    xyz_idx = model_block.find("(xyz", off_idx, off_end)
    if xyz_idx == -1:
        return model_block
    xyz_end = _find_matching_paren(model_block, xyz_idx)
    inner = model_block[xyz_idx + len("(xyz") : xyz_end]
    fields = inner.split()
    if len(fields) < 3:
        return model_block
    try:
        ox, oy, oz = float(fields[0]), float(fields[1]), float(fields[2])
    except ValueError:
        return model_block
    nx = _fmt_num(ox + dx)
    ny = _fmt_num(oy - dy)  # model-frame Y is negated vs footprint 2D Y
    nz = _fmt_num(oz)
    new_xyz = f"(xyz {nx} {ny} {nz})"
    return model_block[:xyz_idx] + new_xyz + model_block[xyz_end + 1 :]


def _fmt_num(value: float) -> str:
    """Format a float the way KiCad writes model offsets (no trailing zeros)."""
    if value == 0.0:
        value = 0.0  # normalize -0.0 -> 0.0
    # Round to a hair under KiCad's 6-dp model-offset precision to avoid FP
    # noise like 1.2699999999 while keeping legitimate sub-micron values.
    rounded = round(value, 6)
    if rounded == int(rounded):
        return str(int(rounded))
    return f"{rounded:g}"


def _apply_rotate_delta(model_block: str, theta_deg: float) -> str:
    """Return *model_block* with a model-frame Z rotation of ``-theta_deg`` baked in.

    *theta_deg* is the pad-field rotation of the target footprint relative to
    its library source, measured in the footprint 2D frame.  The KiCad 3D-model
    frame negates Y versus the footprint 2D frame, so a footprint-2D rotation of
    ``theta`` maps to a model-frame Z rotation of ``-theta`` (pinned by the
    regression tests).  The delta is added into the block's own ``(rotate (xyz
    X Y Z))`` Z field; X and Y are preserved.

    When *theta_deg* is (near) zero -- the co-oriented case (all SMD parts, the
    origin-convention offset fixtures) -- the block is returned unchanged so
    already-correct footprints get a verbatim insert.
    """
    if abs(_normalize_angle(theta_deg)) < 1e-6:
        return model_block
    rot_idx = model_block.find("(rotate")
    if rot_idx == -1:
        return model_block
    rot_end = _find_matching_paren(model_block, rot_idx)
    xyz_idx = model_block.find("(xyz", rot_idx, rot_end)
    if xyz_idx == -1:
        return model_block
    xyz_end = _find_matching_paren(model_block, xyz_idx)
    inner = model_block[xyz_idx + len("(xyz") : xyz_end]
    fields = inner.split()
    if len(fields) < 3:
        return model_block
    try:
        rx, ry, rz = float(fields[0]), float(fields[1]), float(fields[2])
    except ValueError:
        return model_block
    nz = _fmt_num(_normalize_angle(rz - theta_deg))  # footprint 2D theta -> model Z -theta
    new_xyz = f"(xyz {_fmt_num(rx)} {_fmt_num(ry)} {nz})"
    return model_block[:xyz_idx] + new_xyz + model_block[xyz_end + 1 :]


# --------------------------------------------------------------------------
# Resolvers: lib id -> dedented (model ...) block texts
# --------------------------------------------------------------------------


@dataclass
class ResolvedModels:
    """A resolver hit: the model block texts plus the source pad-field geometry.

    *models* are the dedented ``(model ...)`` node texts from the resolved
    library ``.kicad_mod``.  *source_anchor* is that footprint's own pad
    centroid (``None`` when it has no positioned pads), used to compute the
    origin-convention offset ``target_anchor - source_anchor`` at insertion
    time.  *source_orientation* is that footprint's pad-field orientation in
    degrees (``None`` when fewer than two positioned pads exist), used to
    compute the rotation ``theta = target_orientation - source_orientation``
    that a pad-field-rotated target footprint needs baked into its model.
    """

    models: list[str]
    source_anchor: tuple[float, float] | None = None
    source_orientation: float | None = None


# A resolver maps a lib id to its resolved models.  For backward
# compatibility it may return a bare ``list[str]`` (models only, no pad-1
# information -> zero offset applied) instead of a ``ResolvedModels``.
Resolver = Callable[[str], "ResolvedModels | list[str] | None"]


def _find_variant_mod(paths: LibraryPaths, library: str, name: str) -> Path | None:
    """Find a same-library name variant of a footprint (visual fallback).

    KiCad library footprints often exist only as suffixed variants of a
    family name (e.g. ``QFN-24-1EP_4x4mm_P0.5mm`` ships as
    ``QFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm``).  For 3D *models* — pure
    visual metadata — the variant's body is the right shape, so when the
    exact name is missing we accept a footprint in the same library whose
    name extends the requested one at a ``_`` or ``-`` boundary.

    Deterministic choice: plain variants beat ``ThermalVias`` specials,
    then shortest name, then lexicographic.
    """
    lib_dir = paths.get_library_path(library)
    if lib_dir is None:
        return None
    prefixes = (name + "_", name + "-")
    candidates = [p for p in lib_dir.glob("*.kicad_mod") if p.stem.startswith(prefixes)]
    if not candidates:
        return None
    candidates.sort(key=lambda p: ("ThermalVias" in p.stem, len(p.stem), p.stem))
    return candidates[0]


def make_library_resolver(
    library_paths: LibraryPaths | None = None,
    *,
    allow_variants: bool = True,
    allow_substitutions: bool = True,
    variant_log: dict[str, str] | None = None,
    substitution_log: dict[str, str] | None = None,
    lcsc_mapping: dict[str, str] | None = None,
    lcsc_fetch: bool = False,
    lcsc_cache_dir: Path | None = None,
    lcsc_log: dict[str, str] | None = None,
    lcsc_warn: Callable[[str], None] | None = None,
) -> Resolver:
    """Build a resolver that reads model refs from installed KiCad libraries.

    The resolver maps a footprint lib id (``"LED_THT:LED_D5.0mm"``) to the
    dedented ``(model ...)`` block(s) found in the corresponding installed
    ``.kicad_mod``.  Returns ``None`` when the library footprint can't be
    found and ``[]`` when it exists but carries no model reference.
    Results are cached per lib id.

    Resolution tiers (first hit wins):

    1. **Exact** installed footprint for ``library:name``.
    2. **Same-library variant** (``_find_variant_mod``) — a suffixed name in
       the same library, when ``allow_variants`` is set.
    3. **Cross-library substitution** (``model_substitutions``) — an explicit,
       curated ``lib_id -> lib_id`` mapping for generic/synthetic lib ids that
       have a body-compatible equivalent in a *different* library, when
       ``allow_substitutions`` is set.
    4. **LCSC/EasyEDA fetch-on-demand** (``lcsc_models``) — an explicit,
       committed ``lib_id -> C-number`` sidecar mapping whose STEP body is
       resolved from a local cache (fetched on demand from EasyEDA when
       ``lcsc_fetch`` is enabled), when *lcsc_mapping* is supplied.  The
       synthesized ``(model ...)`` ref points at ``${KCT_LCSC_3D_DIR}`` and is
       authored as **origin-centered** (``source_anchor=(0.0, 0.0)``) so the
       shared offset machinery lands the body on the target pad centroid.

    Args:
        library_paths: Explicit library location (default: auto-detect).
        allow_variants: When the exact footprint name is missing, fall back
            to a same-library name variant (see ``_find_variant_mod``).
        allow_substitutions: When exact + variant matching both miss, fall
            back to the curated cross-library substitution table.
        variant_log: Optional dict populated with ``lib_id -> variant stem``
            for every same-library variant match, so callers can report them.
        substitution_log: Optional dict populated with
            ``lib_id -> substitute lib_id`` for every cross-library
            substitution, so callers can report them.
        lcsc_mapping: Optional ``lib_id -> C-number`` sidecar mapping enabling
            the LCSC tier (tier 4).  Only lib ids present here are eligible.
        lcsc_fetch: When True, fetch a missing STEP from EasyEDA on a cache
            miss; default cache-only (no network).
        lcsc_cache_dir: Optional LCSC STEP cache directory (default:
            :func:`kicad_tools.pcb.lcsc_models.lcsc_cache_dir`).
        lcsc_log: Optional dict populated with ``lib_id -> C-number`` for every
            resolved LCSC match, so callers can report them.
        lcsc_warn: Optional ``callable(str)`` invoked on a fetch failure.
    """
    paths = library_paths if library_paths is not None else detect_kicad_library_path()
    cache: dict[str, ResolvedModels | None] = {}

    def _lookup_mod(lib_id: str) -> tuple[Path | None, str | None]:
        """Return (mod path, substitute lib id) for *lib_id*, or (None, None).

        The second element is set only when the match came from the
        cross-library substitution table.
        """
        library, name = parse_library_id(lib_id)
        if not library:
            return None, None
        mod_path = paths.get_footprint_file(library, name, fallback_search=False)
        if mod_path is not None:
            return mod_path, None
        if allow_variants:
            mod_path = _find_variant_mod(paths, library, name)
            if mod_path is not None:
                if variant_log is not None:
                    variant_log[lib_id] = mod_path.stem
                return mod_path, None
        if allow_substitutions:
            sub_id = substitute_lib_id(lib_id)
            if sub_id is not None:
                sub_lib, sub_name = parse_library_id(sub_id)
                if sub_lib:
                    mod_path = paths.get_footprint_file(sub_lib, sub_name, fallback_search=False)
                    if mod_path is not None:
                        return mod_path, sub_id
        return None, None

    def _resolve_lcsc(lib_id: str) -> ResolvedModels | None:
        """Tier 4: LCSC/EasyEDA fetch-on-demand.  Returns None when the lib id
        has no mapping, or the STEP is neither cached nor fetchable."""
        if not lcsc_mapping:
            return None
        lcsc_id = lcsc_mapping.get(lib_id)
        if not lcsc_id:
            return None
        # Imported lazily so the module (and the three installed-library tiers)
        # never depend on the LCSC client unless the LCSC tier is actually used.
        from kicad_tools.pcb.lcsc_models import resolve_lcsc_step, synthesize_model_block

        step_path = resolve_lcsc_step(
            lcsc_id,
            cache_dir=lcsc_cache_dir,
            fetch=lcsc_fetch,
            warn=lcsc_warn,
        )
        if step_path is None:
            # Skip-on-miss: report unresolved rather than emitting a ref to a
            # file that is known-absent at patch time.
            return None
        if lcsc_log is not None:
            lcsc_log[lib_id] = lcsc_id
        # Origin-authored body: explicit (0, 0) source anchor so the shared
        # offset math shifts by the full target pad centroid.
        return ResolvedModels(models=[synthesize_model_block(lcsc_id)], source_anchor=(0.0, 0.0))

    def resolve(lib_id: str) -> ResolvedModels | None:
        if lib_id in cache:
            return cache[lib_id]
        result: ResolvedModels | None = None
        if paths.found:
            mod_path, sub_id = _lookup_mod(lib_id)
            if mod_path is not None:
                try:
                    mod_text = mod_path.read_text()
                except OSError:
                    result = None
                else:
                    result = ResolvedModels(
                        models=extract_model_blocks(mod_text),
                        source_anchor=_pad_anchor(mod_text),
                        source_orientation=_pad_field_orientation(mod_text),
                    )
                    if sub_id is not None and substitution_log is not None:
                        substitution_log[lib_id] = sub_id
        if result is None:
            result = _resolve_lcsc(lib_id)
        cache[lib_id] = result
        return result

    return resolve


# --------------------------------------------------------------------------
# Patching
# --------------------------------------------------------------------------


@dataclass
class ModelPatchReport:
    """Summary of an ``add_model_refs`` run."""

    patched: list[str] = field(default_factory=list)
    """Lib ids that had model refs inserted (one entry per footprint)."""
    already_present: list[str] = field(default_factory=list)
    """Lib ids skipped because the footprint already has a model ref."""
    unresolved: list[str] = field(default_factory=list)
    """Lib ids skipped: not found in the installed KiCad libraries."""
    no_model_in_library: list[str] = field(default_factory=list)
    """Lib ids skipped: library footprint exists but has no model ref."""
    variant_matches: dict[str, str] = field(default_factory=dict)
    """Lib ids whose model came from a same-library name variant
    (``lib_id -> matched footprint name``)."""
    substitution_matches: dict[str, str] = field(default_factory=dict)
    """Lib ids whose model came from a cross-library substitution
    (``lib_id -> substitute lib_id``)."""
    lcsc_matches: dict[str, str] = field(default_factory=dict)
    """Lib ids whose model came from the LCSC/EasyEDA fetch tier
    (``lib_id -> C-number``)."""

    @property
    def changed(self) -> bool:
        return bool(self.patched)


def add_model_refs_to_text(pcb_text: str, resolver: Resolver) -> tuple[str, ModelPatchReport]:
    """Insert missing ``(model ...)`` refs into raw ``.kicad_pcb`` text.

    Pure text insertion: the returned text differs from *pcb_text* only by
    inserted model lines (never removed or reordered bytes), keeping the
    change strictly render-metadata-scoped.
    """
    report = ModelPatchReport()
    insertions: list[tuple[int, str]] = []  # (index, text) sorted ascending

    for block in iter_footprint_blocks(pcb_text):
        body = pcb_text[block.start : block.end + 1]
        if _contains_token(body, "model"):
            report.already_present.append(block.lib_id)
            continue
        resolved = resolver(block.lib_id)
        if resolved is None:
            report.unresolved.append(block.lib_id)
            continue
        # Accept a bare list[str] (legacy resolvers) or a ResolvedModels.
        if isinstance(resolved, ResolvedModels):
            models = resolved.models
            source_anchor = resolved.source_anchor
            source_orientation = resolved.source_orientation
        else:
            models = resolved
            source_anchor = None
            source_orientation = None
        if not models:
            report.no_model_in_library.append(block.lib_id)
            continue
        # Orientation-convention rotation: a target footprint whose pad field
        # is rotated relative to its library source (rotation baked into pad
        # coordinates rather than the placement angle) needs the delta baked
        # into the model's (rotate ...).  theta is measured in the footprint
        # 2D frame; the model frame negates Y, so _apply_rotate_delta bakes a
        # model-frame Z of -theta.  When either orientation is underivable
        # (single-pad parts, LCSC-synthesized bodies) theta stays 0.
        target_orientation = _pad_field_orientation(body)
        theta = 0.0
        if source_orientation is not None and target_orientation is not None:
            theta = _normalize_angle(target_orientation - source_orientation)
        # Origin-convention offset, composed in the rotated frame: shift the
        # body by target_anchor - R_theta * source_anchor (pad centroids) so
        # the model lands on the target footprint's pads after rotation.  With
        # theta == 0 this reduces to the plain target - source centroid delta.
        target_anchor = _pad_anchor(body)
        dx = dy = 0.0
        if source_anchor is not None and target_anchor is not None:
            rsx, rsy = _rotate_point(source_anchor, theta)
            dx = target_anchor[0] - rsx
            dy = target_anchor[1] - rsy
        # Insert before the line that holds the footprint's closing paren.
        close_line_start = pcb_text.rfind("\n", 0, block.end) + 1
        child_indent = block.indent + "\t"
        text = "".join(
            _indent_block(_apply_rotate_delta(_apply_offset_delta(m, dx, dy), theta), child_indent)
            + "\n"
            for m in models
        )
        insertions.append((close_line_start, text))
        report.patched.append(block.lib_id)

    if not insertions:
        return pcb_text, report

    out: list[str] = []
    prev = 0
    for idx, text in insertions:
        out.append(pcb_text[prev:idx])
        out.append(text)
        prev = idx
    out.append(pcb_text[prev:])
    return "".join(out), report


def add_model_refs(
    pcb_path: Path | str,
    *,
    output_path: Path | str | None = None,
    library_paths: LibraryPaths | None = None,
    resolver: Resolver | None = None,
    allow_variants: bool = True,
    allow_substitutions: bool = True,
    lcsc_mapping: dict[str, str] | None = None,
    lcsc_fetch: bool = False,
    lcsc_cache_dir: Path | None = None,
    lcsc_warn: Callable[[str], None] | None = None,
    dry_run: bool = False,
) -> ModelPatchReport:
    """Patch missing 3D model refs into a ``.kicad_pcb`` file.

    Args:
        pcb_path: PCB file to patch.
        output_path: Where to write the patched file (default: in place).
        library_paths: Optional explicit KiCad library location (defaults to
            auto-detection of the installed KiCad footprint libraries).
        resolver: Optional custom lib-id resolver (overrides library_paths).
        allow_variants: Accept same-library footprint-name variants when the
            exact name is missing (visual fallback; reported in
            ``variant_matches``). Ignored when *resolver* is supplied.
        allow_substitutions: Accept curated cross-library substitutions when
            exact + variant matching both miss (reported in
            ``substitution_matches``). Ignored when *resolver* is supplied.
        lcsc_mapping: Optional ``lib_id -> C-number`` sidecar enabling the LCSC
            fetch tier (reported in ``lcsc_matches``). Ignored when *resolver*
            is supplied.
        lcsc_fetch: When True, fetch a missing LCSC STEP on a cache miss;
            default cache-only (no network). Ignored when *resolver* is
            supplied.
        lcsc_cache_dir: Optional LCSC STEP cache directory. Ignored when
            *resolver* is supplied.
        lcsc_warn: Optional ``callable(str)`` invoked on an LCSC fetch failure.
            Ignored when *resolver* is supplied.
        dry_run: When True, nothing is written.

    Returns:
        ModelPatchReport describing what was (or would be) inserted.
    """
    pcb_path = Path(pcb_path)
    text = pcb_path.read_text()
    variant_log: dict[str, str] = {}
    substitution_log: dict[str, str] = {}
    lcsc_log: dict[str, str] = {}
    if resolver is None:
        resolver = make_library_resolver(
            library_paths,
            allow_variants=allow_variants,
            allow_substitutions=allow_substitutions,
            variant_log=variant_log,
            substitution_log=substitution_log,
            lcsc_mapping=lcsc_mapping,
            lcsc_fetch=lcsc_fetch,
            lcsc_cache_dir=lcsc_cache_dir,
            lcsc_log=lcsc_log,
            lcsc_warn=lcsc_warn,
        )
    new_text, report = add_model_refs_to_text(text, resolver)
    # Only surface variants/substitutions that actually got patched in.
    report.variant_matches = {
        lib_id: stem for lib_id, stem in variant_log.items() if lib_id in report.patched
    }
    report.substitution_matches = {
        lib_id: sub for lib_id, sub in substitution_log.items() if lib_id in report.patched
    }
    report.lcsc_matches = {
        lib_id: cnum for lib_id, cnum in lcsc_log.items() if lib_id in report.patched
    }
    if report.changed and not dry_run:
        dest = Path(output_path) if output_path is not None else pcb_path
        dest.write_text(new_text)
    return report
