"""Pure Python DRC validation for KiCad PCB designs.

This module provides a DRC checker that validates PCB designs against
manufacturer design rules without requiring kicad-cli to be installed.

Example:
    >>> from kicad_tools.schema.pcb import PCB
    >>> from kicad_tools.validate import DRCChecker, DRCViolation, DRCResults
    >>>
    >>> pcb = PCB.load("board.kicad_pcb")
    >>> checker = DRCChecker(pcb, manufacturer="jlcpcb", layers=4)
    >>> results = checker.check_all()
    >>>
    >>> print(results.summary())
    >>> for violation in results:
    ...     print(f"  {violation.rule_id}: {violation.message}")

Difference from ``kicad_tools.drc``:
    - ``kicad_tools.drc``: Parses DRC reports generated by kicad-cli
    - ``kicad_tools.validate``: Performs DRC checks in pure Python (no kicad-cli)
"""

from .checker import DRCChecker
from .violations import DRCResults, DRCViolation

__all__ = [
    "DRCChecker",
    "DRCViolation",
    "DRCResults",
]
