#!/usr/bin/env python3
"""
Re-annotate reference designators in KiCad schematics.

Renumbers reference designators sequentially across the hierarchy,
closing gaps and making numbering contiguous.  Also annotates
unannotated components (``R?``, ``C?``, etc.) and creates missing
``(instances)`` blocks for multi-project schematics.

Usage:
    # Preview changes
    kicad-tools sch re-annotate board.kicad_sch --dry-run

    # Renumber all refs starting from 1
    kicad-tools sch re-annotate board.kicad_sch

    # Only renumber resistors and capacitors
    kicad-tools sch re-annotate board.kicad_sch --prefix R,C

    # Start numbering from 100
    kicad-tools sch re-annotate board.kicad_sch --start-from 100

    # Restart numbering per sheet
    kicad-tools sch re-annotate board.kicad_sch --per-sheet
"""

import re
import sys
from pathlib import Path

from kicad_tools.cli.modify_schematic import create_backup
from kicad_tools.cli.sch_set_footprint import _collect_schematic_files

# Prefixes for power/flag symbols that should be excluded from renumbering
# by default.  When ``include_power=True`` is passed, ``#PWR`` and ``#FLG``
# are allowed through; ``#SYM`` is always excluded (internal KiCad artifact).
EXCLUDED_PREFIXES = {"#PWR", "#FLG", "#SYM"}

# Prefixes that may be included when ``--include-power`` is active.
_POWER_PREFIXES = {"#PWR", "#FLG"}

# Whitespace token for regex: matches one or more tabs or spaces
_WS = r'[ \t]+'


def _format_reference(prefix: str, number: int, unit_suffix: str = "") -> str:
    """Format a reference designator, applying zero-padding for power prefixes.

    KiCad uses 2-digit zero-padded numbers for power symbols
    (``#PWR01``, ``#FLG01``, ``#PWR12``).  All other prefixes use
    plain integers (``R1``, ``C10``).
    """
    if prefix in _POWER_PREFIXES:
        return f"{prefix}{number:02d}{unit_suffix}"
    return f"{prefix}{number}{unit_suffix}"


def _detect_indent(text: str) -> str:
    """Detect the indentation unit used in a schematic file.

    Looks at the first indented line to determine whether the file uses
    tabs or spaces (and how many spaces per level).

    Returns:
        The single-level indent string (e.g. ``'\\t'`` or ``'  '``).
    """
    for line in text.splitlines():
        if line and line[0] in (' ', '\t'):
            # Count leading whitespace
            stripped = line.lstrip(' \t')
            leading = line[:len(line) - len(stripped)]
            if '\t' in leading:
                return '\t'
            # Assume the first indented line is at depth 1
            # Common space counts: 2 or 4
            return leading
    return '\t'


def _parse_reference(ref: str) -> tuple[str, int | None, str]:
    """Parse a reference designator into (prefix, number, unit_suffix).

    Examples:
        "R1"   -> ("R", 1, "")
        "U1A"  -> ("U", 1, "A")
        "C32"  -> ("C", 32, "")
        "#PWR01" -> ("#PWR", 1, "")
        "R?"   -> ("R", None, "")
    """
    # Match prefix (letters/underscores, optionally starting with #), number, optional unit letter
    m = re.match(r'^(#?[A-Za-z_]+)(\d+)([A-Za-z]?)$', ref)
    if m:
        return m.group(1), int(m.group(2)), m.group(3)
    # Unannotated reference like "R?" or "#PWR_FLAG?"
    m = re.match(r'^(#?[A-Za-z_]+)\?$', ref)
    if m:
        return m.group(1), None, ""
    return ref, None, ""


def _extract_symbols_from_text(text: str) -> list[dict]:
    """Extract symbol references and their positions from schematic text.

    Returns list of dicts with keys: reference, prefix, number, unit_suffix,
    position_y, position_x, lib_id, uuid, has_project_instance.

    Two passes are performed:
    1. Main pass: matches symbol blocks ending with an ``(instances)`` block
       or a ``(pin ...)`` entry — covers the vast majority of real schematics.
    2. Unannotated-only pass: finds symbols with a ``?`` reference that have
       *neither* an instances block nor any pin entries.  These bare symbols
       are generated by KiCad when a component is placed but not yet
       annotated and saved before the project is fully set up.
    """
    ref_pattern = re.compile(r'\(property "Reference" "([^"]+)"')
    symbols = []

    # Find all symbol blocks that have lib_id (instances, not lib definitions)
    # Use _WS instead of literal \t to support both tab and space indentation
    block_pattern = re.compile(
        _WS + r'\(symbol\n'
        + _WS + r'\(lib_id "[^"]+"\)'
        r'.*?'
        r'(?:' + _WS + r'\(instances\n.*?' + _WS + r'\)\n' + _WS + r'\)'
        r'|' + _WS + r'\(pin "[^"]+"\n' + _WS + r'\(uuid "[^"]+"\)\n' + _WS + r'\)\n' + _WS + r'\))',
        re.DOTALL,
    )

    seen_uuids: set[str] = set()

    for match in block_pattern.finditer(text):
        block = match.group(0)
        lib_match = re.search(r'\(lib_id "([^"]+)"\)', block)
        at_match = re.search(r'\(at ([\d.eE+-]+) ([\d.eE+-]+)', block)
        ref_match = ref_pattern.search(block)
        uuid_match = re.search(r'\(uuid "([^"]+)"\)', block)

        if not ref_match or not lib_match:
            continue

        ref = ref_match.group(1)
        lib_id = lib_match.group(1)
        sym_uuid = uuid_match.group(1) if uuid_match else ""
        x = float(at_match.group(1)) if at_match else 0.0
        y = float(at_match.group(2)) if at_match else 0.0

        prefix, number, unit_suffix = _parse_reference(ref)

        seen_uuids.add(sym_uuid)
        symbols.append({
            "reference": ref,
            "prefix": prefix,
            "number": number,
            "unit_suffix": unit_suffix,
            "position_x": x,
            "position_y": y,
            "lib_id": lib_id,
            "uuid": sym_uuid,
        })

    # Second pass: find unannotated symbols (Reference contains "?") that have
    # no (instances) block and no (pin) entries.  These are "bare" symbol blocks
    # ending with just (uuid "...")\n_WS) and are missed by the main pattern.
    #
    # Strategy: scan for unannotated Reference properties, then locate the
    # enclosing symbol block using the uuid that immediately precedes the
    # block's closing paren.
    unannotated_ref_pattern = re.compile(r'\(property "Reference" "([^"]*\?[^"]*)"')
    uuid_pattern = re.compile(r'\(uuid "([^"]+)"\)')
    symbol_start_pattern = re.compile(_WS + r'\(symbol\n')
    block_close_pattern = re.compile(r'\n' + _WS + r'\)')

    for ref_match in unannotated_ref_pattern.finditer(text):
        ref = ref_match.group(1)

        # Find the uuid closest after the Reference property within the same block.
        # We search forward from the reference property for a uuid.
        uuid_match = uuid_pattern.search(text, ref_match.end())
        if uuid_match is None:
            continue
        sym_uuid = uuid_match.group(1)

        # Skip symbols already captured by the main pass
        if sym_uuid in seen_uuids:
            continue

        # Find the symbol block start by walking backward from the reference
        block_start = -1
        for m in symbol_start_pattern.finditer(text, 0, ref_match.start()):
            block_start = m.start()
        if block_start == -1:
            continue

        # The block ends with \n<ws>) after the uuid
        close_match = block_close_pattern.search(text, uuid_match.end())
        if close_match is None:
            continue
        block_end = close_match.end()

        block = text[block_start:block_end]

        lib_match = re.search(r'\(lib_id "([^"]+)"\)', block)
        if not lib_match:
            continue
        lib_id = lib_match.group(1)

        at_match = re.search(r'\(at ([\d.eE+-]+) ([\d.eE+-]+)', block)
        x = float(at_match.group(1)) if at_match else 0.0
        y = float(at_match.group(2)) if at_match else 0.0

        prefix, number, unit_suffix = _parse_reference(ref)

        seen_uuids.add(sym_uuid)
        symbols.append({
            "reference": ref,
            "prefix": prefix,
            "number": number,
            "unit_suffix": unit_suffix,
            "position_x": x,
            "position_y": y,
            "lib_id": lib_id,
            "uuid": sym_uuid,
        })

    return symbols


def _apply_reference_rename(text: str, old_ref: str, new_ref: str) -> str:
    """Rename a reference designator in schematic text.

    Updates both:
    - (property "Reference" "OLD" ...) -> (property "Reference" "NEW" ...)
    - (reference "OLD") -> (reference "NEW") in instances blocks
    """
    # Update property "Reference" value
    text = re.sub(
        r'(\(property "Reference" ")' + re.escape(old_ref) + r'"',
        r'\g<1>' + new_ref + '"',
        text,
    )

    # Update (reference "OLD") in instances blocks
    text = re.sub(
        r'(\(reference ")' + re.escape(old_ref) + r'"\)',
        r'\g<1>' + new_ref + '")',
        text,
    )

    return text


def _apply_uuid_reference_rename(text: str, sym_uuid: str, new_ref: str) -> str:
    """Rename a reference designator for a specific symbol identified by UUID.

    This is needed for unannotated components (``R?``, ``C?``) where the
    reference string is shared by multiple components in the same file.
    Targets the symbol block containing the given UUID.
    """
    # Strategy: find the symbol block boundaries first, then modify within.
    # Symbol blocks start with <indent>(symbol\n and end with <indent>).
    # We find the block that contains our UUID and replace within it.
    uuid_str = f'(uuid "{sym_uuid}")'
    uuid_pos = text.find(uuid_str)
    if uuid_pos == -1:
        return text

    # Walk backward to find the start of this symbol block using regex
    # to support both tab and space indentation
    start_pattern = re.compile(_WS + r'\(symbol\n')
    block_start = -1
    for m in start_pattern.finditer(text, 0, uuid_pos):
        block_start = m.start()
    if block_start == -1:
        return text

    # Walk forward to find the end of this symbol block (\n<indent>) at depth 1)
    end_pattern = re.compile(r'\n' + _WS + r'\)')
    end_match = end_pattern.search(text, uuid_pos)
    if end_match is None:
        return text
    block_end = end_match.end()

    block = text[block_start:block_end]

    # Replace the Reference property within this specific block
    new_block = re.sub(
        r'(\(property "Reference" ")[^"]+"',
        r'\g<1>' + new_ref + '"',
        block,
        count=1,
    )

    return text[:block_start] + new_block + text[block_end:]


def _detect_project_info(
    root_path: Path,
    all_files: list[Path],
) -> tuple[str, str, dict[Path, str]]:
    """Detect project name, root UUID, and sheet UUID paths.

    For multi-project schematics, the project name is derived from the
    root schematic filename.  The instance path for each sub-sheet is
    ``/<root_uuid>/<sheet_uuid>``.

    Returns:
        Tuple of (project_name, root_uuid, file_to_instance_path_map).
    """
    project_name = root_path.stem
    root_text = root_path.read_text(encoding="utf-8")

    # Find root schematic UUID (first uuid at top level)
    root_uuid_match = re.search(r'^' + _WS + r'\(uuid "([^"]+)"\)', root_text, re.MULTILINE)
    root_uuid = root_uuid_match.group(1) if root_uuid_match else ""

    # Build map of sub-sheet file -> instance path
    # Parse sheet blocks from root: (sheet ... (uuid "XXX") ... (property "Sheetfile" "file.kicad_sch"))
    file_paths: dict[Path, str] = {
        root_path: f"/{root_uuid}",
    }

    sheet_pattern = re.compile(
        r'\(sheet\b.*?\(uuid "([^"]+)"\).*?\(property "Sheetfile" "([^"]+)".*?\)',
        re.DOTALL,
    )
    for m in sheet_pattern.finditer(root_text):
        sheet_uuid = m.group(1)
        sheet_file = m.group(2)
        sheet_path = root_path.parent / sheet_file
        file_paths[sheet_path] = f"/{root_uuid}/{sheet_uuid}"

    return project_name, root_uuid, file_paths


def _find_symbol_block_bounds(text: str, sym_uuid: str) -> tuple[int, int] | None:
    """Return (start, end) byte offsets of the symbol block containing *sym_uuid*.

    The returned range covers from the leading whitespace of ``(symbol\\n``
    to the end of the line containing the symbol's closing ``)``.

    Returns ``None`` if the uuid is not found or the block cannot be delimited.
    """
    uuid_str = f'(uuid "{sym_uuid}")'
    uuid_pos = text.find(uuid_str)
    if uuid_pos == -1:
        return None

    # Walk backward to find the most recent (symbol\n start before the uuid
    start_pattern = re.compile(_WS + r'\(symbol\n')
    block_start = -1
    for m in start_pattern.finditer(text, 0, uuid_pos):
        block_start = m.start()
    if block_start == -1:
        return None

    # Walk forward from the uuid to find the symbol block's closing )
    # Symbol blocks close with \n<indent1>) where indent1 is a single
    # indentation unit.  We find the first \n<ws>) that is NOT followed by
    # more content at the same depth (i.e. ends the outermost symbol block).
    # For simplicity we track nesting depth by counting unmatched ( vs ).
    depth = 0
    i = block_start
    in_string = False
    while i < len(text):
        ch = text[i]
        if ch == '"':
            in_string = not in_string
        elif not in_string:
            if ch == '(':
                depth += 1
            elif ch == ')':
                depth -= 1
                if depth == 0:
                    # This ) closes the outermost (symbol ...) block
                    # Consume to end of line
                    end = i + 1
                    if end < len(text) and text[end] == '\n':
                        end += 1
                    return (block_start, end)
        i += 1

    return None


def _add_project_instance(
    text: str,
    sym_uuid: str,
    project_name: str,
    instance_path: str,
    new_ref: str,
    unit: int = 1,
) -> str:
    """Add a project instance entry to a symbol's (instances) block.

    If the symbol has an ``(instances)`` block, appends a new
    ``(project "name" ...)`` entry.  If the symbol has no
    ``(instances)`` block, creates one before the closing ``)``.

    Uses a positional approach to locate the symbol block so that symbols
    are never confused with each other even when processed sequentially
    within the same file.

    Args:
        text: Full schematic text.
        sym_uuid: UUID of the target symbol.
        project_name: Project name for the instance entry.
        instance_path: Full hierarchy path (e.g. ``/root-uuid/sheet-uuid``).
        new_ref: Reference designator to use in the instance.
        unit: Unit number (default 1).

    Returns:
        Modified schematic text.
    """
    # Detect the indentation unit used in this file
    ind = _detect_indent(text)
    i2 = ind * 2
    i3 = ind * 3
    i4 = ind * 4
    i5 = ind * 5

    instance_entry = (
        f'{i3}(project "{project_name}"\n'
        f'{i4}(path "{instance_path}"\n'
        f'{i5}(reference "{new_ref}")\n'
        f'{i5}(unit {unit})\n'
        f'{i4})\n'
        f'{i3})\n'
    )

    # Locate the exact symbol block for this UUID using positional bounds
    bounds = _find_symbol_block_bounds(text, sym_uuid)
    if bounds is None:
        return text

    block_start, block_end = bounds
    block = text[block_start:block_end]

    # Case 1: Block already has an (instances) block — append a new project entry
    instances_pattern = re.compile(
        r'(' + _WS + r'\(instances\n)'
        r'(.*?)'
        r'(' + _WS + r'\)\n' + _WS + r'\))',
        re.DOTALL,
    )
    inst_match = instances_pattern.search(block)
    if inst_match:
        instances_body = inst_match.group(2)
        if f'(project "{project_name}"' in instances_body:
            return text
        # Insert new project entry before the closing ) of the instances block
        new_body = (
            inst_match.group(1)
            + instances_body
            + instance_entry
            + inst_match.group(3)
        )
        new_block = block[:inst_match.start()] + new_body + block[inst_match.end():]
        return text[:block_start] + new_block + text[block_end:]

    # Case 2: No instances block.  Insert one before the symbol's closing ).
    # Find the closing ) of the symbol block — it is the last ) in the block.
    # The block ends with \n<ws>) so we insert the instances block before it.
    close_pattern = re.compile(r'\n(' + _WS + r'\))$')
    close_match = close_pattern.search(block)
    if close_match is None:
        return text

    instances_block = (
        f'{i2}(instances\n'
        f'{instance_entry}'
        f'{i2})\n'
    )
    insert_pos = close_match.start() + 1  # after the \n, before the <ws>)
    new_block = block[:insert_pos] + instances_block + block[insert_pos:]
    return text[:block_start] + new_block + text[block_end:]


def run_re_annotate(
    schematic_path: Path,
    dry_run: bool = False,
    backup: bool = True,
    prefixes: list[str] | None = None,
    start_from: int = 1,
    per_sheet: bool = False,
    format: str = "text",
    unannotated_only: bool = False,
    include_power: bool = False,
) -> int:
    """Run the re-annotate operation.

    Args:
        schematic_path: Path to root .kicad_sch file.
        dry_run: If True, show mapping without modifying files.
        backup: If True, create backups before modifying.
        prefixes: If set, only renumber these prefixes (e.g., ["R", "C"]).
        start_from: Starting number for each prefix (default 1).
        per_sheet: If True, restart numbering per sheet.
        format: Output format ("text" or "json").
        unannotated_only: If True, only assign numbers to unannotated (``?``)
            references, leaving already-assigned references unchanged.
        include_power: If True, also annotate ``#PWR?`` and ``#FLG?`` power
            symbols (excluded by default).

    Returns:
        0 on success, 1 on error.
    """
    if not schematic_path.exists():
        print(f"Error: File not found: {schematic_path}", file=sys.stderr)
        return 1

    # Collect all schematic files in hierarchy order
    all_files = _collect_schematic_files(schematic_path)

    if not all_files:
        print("Error: No schematic files found", file=sys.stderr)
        return 1

    # Detect project info for multi-project instance handling
    project_name, root_uuid, file_instance_paths = _detect_project_info(
        schematic_path, all_files
    )

    # Phase 1: Collect all symbols across hierarchy
    file_symbols: dict[Path, list[dict]] = {}
    file_texts: dict[Path, str] = {}

    for sch_file in all_files:
        try:
            text = sch_file.read_text(encoding="utf-8")
        except OSError as e:
            print(f"Error reading {sch_file}: {e}", file=sys.stderr)
            return 1
        file_texts[sch_file] = text
        file_symbols[sch_file] = _extract_symbols_from_text(text)

    # Phase 2: Build rename mapping
    # The mapping is now keyed by UUID to handle unannotated refs (R?, C?)
    # that share the same reference string across multiple components.

    if per_sheet:
        uuid_mapping = _build_per_sheet_mapping(
            all_files, file_symbols, prefixes, start_from,
            unannotated_only=unannotated_only,
            include_power=include_power,
        )
    else:
        uuid_mapping = _build_continuous_mapping(
            all_files, file_symbols, prefixes, start_from,
            unannotated_only=unannotated_only,
            include_power=include_power,
        )

    if not uuid_mapping:
        print("No references to renumber.")
        return 0

    # Filter out identity mappings
    effective_mapping = {
        uid: info for uid, info in uuid_mapping.items()
        if info["old"] != info["new"]
    }

    if not effective_mapping:
        print("All references are already sequential. No changes needed.")
        return 0

    # Phase 3: Output mapping / apply changes
    if format == "json":
        import json
        output = {
            "mappings": [
                {"old": info["old"], "new": info["new"], "uuid": uid}
                for uid, info in sorted(
                    effective_mapping.items(), key=lambda x: x[1]["new"]
                )
            ],
            "total": len(effective_mapping),
            "dry_run": dry_run,
        }
        print(json.dumps(output, indent=2))
    else:
        print(f"Re-annotation mapping ({len(effective_mapping)} changes):")
        print()

        # Group by prefix for display
        by_prefix: dict[str, list[tuple[str, str]]] = {}
        for uid, info in sorted(
            effective_mapping.items(), key=lambda x: x[1]["new"]
        ):
            prefix, _, _ = _parse_reference(info["new"])
            by_prefix.setdefault(prefix, []).append((info["old"], info["new"]))

        for prefix in sorted(by_prefix):
            changes = by_prefix[prefix]
            print(f"  {prefix}:")
            for old, new in changes:
                print(f"    {old} -> {new}")
        print()

    if dry_run:
        if format == "text":
            print("Dry run: no changes made.")
        return 0

    # Phase 4: Apply the full mapping to each file
    # For annotated refs (unique reference strings), use the two-pass rename.
    # For unannotated refs (R?, C?), use UUID-targeted replacement.
    modified_files: dict[Path, str] = {}

    for sch_file in all_files:
        text = file_texts[sch_file]
        syms = file_symbols[sch_file]
        uuids_in_file = {s["uuid"] for s in syms}

        # Partition mappings for this file into annotated vs unannotated
        annotated_mapping: dict[str, str] = {}  # old_ref -> new_ref
        unannotated_entries: list[dict] = []  # [{uuid, new_ref}, ...]

        for uid, info in uuid_mapping.items():
            if uid not in uuids_in_file:
                continue
            if info["unannotated"]:
                unannotated_entries.append({
                    "uuid": uid,
                    "old": info["old"],
                    "new": info["new"],
                })
            else:
                if info["old"] != info["new"]:
                    annotated_mapping[info["old"]] = info["new"]

        if not annotated_mapping and not unannotated_entries:
            continue

        current_text = text

        # Step A: Handle annotated refs with two-pass rename to avoid collisions
        if annotated_mapping:
            temp_mapping: dict[str, str] = {}
            for i, old_ref in enumerate(annotated_mapping):
                temp_ref = f"__REANNOTATE_TEMP_{i}__"
                temp_mapping[old_ref] = temp_ref

            for old_ref, temp_ref in temp_mapping.items():
                current_text = _apply_reference_rename(current_text, old_ref, temp_ref)

            for old_ref, temp_ref in temp_mapping.items():
                new_ref = annotated_mapping[old_ref]
                current_text = _apply_reference_rename(current_text, temp_ref, new_ref)

        # Step B: Handle unannotated refs with UUID-targeted replacement
        instance_path = file_instance_paths.get(sch_file, "")
        for entry in unannotated_entries:
            current_text = _apply_uuid_reference_rename(
                current_text, entry["uuid"], entry["new"]
            )
            # Add project instance entry
            if instance_path:
                current_text = _add_project_instance(
                    current_text,
                    entry["uuid"],
                    project_name,
                    instance_path,
                    entry["new"],
                )

        modified_files[sch_file] = current_text

    # Phase 5: Write modified files
    if modified_files:
        for sch_file, new_text in modified_files.items():
            if backup:
                bak = create_backup(sch_file)
                if format == "text":
                    print(f"  Backup: {bak.name}")
            try:
                sch_file.write_text(new_text, encoding="utf-8")
            except OSError as e:
                print(f"Error writing {sch_file}: {e}", file=sys.stderr)
                return 1

    if format == "text":
        print(
            f"Re-annotated {len(effective_mapping)} reference(s) "
            f"across {len(modified_files)} file(s)."
        )

    return 0


def _build_continuous_mapping(
    all_files: list[Path],
    file_symbols: dict[Path, list[dict]],
    prefixes: list[str] | None,
    start_from: int,
    *,
    unannotated_only: bool = False,
    include_power: bool = False,
) -> dict[str, dict]:
    """Build a continuous UUID-keyed mapping across all files.

    Symbols are ordered by file order, then by position (top-to-bottom,
    left-to-right) within each file. Multi-unit components share a base
    number.

    Returns:
        Dict mapping UUID -> {"old": str, "new": str, "unannotated": bool}.
    """
    ordered_symbols: list[dict] = []
    for sch_file in all_files:
        syms = file_symbols[sch_file]
        syms_sorted = sorted(syms, key=lambda s: (s["position_y"], s["position_x"]))
        ordered_symbols.extend(syms_sorted)

    return _assign_numbers(ordered_symbols, prefixes, start_from,
                           unannotated_only=unannotated_only,
                           include_power=include_power)


def _build_per_sheet_mapping(
    all_files: list[Path],
    file_symbols: dict[Path, list[dict]],
    prefixes: list[str] | None,
    start_from: int,
    *,
    unannotated_only: bool = False,
    include_power: bool = False,
) -> dict[str, dict]:
    """Build a per-sheet UUID-keyed mapping, restarting numbering per file."""
    mapping: dict[str, dict] = {}

    for sch_file in all_files:
        syms = file_symbols[sch_file]
        syms_sorted = sorted(syms, key=lambda s: (s["position_y"], s["position_x"]))
        sheet_mapping = _assign_numbers(syms_sorted, prefixes, start_from,
                                        unannotated_only=unannotated_only,
                                        include_power=include_power)
        mapping.update(sheet_mapping)

    return mapping


def _assign_numbers(
    symbols: list[dict],
    prefixes: list[str] | None,
    start_from: int,
    *,
    unannotated_only: bool = False,
    include_power: bool = False,
) -> dict[str, dict]:
    """Assign sequential numbers to symbols, handling multi-unit components.

    Multi-unit components (e.g., U1A and U1B) share the same base reference
    number but differ by their unit suffix.

    When *unannotated_only* is ``True``, only symbols with unannotated
    references (e.g. ``R?``) receive new numbers.  Already-assigned
    references are left unchanged and their numbers are reserved so that
    new assignments do not collide with them.

    When *include_power* is ``True``, ``#PWR`` and ``#FLG`` prefixes are
    no longer excluded, allowing power/flag symbols to be annotated.

    Returns:
        Dict mapping UUID -> {"old": str, "new": str, "unannotated": bool}.
    """
    mapping: dict[str, dict] = {}

    if unannotated_only:
        return _assign_numbers_unannotated_only(
            symbols, prefixes, start_from,
            include_power=include_power,
        )

    # Track next number per prefix
    counters: dict[str, int] = {}
    # Track base number assignments for multi-unit: (prefix, old_number) -> new_number
    multi_unit_assigned: dict[tuple[str, int | None], int] = {}

    for sym in symbols:
        ref = sym["reference"]
        prefix = sym["prefix"]
        number = sym["number"]
        unit_suffix = sym["unit_suffix"]
        sym_uuid = sym.get("uuid") or ref

        # Skip excluded prefixes (power symbols, flags, ground symbols)
        if prefix in EXCLUDED_PREFIXES or prefix.startswith("#"):
            if not (include_power and prefix in _POWER_PREFIXES):
                continue

        # Skip if prefix filter is active and this prefix isn't included
        if prefixes is not None and prefix not in prefixes:
            continue

        unannotated = number is None

        # Handle multi-unit components
        if unit_suffix:
            key = (prefix, number)
            if key in multi_unit_assigned:
                new_number = multi_unit_assigned[key]
            else:
                new_number = counters.get(prefix, start_from)
                counters[prefix] = new_number + 1
                multi_unit_assigned[key] = new_number
            new_ref = _format_reference(prefix, new_number, unit_suffix)
        else:
            new_number = counters.get(prefix, start_from)
            counters[prefix] = new_number + 1
            new_ref = _format_reference(prefix, new_number)

        mapping[sym_uuid] = {
            "old": ref,
            "new": new_ref,
            "unannotated": unannotated,
        }

    return mapping


def _assign_numbers_unannotated_only(
    symbols: list[dict],
    prefixes: list[str] | None,
    start_from: int,
    *,
    include_power: bool = False,
) -> dict[str, dict]:
    """Assign numbers only to unannotated symbols, preserving existing refs.

    Collects existing numbers per prefix into a reserved set, then assigns
    new sequential numbers to unannotated (``?``) symbols while skipping
    over reserved numbers.

    When *include_power* is ``True``, ``#PWR`` and ``#FLG`` prefixes are
    no longer excluded.

    Returns:
        Dict mapping UUID -> {"old": str, "new": str, "unannotated": bool}.
    """
    mapping: dict[str, dict] = {}

    def _is_excluded(prefix: str) -> bool:
        """Return True if *prefix* should be skipped."""
        if prefix in EXCLUDED_PREFIXES or prefix.startswith("#"):
            if include_power and prefix in _POWER_PREFIXES:
                return False
            return True
        return False

    # Phase 1: Collect existing (reserved) numbers per prefix
    existing: dict[str, set[int]] = {}
    # Also collect multi-unit base numbers that are already assigned
    multi_unit_assigned: dict[tuple[str, int | None], int] = {}

    for sym in symbols:
        prefix = sym["prefix"]
        number = sym["number"]
        unit_suffix = sym["unit_suffix"]

        if _is_excluded(prefix):
            continue
        if prefixes is not None and prefix not in prefixes:
            continue
        if number is not None:
            existing.setdefault(prefix, set()).add(number)

    # Phase 2: Assign numbers only to unannotated symbols
    counters: dict[str, int] = {}

    def _next_available(pfx: str) -> int:
        """Return the next available number for *pfx*, skipping reserved."""
        n = counters.get(pfx, start_from)
        reserved = existing.get(pfx, set())
        while n in reserved:
            n += 1
        counters[pfx] = n + 1
        return n

    for sym in symbols:
        ref = sym["reference"]
        prefix = sym["prefix"]
        number = sym["number"]
        unit_suffix = sym["unit_suffix"]
        sym_uuid = sym.get("uuid") or ref

        if _is_excluded(prefix):
            continue
        if prefixes is not None and prefix not in prefixes:
            continue

        # Skip already-assigned references
        if number is not None:
            continue

        # Handle multi-unit unannotated components
        if unit_suffix:
            key = (prefix, number)  # number is None for unannotated
            if key in multi_unit_assigned:
                new_number = multi_unit_assigned[key]
            else:
                new_number = _next_available(prefix)
                multi_unit_assigned[key] = new_number
            new_ref = _format_reference(prefix, new_number, unit_suffix)
        else:
            new_number = _next_available(prefix)
            new_ref = _format_reference(prefix, new_number)

        mapping[sym_uuid] = {
            "old": ref,
            "new": new_ref,
            "unannotated": True,
        }

    return mapping


def main(argv: list[str] | None = None):
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Re-annotate reference designators in KiCad schematics",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("schematic", type=Path, help="Path to .kicad_sch file")
    parser.add_argument(
        "--dry-run", "-n", action="store_true", help="Preview changes without modifying files"
    )
    parser.add_argument(
        "--backup", action="store_true", help="Create backup before modifying"
    )
    parser.add_argument(
        "--prefix",
        help="Comma-separated list of prefixes to renumber (e.g., R,C,U)",
    )
    parser.add_argument(
        "--start-from",
        type=int,
        default=1,
        help="Starting number for each prefix (default: 1)",
    )
    parser.add_argument(
        "--per-sheet",
        action="store_true",
        help="Restart numbering per sheet instead of continuous",
    )
    parser.add_argument(
        "--unannotated-only",
        action="store_true",
        help="Only assign numbers to unannotated (?) references, leaving existing ones unchanged",
    )
    parser.add_argument(
        "--include-power",
        action="store_true",
        help="Also annotate unannotated #PWR? and #FLG? power symbols",
    )
    parser.add_argument(
        "--format",
        choices=["text", "json"],
        default="text",
        help="Output format (default: text)",
    )

    args = parser.parse_args(argv)

    prefix_list = None
    if args.prefix:
        prefix_list = [p.strip() for p in args.prefix.split(",")]

    return run_re_annotate(
        schematic_path=args.schematic,
        dry_run=args.dry_run,
        backup=args.backup,
        prefixes=prefix_list,
        start_from=args.start_from,
        per_sheet=args.per_sheet,
        format=args.format,
        unannotated_only=args.unannotated_only,
        include_power=args.include_power,
    )


if __name__ == "__main__":
    sys.exit(main())
