# Loom Workflow Labels
# These labels coordinate the Loom AI agent workflow
# Sync with: ./scripts/install/sync-labels.sh . (from workspace root)
# Or manually: gh label create/edit commands

# Core Workflow States
- name: loom:triage
  description: New issue awaiting Curator enhancement
  color: "9CA3AF"  # gray-400 - neutral initial state

- name: loom:issue
  description: Approved for work by human (ready for Builder to claim)
  color: "3B82F6"  # blue-500

# DEPRECATED: loom:in-progress removed (use role-specific labels)
# - loom:building (Builder implementing issue)
# - loom:curating (Curator enhancing issue)
# - loom:reviewing (Judge reviewing PR)
# - loom:treating (Doctor fixing bug/PR feedback)

# Role-Specific Workflow Labels
- name: loom:building
  description: Builder is implementing this issue
  color: "F59E0B"  # amber-500 - matches other in-progress states

- name: loom:curating
  description: Curator is enhancing this issue
  color: "F59E0B"  # amber-500 - matches other in-progress states

- name: loom:treating
  description: Doctor is fixing this bug or addressing PR feedback
  color: "F59E0B"  # amber-500 - matches other in-progress states

- name: loom:reviewing
  description: Judge is actively reviewing this PR
  color: "F59E0B"  # amber-500 - matches other in-progress states

- name: loom:review-requested
  description: PR ready for Judge to review
  color: "10B981"  # emerald-500

- name: loom:changes-requested
  description: "PR requires changes before re-review (Judge requested modifications)"
  color: "F59E0B"  # amber-500 - matches other "action required" labels

- name: loom:pr
  description: PR approved by Judge, ready for human to merge
  color: "3B82F6"  # blue-500

# Agent Proposal Labels
- name: loom:architect
  description: Architect proposal awaiting user approval
  color: "9333EA"  # purple (violet-600)

- name: loom:hermit
  description: Hermit removal/simplification proposal awaiting user approval
  color: "9333EA"  # purple (violet-600)

- name: loom:curated
  description: Enhanced by Curator, awaiting human approval
  color: "10B981"  # emerald-500

# Status Labels
- name: loom:blocked
  description: Implementation blocked, needs help or clarification
  color: "EF4444"  # red-500

- name: loom:urgent
  description: Critical/blocking issue requiring immediate attention
  color: "DC2626"  # red-600

# Designer Validation Labels
# These labels are used by the /designer skill for automated design validation

# Severity Labels
- name: designer:error
  description: Design validation found blocking error
  color: "B60205"  # red - blocking failure

- name: designer:warning
  description: Design validation found non-blocking warning
  color: "FBCA04"  # yellow - non-blocking issue

- name: designer:friction
  description: Design validation found DX/UX friction
  color: "C5DEF5"  # light blue - improvement opportunity

# Board Labels
- name: board:00-simple-led
  description: Simple LED demo board
  color: "D4C5F9"  # lavender

- name: board:01-voltage-divider
  description: Voltage divider demo board
  color: "D4C5F9"  # lavender

- name: board:02-charlieplex
  description: Charlieplex LED matrix board
  color: "D4C5F9"  # lavender

- name: board:03-usb-joystick
  description: USB joystick demo board
  color: "D4C5F9"  # lavender

- name: board:04-stm32-devboard
  description: STM32 development board
  color: "D4C5F9"  # lavender

# Phase Labels
- name: phase:schematic
  description: Schematic generation phase
  color: "BFD4F2"  # light blue

- name: phase:pcb
  description: PCB creation phase
  color: "BFD4F2"  # light blue

- name: phase:routing
  description: Autorouting phase
  color: "BFD4F2"  # light blue

- name: phase:drc
  description: DRC validation phase
  color: "BFD4F2"  # light blue
