"""``net-status --why`` reads the routing-plan sidecar (Issue #5521).

Epic #5510 Phase 1c, item 3.  ``kct route`` has written a report-only
``<stem>.routing_plan.json`` since #5519/#5520, but nothing read it: the
board that said *where* it was over-subscribed could not tell the person
asking *why this net is stuck*.  This module pins both halves of that:

1. **Without a sidecar, nothing changes at all.**  Golden byte-equality
   against ``tests/fixtures/net_status_why_golden/`` -- text AND JSON --
   captured from the parent commit.  A new key, a reordered key, an extra
   blank line all fail here.  (The fixtures are regenerated by
   ``scripts/regen_net_status_why_golden.py``.)
2. **With a sidecar, the named overflowed corridor and its measured relief
   appear ahead of the classifier's guess**, and the JSON grows exactly two
   additive keys (``routing_plan`` top-level, ``overflow_edge`` per crossing
   diagnosis).

A stale or malformed sidecar is treated as no sidecar -- never as a hint.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from kicad_tools.cli.net_status_cmd import main
from tests.test_net_status_cmd import INCOMPLETE_PCB

GOLDEN_DIR = Path(__file__).parent / "fixtures" / "net_status_why_golden"

#: The ``incomplete_pcb`` fixture's one stuck signal net with two pads.
STUCK_NET = "SIG"
STUCK_NET_ID = 3


@pytest.fixture
def board(tmp_path: Path) -> Path:
    pcb = tmp_path / "incomplete.kicad_pcb"
    pcb.write_text(INCOMPLETE_PCB)
    return pcb


def _sidecar_payload(pcb: Path, *, net_name: str = STUCK_NET) -> dict:
    """A minimal but schema-valid plan with exactly one overflowed edge."""
    return {
        "schema_version": 1,
        "source": {"pcb": str(pcb), "kct_version": "test", "tile_mm": 4.0},
        "layers": {"signal": [0, 3], "plane": [1, 2]},
        "regions": {
            "17": {"row": 3, "col": 5, "min_x": 20.0, "min_y": 12.0, "max_x": 24.0, "max_y": 16.0},
            "18": {"row": 3, "col": 6, "min_x": 24.0, "min_y": 12.0, "max_x": 28.0, "max_y": 16.0},
        },
        "nets": {
            str(STUCK_NET_ID): {
                "name": net_name,
                "class": None,
                "pitch_mm": 0.4,
                "layer_set": [0],
                "region_path": [17, 18],
                "status": "assigned",
            }
        },
        "edges": [
            {
                "a": 17,
                "b": 18,
                "capacity": 9,
                "demand": 14.0,
                "overflow": 5,
                "blockage_mm": 0.0,
                "nets": [STUCK_NET_ID],
                "layers": {"0": {"capacity": 9, "demand": 14.0}},
                "refs_a": ["U1"],
                "refs_b": ["R1"],
            }
        ],
        "overflow_report": {
            "iterations": 15,
            "total_overflow": 5,
            "overflowed_edges": 1,
            "failed_nets": [],
            "feasible": False,
            "elapsed_s": 0.4,
        },
        "relief": [
            {
                "edge": [17, 18],
                "kind": "move_component",
                "ref": "R1",
                "dx": 2.0,
                "dy": 0.0,
                "expected_overflow": 0,
            },
            {"edge": [17, 18], "kind": "swap_pins", "deferred": "#5511"},
        ],
        "relief_meta": {
            "candidates_evaluated": 4,
            "elapsed_s": 0.9,
            "truncated": False,
            "baseline_overflow": 5,
            "budget_s": 5.0,
        },
    }


def _write_sidecar(pcb: Path, payload: dict | None = None) -> Path:
    sidecar = pcb.with_name(pcb.stem + ".routing_plan.json")
    sidecar.write_text(json.dumps(payload if payload is not None else _sidecar_payload(pcb)))
    return sidecar


class TestGoldenNoSidecar:
    """No sidecar => byte-identical to the pre-#5521 output."""

    def test_text_output_is_byte_identical(self, board: Path, capsys):
        main([str(board), "--why"])
        got = capsys.readouterr().out.replace(str(board), "INCOMPLETE_PCB")
        assert got == (GOLDEN_DIR / "incomplete.txt").read_text()

    def test_json_output_is_byte_identical(self, board: Path, capsys):
        main([str(board), "--why", "--format", "json"])
        got = capsys.readouterr().out.replace(str(board), "INCOMPLETE_PCB")
        assert got == (GOLDEN_DIR / "incomplete.json").read_text()

    def test_json_has_no_routing_plan_keys(self, board: Path, capsys):
        main([str(board), "--why", "--format", "json"])
        data = json.loads(capsys.readouterr().out)
        assert "routing_plan" not in data
        assert all("overflow_edge" not in n for n in data["nets"])


class TestWithSidecar:
    def test_text_names_the_overflowed_corridor(self, board: Path, capsys):
        _write_sidecar(board)
        main([str(board), "--why"])
        out = capsys.readouterr().out
        assert "routing plan:" in out
        # The corridor is named with the SAME wording the route-time report
        # uses (RoutingPlan.format_edge_headline).
        assert "corridor U1 -> R1 (tiles 17-18, layer 0)" in out
        assert "demand 14.0 tracks, capacity 9, overflow 5" in out

    def test_text_carries_the_measured_relief(self, board: Path, capsys):
        _write_sidecar(board)
        main([str(board), "--why"])
        out = capsys.readouterr().out
        assert "relief: move R1 +2.0/+0.0 mm -> total overflow 0" in out
        assert "relief: swap_pins deferred (#5511)" in out

    def test_plan_block_precedes_the_recommendation(self, board: Path, capsys):
        _write_sidecar(board)
        main([str(board), "--why"])
        out = capsys.readouterr().out
        block = out.index("routing plan:")
        # The classifier's own verdict lines must still be above it: the plan
        # is a second witness, never a reclassification.
        assert out.index(f"] {STUCK_NET}") < block
        assert out.index("evidence:") < block

    def test_classification_header_is_unchanged(self, board: Path, capsys):
        """The plan does not reclassify anything."""
        main([str(board), "--why"])
        before = capsys.readouterr().out
        _write_sidecar(board)
        main([str(board), "--why"])
        after = capsys.readouterr().out
        header = before.split("[", 1)[0]
        assert after.startswith(header)

    def test_uncrossed_nets_get_no_block(self, board: Path, capsys):
        """A net that crosses no overflowed edge is untouched."""
        payload = _sidecar_payload(board, net_name="SOMETHING_ELSE")
        _write_sidecar(board, payload)
        main([str(board), "--why"])
        assert "routing plan:" not in capsys.readouterr().out

    def test_json_adds_overflow_edge_and_routing_plan(self, board: Path, capsys):
        sidecar = _write_sidecar(board)
        main([str(board), "--why", "--format", "json"])
        data = json.loads(capsys.readouterr().out)
        assert data["routing_plan"]["path"] == str(sidecar)
        assert data["routing_plan"]["schema_version"] == 1
        assert data["routing_plan"]["feasible"] is False
        assert data["routing_plan"]["total_overflow"] == 5

        crossing = [n for n in data["nets"] if n["net_name"] == STUCK_NET]
        assert crossing, "the stuck net vanished from the JSON"
        edge = crossing[0]["overflow_edge"]
        assert (edge["a"], edge["b"]) == (17, 18)
        assert edge["overflow"] == 5
        assert edge["refs_a"] == ["U1"] and edge["refs_b"] == ["R1"]

    def test_json_diagnosis_keys_are_otherwise_unchanged(self, board: Path, capsys):
        """``overflow_edge`` is injected in output_why, not in to_dict()."""
        main([str(board), "--why", "--format", "json"])
        bare = {n["net_name"]: set(n) for n in json.loads(capsys.readouterr().out)["nets"]}
        _write_sidecar(board)
        main([str(board), "--why", "--format", "json"])
        withplan = {n["net_name"]: set(n) for n in json.loads(capsys.readouterr().out)["nets"]}
        for name, keys in withplan.items():
            extra = keys - bare[name]
            assert extra in ({"overflow_edge"}, set()), f"{name} grew {extra}"

    def test_stuck_classifier_to_dict_is_not_touched(self, board: Path):
        """The shared serializer must not learn about overflow edges (#5521)."""
        from kicad_tools.router.stuck_classifier import classify_stuck_nets

        _write_sidecar(board)
        result = classify_stuck_nets(board, strict=True)
        assert all("overflow_edge" not in d.to_dict() for d in result.diagnoses)


class TestUntrustworthySidecars:
    def test_sidecar_for_a_different_board_is_ignored(self, board: Path, capsys):
        payload = _sidecar_payload(board)
        payload["source"]["pcb"] = "/elsewhere/other_board.kicad_pcb"
        _write_sidecar(board, payload)
        main([str(board), "--why"])
        captured = capsys.readouterr()
        assert "routing plan:" not in captured.out
        assert "other_board.kicad_pcb" in captured.err

    def test_sidecar_older_than_the_pcb_is_ignored(self, board: Path, capsys):
        import os

        sidecar = _write_sidecar(board)
        os.utime(sidecar, (1000, 1000))
        main([str(board), "--why"])
        captured = capsys.readouterr()
        assert "routing plan:" not in captured.out
        assert "older than" in captured.err

    def test_malformed_sidecar_is_ignored_silently(self, board: Path, capsys):
        board.with_name(board.stem + ".routing_plan.json").write_text("{not json")
        main([str(board), "--why"])
        captured = capsys.readouterr()
        assert "routing plan:" not in captured.out
        assert captured.err == ""


class TestCrossingPredicate:
    """One definition of "crossing", shared with the fleet table."""

    def test_only_overflowed_edges_count(self, board: Path):
        from kicad_tools.router.routing_plan import RoutingPlan

        payload = _sidecar_payload(board)
        payload["edges"][0]["overflow"] = 0
        plan = RoutingPlan.from_dict(payload)
        assert plan.crossings_by_net_name() == {}

    def test_worst_edge_first(self, board: Path):
        from kicad_tools.router.routing_plan import RoutingPlan

        payload = _sidecar_payload(board)
        second = dict(payload["edges"][0])
        second["a"], second["b"], second["overflow"] = 18, 19, 11
        payload["edges"].append(second)
        plan = RoutingPlan.from_dict(payload)
        edges = plan.crossings_by_net_name()[STUCK_NET]
        assert [e.overflow for e in edges] == [11, 5]
