"""Regression tests for ``boards/05-bldc-motor-controller/`` routing throughput.

Issue #2681 — Routing-throughput regression caused by Phase 1C clearance
threading (#2586 / commit ``1482a75d``).  Per-net A* on the dense diff-pair
nets (ISENSE_*) lost ~13 % per net once the partner-aware kwargs were
threaded into ``_is_trace_blocked`` and ``compute_expanded_blocked``, even
though the partner branch was dormant at that commit.  The cumulative
effect was that the 240s wall-clock budget no longer reached the late nets,
collapsing board 05's 2L completion from 9/35 (26 %) at ``a9790ad0`` to
0/35 (0 %) at HEAD.

PR #2698 (placement re-tune) restored 2L completion to ~34 % by relieving
the U3/U10 fan-out density that was driving the per-net A* cost up.  This
test pins the post-PR-2698 completion floor so a future router or placement
change that re-introduces the regression is caught loudly.

The test is marked ``@pytest.mark.slow`` (4-minute wall clock) so PR-time
CI excludes it; the nightly slow-tests workflow at
``.github/workflows/slow-tests.yml`` (``-m slow``) picks it up.

NON-PRODUCTION RECIPE (read before editing the flags below).  This test
deliberately runs ``--backend python --no-auto-layers --layers 2`` -- it
is a *throughput* regression guard (net-completion %, the #2681 per-net
A* slowdown dimension), pinned on the python backend so it reproduces on
CI runners where the C++ extension is not built.  It is NOT board 05's
production recipe: ``boards/05-bldc-motor-controller/design.py`` routes
with ``--backend cpp --auto-layers --starting-layers 4 --max-layers 4
--manufacturer jlcpcb-tier1`` (Issue #3425).

The hard cross-net trace-overlap crossings on this python/2L path
(Issue #3444: ``clearance_segment_segment`` actual -0.200mm etc.) were
NOT fixed in the python backend -- the production recipe moved off this
path entirely.  Do not treat this throughput floor as a manufacturability
or DRC-cleanliness gate for board 05; that is
``tests/test_board_05_drc_hotspot_regression.py`` against the committed
cpp/tier1/4L snapshot.

The recipe also passes ``--allow-unsafe-grid`` (Issue #4024).  Board 05's
geometry (210 pads, 0.15mm clearance, 80x100mm) makes ``--grid auto``
select a grid coarser than clearance/2 once the memory budget cap
(max_cells=2,000,000) is hit, which trips the #3911 auto-grid safety gate
(``route_cmd.py`` ~8594) BEFORE any backend selection happens -- so the
gate does ``return 1`` identically under both ``--backend python`` and
``--backend cpp``.  A fatal exit 1 raised inside the class-scoped fixture
turns into pytest ERROR (not FAIL) for every dependent test.  Because this
throughput guard discards its routed output (written to a
``TemporaryDirectory`` and never manufactured or DRC-checked), the
DRC-safety gate is irrelevant here; ``--allow-unsafe-grid`` makes the gate
a no-op for this fixture without touching production behavior anywhere
else.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
BOARD_DIR = REPO_ROOT / "boards" / "05-bldc-motor-controller"
UNROUTED_PCB = BOARD_DIR / "output" / "bldc_controller.kicad_pcb"


# Minimum 2-layer completion rate the negotiated A* router should achieve
# on board 05 with default flags and ``--seed 42``.  Calibrated from
# Issue #2681 acceptance criterion: "restore 2L completion to >=26% on
# board 05 with default flags".  Post-#2698 placement the typical value
# was ~34 %; the 26 % floor left ~8 percentage points of slack for
# legitimate routing-quality variations across runs and platforms.
#
# Re-pinned 26 -> 35 by Issue #3423 (2026-06-09): the U3 (DRV8301)
# 90-degree-CW rotation + C/B/A MOSFET phase-column swap structurally
# removed the PWM/GATE crossing topology, raising the measured 2L
# completion at this test's exact recipe (python backend, 240s budget,
# seed 42, no skip-nets) to 16/35 = 45.7 % with the post-#3442 router
# -- measured on a heavily loaded machine, so idle CI should do at
# least as well.  The 35 % floor keeps ~10 points of slack, mirroring
# the old 34-measured / 26-floor margin.  With the design recipe's
# full 900s budget and skip-nets the same board reaches 17/32 = 53 %.
MIN_2L_COMPLETION_PCT = 35


@pytest.fixture(scope="module")
def unrouted_pcb_path() -> Path:
    """Verify the committed unrouted board 05 PCB exists.

    The PCB is committed under ``boards/05-bldc-motor-controller/output/``
    (regenerated by PR #2698 to address the U3/U10 fan-out density).  If
    the file is missing the test cannot run -- skip with a clear message
    rather than fail spuriously.
    """
    if not UNROUTED_PCB.exists():
        pytest.skip(
            f"Board 05 unrouted PCB not found at {UNROUTED_PCB!s}; "
            "regenerate via `uv run kct build boards/05-bldc-motor-controller --step pcb`"
        )
    return UNROUTED_PCB


def _parse_routed_net_count(stdout: str) -> tuple[int, int] | None:
    """Extract the final ``Nets routed: N/M`` count from kct route output.

    The expected summary block contains a line of the form::

        Nets routed:     12/35

    (Multiple matches may exist in escalation mode; we return the LAST
    one since that reflects the final state the router landed on.)

    Returns ``(routed, total)`` or ``None`` if no such line was found
    (e.g., the router crashed before producing a summary).
    """
    pattern = re.compile(r"Nets routed:\s+(\d+)/(\d+)")
    matches = pattern.findall(stdout)
    if not matches:
        return None
    routed, total = matches[-1]
    return int(routed), int(total)


def _parse_iter0_route_count(stdout: str) -> int | None:
    """Extract the iteration-0 routed-net count from kct route output.

    The legacy negotiated loop (``core.py::route_all_negotiated``) emits a
    line of the form::

        Routed 23/35 nets, overflow: 14 (178.4s)

    immediately after the initial-routing-with-sharing pass.  The two-phase
    path (``two_phase.py`` / ``hierarchical.py``, default since #3452/#3499)
    emits the equivalent tally as::

        Initial pass: 23/39 nets, overflow: 14

    Both report the same measure: the net count after the iteration-0
    initial pass, before any rip-up-and-reroute iteration.  Note the
    two-phase line is printed AFTER the bounded grace pass (#3452)
    commits its routes, so it includes grace-routed starved nets; the
    grace pass is part of the initial pass by design (one bounded
    attempt per starved net within a fixed grace budget), so this line
    remains the honest iteration-0 tally.

    We capture the FIRST such line (iteration 0) because subsequent
    iterations may rip up and re-route a different subset.

    Returns the integer count or ``None`` if no such line was found.
    """
    pattern = re.compile(r"(?:Routed|Initial pass:)\s+(\d+)/\d+\s+nets,\s+overflow:\s+\d+")
    match = pattern.search(stdout)
    if match is None:
        return None
    return int(match.group(1))


@pytest.mark.slow
class TestBoard05RoutingThroughput:
    """Pin 2-layer routing throughput on board 05 against the #2681 floor.

    These tests run the full ``kct route`` CLI as a subprocess to exercise
    the same code path the user invokes interactively.  Each test runs
    once per session (cached via ``module``-scoped fixture below) and asserts
    a different aspect of the result to keep failure attribution sharp.
    """

    @pytest.fixture(scope="class")
    def route_stdout(self, unrouted_pcb_path: Path) -> str:
        """Run ``kct route --seed 42 --differential-pairs --layers 2 ...``.

        Captures stdout for the per-test assertions below.  The run uses
        the pure-Python backend so the regression test is reproducible on
        CI runners where the C++ extension is not built.  ``--no-auto-layers
        --layers 2`` keeps the test wall-clock around 4 minutes (one 240s
        budget) instead of the 4x cost a full ``--auto-layers`` escalation
        would incur.
        """
        with tempfile.TemporaryDirectory() as td:
            pcb_copy = Path(td) / "bldc_controller.kicad_pcb"
            shutil.copy2(unrouted_pcb_path, pcb_copy)
            # 240s budget matches issue #2681's reproduction recipe.
            # ``--seed 42`` makes the per-net order deterministic so the
            # completion percentage is reproducible run-to-run.
            # ``--no-auto-layers --layers 2`` prevents the layer-escalation
            # loop from re-running on 4L/6L stacks (which would multiply
            # the wall-clock cost by 4x); this test only pins 2L throughput,
            # the regression dimension #2681 identified.
            # ``--no-cache`` (issue #3502): a warm routing cache makes
            # ``kct route`` skip the routing phase entirely ("Cache HIT ...
            # Using cached routing result"), so no iteration-0 line is
            # emitted at all and the completion metric reflects a stale
            # cached route rather than current router throughput.  Both
            # tests in this class pin THROUGHPUT, so the route must
            # actually run.
            # ``--allow-unsafe-grid`` (issue #4024): board 05's dense
            # geometry (210 pads, 0.15mm clearance) forces ``--grid auto``
            # coarser than clearance/2 under the memory budget cap, tripping
            # the #3911 auto-grid safety gate (route_cmd.py ~8594), which
            # does ``return 1`` BEFORE backend selection -- identically for
            # python and cpp.  That fatal exit inside this class-scoped
            # fixture surfaces as pytest ERROR (not FAIL) on every dependent
            # test.  This is a throughput-only guard: the routed PCB is
            # written to the TemporaryDirectory above and discarded (never
            # manufactured, never DRC-checked), so the DRC-safety intent of
            # the gate does not apply.  The flag makes the gate a no-op here
            # WITHOUT altering production gate behavior (see #3911); it does
            # not change the throughput numbers the assertions below parse.
            cmd = [
                sys.executable,
                "-m",
                "kicad_tools.cli",
                "route",
                str(pcb_copy),
                "--seed",
                "42",
                "--differential-pairs",
                "--no-auto-layers",
                "--layers",
                "2",
                "--manufacturer",
                "jlcpcb",
                "--timeout",
                "240",
                "--backend",
                "python",
                "--no-cache",
                "--allow-unsafe-grid",
            ]
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=360,  # 240s route + slack for setup/teardown
                check=False,
            )
            # ``kct route`` returns:
            #   0 = full route + DRC clean
            #   2 = partial routing below --min-completion
            #   3 = >= min-completion but DRC violations remain
            #   4 = partial routing AND segment-segment clearance violations
            # Board 05 is currently in the 2-4 regime; we only flag
            # exit codes 1 (fatal: no nets routed) or 5 (interrupted)
            # as test failures.  The stdout summary is what we parse.
            if proc.returncode in (1, 5):
                pytest.fail(
                    f"kct route returned fatal exit code {proc.returncode}\n"
                    f"stderr (last 2000 chars):\n{proc.stderr[-2000:]}\n"
                    f"stdout (last 2000 chars):\n{proc.stdout[-2000:]}"
                )
            return proc.stdout

    def test_2l_completion_meets_floor(self, route_stdout: str) -> None:
        """2L net-completion stays at or above the #2681 26 % floor.

        Issue #2681 found that commit ``1482a75d`` (Phase 1C clearance
        threading) introduced a ~13 % per-net A* slowdown that, combined
        with the 26 -> 35 net growth from the block-refactor wave, dropped
        board 05's 2L completion from 9/35 (26 %) to 0/35 (0 %).  PR #2698
        restored ~34 % via placement re-tune; this test pins the post-fix
        floor at 26 % so any future router OR placement change that
        regresses the throughput is caught loudly.

        The "completion" metric here is the connectivity-verified count
        from the final summary block (``Nets routed: N/M``), which
        counts nets where ALL pads are in the same connected component
        (the ``validate_net_connectivity`` semantic from
        ``two_phase.py``).
        """
        parsed = _parse_routed_net_count(route_stdout)
        assert parsed is not None, (
            "Could not find 'Nets routed: N/M' line in kct route output. "
            f"Last 2000 chars of stdout:\n{route_stdout[-2000:]}"
        )
        routed, total = parsed
        actual_pct = (100 * routed) // total if total else 0
        assert actual_pct >= MIN_2L_COMPLETION_PCT, (
            f"Board 05 2L completion regressed: routed {routed}/{total} "
            f"({actual_pct}%), expected >= {MIN_2L_COMPLETION_PCT}% "
            f"(issue #2681 floor).  This typically indicates either a "
            f"router slowdown (re-bisect to find the regressing commit) "
            f"or a placement change that reduced fan-out throughput "
            f"(see PR #2698)."
        )

    def test_initial_pass_routes_enough_nets(self, route_stdout: str) -> None:
        """Iteration-0 net count is at least 15/35.

        The initial negotiated pass (iteration 0) routes nets in the
        order produced by the net-ordering heuristic, before any rip-up
        and reroute.  A drop in this count directly indicates per-net
        A* slowdown -- the wall-clock budget is being exhausted on
        earlier nets.  At ``a9790ad0`` (pre-#2586) the iteration-0 pass
        routed 19/35 nets; at ``1482a75d`` it dropped to 10/35.

        Post-PR-2698 (placement re-tune) the typical iteration-0 count
        is 23/35.  We pin the floor at 15/35 to leave ~8 nets of slack
        for legitimate per-platform variation while still catching the
        characteristic #2681 collapse (which dropped iter-0 by ~50 %).

        This check is supplementary to ``test_2l_completion_meets_floor``:
        it points at the per-net A* cost dimension specifically, so a
        future regression in ``_is_trace_blocked`` / ``compute_expanded_
        blocked`` per-call overhead is caught even if the connectivity
        metric happens to stay above the floor.
        """
        actual_count = _parse_iter0_route_count(route_stdout)
        assert actual_count is not None, (
            "Could not find the iteration-0 line ('Routed N/M nets, "
            "overflow: K' or 'Initial pass: N/M nets, overflow: K') in kct "
            f"route output.  Last 2000 chars of stdout:\n{route_stdout[-2000:]}"
        )
        assert actual_count >= 15, (
            f"Board 05 iteration-0 routed only {actual_count} nets "
            "in the 240s budget; expected >= 15 (issue #2681 floor).  "
            "Lower counts indicate per-net A* slowdown -- check recent "
            "router changes for added per-call overhead in "
            "_is_trace_blocked or compute_expanded_blocked."
        )
