"""Golden-fixture tests pinning the mirror strategy to KiCad's own flip (#4560).

``tests/fixtures/mirror_flip/`` holds a committed pair generated by KiCad
10.0.5 itself (see ``generate_golden.py`` there):

* ``mirror_front.kicad_pcb``  -- one asymmetric footprint ``U1`` on ``F.Cu``
  at rotation 30 (mixed SMD/through-hole pads, non-axis pad angles);
* ``mirror_back_lr.kicad_pcb`` -- the SAME board after KiCad's
  ``FOOTPRINT.Flip(anchor, FLIP_DIRECTION_LEFT_RIGHT)``.

These tests assert that ``StrategyApplicator``'s ``MIRROR_COMPONENT`` turns
the front board into the back board -- absolute pad geometry (positions,
layer lists, angles), footprint layer/position/rotation -- and that the
mutation *serializes* (flip -> save -> reparse shows the flip; the
``Pad.__setattr__`` write-through hazard from the issue).  KiCad is NOT
required at test time; the ``kicad-cli pcb drc`` cross-gate below skips when
the binary is absent (as on the plain CI test runner).

The empirically-pinned file-level transform (30 deg was chosen because it is
NOT a fixed point of the candidate transforms, which 90/270 are):

* footprint layer ``F.* <-> B.*``; rotation ``theta -> 180 - theta``;
* pad local position ``(x, y) -> (x, -y)`` (constant in theta);
* pad ABSOLUTE angle ``a -> 180 - a`` (the left/right reflection of an
  orientation -- NOT ``-a``, which is the top/bottom flip);
* pad layers side-swapped per name (through-hole ``*.Cu``/``*.Mask``
  unchanged).
"""

from __future__ import annotations

import json
import math
import shutil
import subprocess
from pathlib import Path

import pytest

from kicad_tools.recovery import (
    Action,
    Difficulty,
    ResolutionStrategy,
    StrategyApplicator,
    StrategyType,
)
from kicad_tools.schema.pcb import PCB

_FIXTURES = Path(__file__).resolve().parent / "fixtures" / "mirror_flip"
_FRONT = _FIXTURES / "mirror_front.kicad_pcb"
_BACK = _FIXTURES / "mirror_back_lr.kicad_pcb"

# KiCad stores coordinates in integer nanometres; its own flip leaves ~1e-6 mm
# artifacts, and our serializer's float formatting is 6 significant digits.
_TOL = 1e-4


def _u1(pcb: PCB):
    return next(fp for fp in pcb.footprints if fp.reference == "U1")


def _mirror_strategy(ref: str = "U1") -> ResolutionStrategy:
    return ResolutionStrategy(
        type=StrategyType.MIRROR_COMPONENT,
        difficulty=Difficulty.MEDIUM,
        confidence=1.0,
        actions=[Action(type="mirror", target=ref, params={})],
    )


def _abs_pad_positions(fp) -> dict[str, tuple[float, float]]:
    """Board-frame pad centres, using the router's local->board convention
    (``router/io.py``: KiCad footprint orientation applies as a negated angle
    vs standard CCW math)."""
    rot = math.radians(-fp.rotation)
    c, s = math.cos(rot), math.sin(rot)
    out: dict[str, tuple[float, float]] = {}
    for pad in fp.pads:
        x, y = pad.position
        out[pad.number] = (
            fp.position[0] + x * c - y * s,
            fp.position[1] + x * s + y * c,
        )
    return out


def _flip_front() -> PCB:
    pcb = PCB.load(str(_FRONT))
    result = StrategyApplicator().apply_strategy(pcb, _mirror_strategy())
    assert result.success is True
    assert result.components_moved == ["U1"]
    return pcb


class TestMirrorMatchesKiCadFlip:
    def test_footprint_layer_position_rotation(self):
        flipped = _u1(_flip_front())
        golden = _u1(PCB.load(str(_BACK)))
        assert flipped.layer == golden.layer == "B.Cu"
        # Flip about the footprint's own anchor keeps the centre fixed.
        assert flipped.position == pytest.approx(golden.position, abs=_TOL)
        assert (flipped.rotation - golden.rotation) % 360.0 == pytest.approx(0.0, abs=_TOL)

    def test_pad_absolute_geometry_equals_golden(self):
        flipped = _u1(_flip_front())
        golden = _u1(PCB.load(str(_BACK)))
        assert [p.number for p in flipped.pads] == [p.number for p in golden.pads]

        flipped_abs = _abs_pad_positions(flipped)
        golden_abs = _abs_pad_positions(golden)
        for mine, theirs in zip(flipped.pads, golden.pads, strict=True):
            # Absolute board-frame centre.
            assert flipped_abs[mine.number] == pytest.approx(golden_abs[theirs.number], abs=_TOL), (
                f"pad {mine.number} absolute position"
            )
            # Local file coordinates too (the transform is (x, -y)).
            assert mine.position == pytest.approx(theirs.position, abs=_TOL)
            # Absolute angle, mod 360 (KiCad normalizes to (-180, 180]).
            assert (mine.rotation - theirs.rotation) % 360.0 == pytest.approx(0.0, abs=_TOL), (
                f"pad {mine.number} angle"
            )
            # Layer lists swap side per name; through-hole stays *.Cu/*.Mask.
            assert mine.layers == theirs.layers, f"pad {mine.number} layers"

    def test_through_hole_pad_layers_unchanged(self):
        front = PCB.load(str(_FRONT))
        pth_before = next(p for p in _u1(front).pads if p.number == "4")
        assert pth_before.layers == ["*.Cu", "*.Mask"]
        flipped = _u1(_flip_front())
        pth = next(p for p in flipped.pads if p.number == "4")
        assert pth.layers == ["*.Cu", "*.Mask"]

    def test_cosmetics_moved_to_back_side(self):
        flipped = _u1(_flip_front())
        golden = _u1(PCB.load(str(_BACK)))
        assert {t.layer for t in flipped.texts} == {t.layer for t in golden.texts}
        assert all(t.layer.startswith("B.") for t in flipped.texts)
        silk_mine = [g for g in flipped.graphics if g.layer == "B.SilkS"]
        silk_gold = [g for g in golden.graphics if g.layer == "B.SilkS"]
        assert len(silk_mine) == len(silk_gold) == 1
        assert silk_mine[0].start == pytest.approx(silk_gold[0].start, abs=_TOL)
        assert silk_mine[0].end == pytest.approx(silk_gold[0].end, abs=_TOL)

    def test_double_flip_is_identity(self):
        pcb = PCB.load(str(_FRONT))
        original = _u1(PCB.load(str(_FRONT)))
        applicator = StrategyApplicator()
        applicator.apply_strategy(pcb, _mirror_strategy())
        applicator.apply_strategy(pcb, _mirror_strategy())
        fp = _u1(pcb)
        assert fp.layer == original.layer
        assert (fp.rotation - original.rotation) % 360.0 == pytest.approx(0.0, abs=_TOL)
        for mine, theirs in zip(fp.pads, original.pads, strict=True):
            assert mine.position == pytest.approx(theirs.position, abs=_TOL)
            assert (mine.rotation - theirs.rotation) % 360.0 == pytest.approx(0.0, abs=_TOL)
            assert mine.layers == theirs.layers


class TestMirrorSerializes:
    """The flip must reach the S-expression tree ``PCB.save`` writes -- the
    ``Pad.__setattr__`` rotation-only write-through hazard from #4560."""

    def test_flip_save_reparse_shows_the_flip(self, tmp_path: Path):
        pcb = _flip_front()
        out = tmp_path / "flipped.kicad_pcb"
        pcb.save(str(out))

        reloaded = _u1(PCB.load(str(out)))
        golden = _u1(PCB.load(str(_BACK)))
        assert reloaded.layer == "B.Cu"
        assert (reloaded.rotation - golden.rotation) % 360.0 == pytest.approx(0.0, abs=_TOL)
        for mine, theirs in zip(reloaded.pads, golden.pads, strict=True):
            assert mine.position == pytest.approx(theirs.position, abs=_TOL)
            assert (mine.rotation - theirs.rotation) % 360.0 == pytest.approx(0.0, abs=_TOL)
            assert mine.layers == theirs.layers
        # Cosmetic children followed to the back side in the file too, with
        # the y-negation applied -- layer names alone would not catch a
        # side-swap that forgot the geometry (the board's layer-definition
        # table legitimately still names F.SilkS, so assert on ``(layer ...)``
        # references only).
        text = out.read_text()
        assert '(layer "F.SilkS")' not in text
        assert '(layer "B.SilkS")' in text
        silk_reloaded = [g for g in reloaded.graphics if g.layer == "B.SilkS"]
        silk_golden = [g for g in golden.graphics if g.layer == "B.SilkS"]
        assert len(silk_reloaded) == len(silk_golden) == 1
        assert silk_reloaded[0].start == pytest.approx(silk_golden[0].start, abs=_TOL)
        assert silk_reloaded[0].end == pytest.approx(silk_golden[0].end, abs=_TOL)
        # The transform is a y-negation of the ORIGINAL local coordinates.
        front_silk = next(g for g in _u1(PCB.load(str(_FRONT))).graphics if g.layer == "F.SilkS")
        assert silk_reloaded[0].start == pytest.approx(
            (front_silk.start[0], -front_silk.start[1]), abs=_TOL
        )

    @pytest.mark.skipif(shutil.which("kicad-cli") is None, reason="kicad-cli not installed")
    def test_kicad_cli_drc_cross_gate(self, tmp_path: Path):
        """Repo process rule: ``kct check`` alone is insufficient -- the saved
        flipped board must load and DRC clean in KiCad's own tooling."""
        pcb = _flip_front()
        out = tmp_path / "flipped.kicad_pcb"
        pcb.save(str(out))
        report = tmp_path / "drc.json"
        proc = subprocess.run(
            [
                "kicad-cli",
                "pcb",
                "drc",
                "--severity-error",
                "--exit-code-violations",
                "--format",
                "json",
                "-o",
                str(report),
                str(out),
            ],
            capture_output=True,
            text=True,
            timeout=120,
        )
        assert proc.returncode == 0, f"kicad-cli drc failed:\n{proc.stdout}\n{proc.stderr}"
        payload = json.loads(report.read_text())
        assert payload.get("violations", []) == []
