M48
; DRILL file {KiCad 9.0.7} date 2026-01-08T12:12:59-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-08T12:12:59-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X115.0Y-107.4
X115.0Y-118.0
T2
X105.0Y-111.23
X105.0Y-113.77
X125.0Y-111.23
X125.0Y-113.77
M30
