#!/usr/bin/env python3
"""Probe the ``bshada/open-schematics`` corpus through this repo's KiCad parsers.

Issue #4830 (deliverable 1) — a **local, opt-in** dev tool that answers one
question: *how does ``kicad_tools``' own s-expression parser hold up against
real-world KiCad files it did not author?*

Everything this repo measures today runs against the 9 in-repo boards, all of
them generated by ``kct``. The Hugging Face dataset
`bshada/open-schematics <https://huggingface.co/datasets/bshada/open-schematics>`_
(CC-BY-4.0, 87,931 records / ~317 GB) is a free real-world regression corpus:
each record carries a raw schematic source plus the paired PCB source(s) from a
human-completed design. This script samples N random records, runs each payload
through :meth:`kicad_tools.schema.Schematic.load` / :meth:`kicad_tools.schema.PCB.load`,
and emits a **failure taxonomy** — a JSON report for machine consumption and a
human-readable summary — so parser-hardening work can be prioritised by what
actually breaks, and how often.

Design constraints (from the issue; please preserve them):

* **Zero new default dependencies.** stdlib + ``requests`` only (``requests`` is
  already available via the ``dev`` and ``parts`` extras). The Hugging Face
  ``datasets`` library is deliberately *not* used and must not be added.
* **Opt-in / local only.** This script is never wired into a CI workflow and is
  never imported from anything under ``tests/`` — it does network I/O.
* **No corpus in the repo.** Sampled payloads are written to a scratch directory
  under the system temp dir (removed on exit); reports and any retained sources
  go to ``scripts/corpus/.cache/`` by default, which is gitignored. A run leaves
  ``git status`` clean.

Why the datasets-server ``/rows`` endpoint (and not ``/tree/main``)?
    The dataset is published as ~1,700 parquet shards under ``data/``, not as
    individual ``.kicad_sch`` / ``.kicad_pcb`` blobs, so listing the repo tree
    gives you no per-record granularity and the smallest shard is still hundreds
    of MB. The Hugging Face **datasets-server** HTTP API exposes the same
    dataset row-by-row (``/info`` for the row count, ``/rows`` for a window at a
    given offset) and returns the raw file contents as JSON strings. That is a
    plain HTTP API — no ``datasets`` dependency — and it lets us fetch exactly
    the N records we sampled instead of a shard's worth of neighbours.

Usage::

    # 50 random records (the default), reports under scripts/corpus/.cache/
    uv run python scripts/corpus/probe_open_schematics.py

    # small, reproducible sample — same --seed re-samples the same records
    uv run python scripts/corpus/probe_open_schematics.py --n 10 --seed 1234

    # no network: exercise the parse/report path against in-repo KiCad files
    uv run python scripts/corpus/probe_open_schematics.py --dry-run --n 20 --seed 7

Exit status is 0 whenever the probe ran (individual record failures are *data*,
not errors) and 1 only when nothing could be sampled at all.
"""

from __future__ import annotations

import argparse
import json
import random
import re
import shutil
import sys
import tempfile
import time
from collections import Counter
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from kicad_tools.exceptions import FileFormatError, KiCadToolsError
from kicad_tools.schema import PCB, Schematic
from kicad_tools.sexp import ParseError as SexpParseError

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT_DIR = REPO_ROOT / "scripts" / "corpus" / ".cache"

DEFAULT_DATASET = "bshada/open-schematics"
DATASETS_SERVER = "https://datasets-server.huggingface.co"
HUB_API = "https://huggingface.co/api/datasets"
USER_AGENT = "kicad-tools-corpus-probe/1 (+https://github.com/rjwalters/kicad-tools)"

# ---------------------------------------------------------------------------
# Failure taxonomy
#
# Buckets are chosen so that each one maps to a *different engineering action*.
# Resist the temptation to add a bucket that cannot be acted on differently
# from an existing one -- a taxonomy whose classes all mean "fix the parser"
# is just a catch-all with extra steps.
# ---------------------------------------------------------------------------
OK = "ok"

# Parser defects / gaps -- these are the actionable ones.
FAIL_SEXPR_SYNTAX = "sexpr-syntax-error"  # tokenizer/grammar rejected the file
FAIL_WRONG_ROOT = "wrong-root-token"  # parsed, but root tag is not what we expect
FAIL_ENCODING = "encoding-error"  # not decodable as UTF-8
FAIL_MISSING_NODE = "missing-node-or-atom"  # KeyError/IndexError walking the tree
FAIL_BAD_VALUE = "unexpected-value"  # ValueError/TypeError converting an atom
FAIL_TREE_SHAPE = "unexpected-tree-shape"  # AttributeError on an unexpected node
FAIL_RECURSION = "recursion-limit"  # nesting deeper than CPython's stack
FAIL_MEMORY = "out-of-memory"
FAIL_KCT = "kicad-tools-error"  # any other KiCadToolsError subclass
FAIL_OTHER = "uncaught-internal-error"  # everything else: triage individually

# Not parser defects -- excluded from the failure rate, counted separately.
SKIP_NON_KICAD = "skipped-non-kicad-format"  # legacy .sch / Altium / unknown blob
SKIP_EMPTY = "skipped-empty-payload"
SKIP_OVERSIZE = "skipped-oversize-payload"
SKIP_TRUNCATED = "skipped-dataset-truncated-cell"  # dataset API truncated the row
NET_ERROR = "network-error"  # record could not be fetched at all

FAILURE_CLASSES = frozenset(
    {
        FAIL_SEXPR_SYNTAX,
        FAIL_WRONG_ROOT,
        FAIL_ENCODING,
        FAIL_MISSING_NODE,
        FAIL_BAD_VALUE,
        FAIL_TREE_SHAPE,
        FAIL_RECURSION,
        FAIL_MEMORY,
        FAIL_KCT,
        FAIL_OTHER,
    }
)

_VERSION_RE = re.compile(r"\(\s*version\s+(\d+)\s*\)")
_DIGITS_RE = re.compile(r"\d+")


# ---------------------------------------------------------------------------
# Result records
# ---------------------------------------------------------------------------
@dataclass
class ArtifactResult:
    """Outcome of parsing one file payload (one schematic or one PCB)."""

    record_index: int
    record_name: str
    kind: str  # "schematic" | "pcb"
    slot: int  # index within the record's list (schematics are always 0)
    source: str  # dataset row offset or local path
    detected_format: str  # kicad_sch | kicad_pcb | legacy-eeschema | ...
    declared_version: str | None  # KiCad file-format version token, if present
    size_bytes: int
    outcome: str  # OK / a FAIL_* / a SKIP_* constant
    exception_type: str | None = None
    message: str | None = None
    signature: str | None = None  # digit-normalised message, for grouping
    elapsed_ms: float = 0.0
    retained_path: str | None = None  # where the payload was kept, if retained

    @property
    def failed(self) -> bool:
        return self.outcome in FAILURE_CLASSES


@dataclass
class RecordResult:
    """Outcome of one dataset record (a schematic plus its paired PCB files)."""

    index: int
    name: str
    description: str = ""
    extensions_used: list[str] = field(default_factory=list)
    truncated_cells: list[str] = field(default_factory=list)
    fetch_error: str | None = None
    artifacts: list[ArtifactResult] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Classification
# ---------------------------------------------------------------------------
def detect_format(text: str) -> str:
    """Sniff what kind of file a payload actually is, from its first bytes.

    The dataset's ``extensions_used`` field is per-record, not per-file, so the
    only reliable per-payload signal is the content itself.
    """
    head = text[:4096].lstrip()
    if head.startswith("(kicad_sch"):
        return "kicad_sch"
    if head.startswith("(kicad_pcb"):
        return "kicad_pcb"
    if head.startswith("(kicad_"):
        token = head[1:].split(None, 1)[0].strip("()")
        return f"kicad-other:{token}"
    if head.startswith("EESchema"):
        return "legacy-eeschema"
    if head.startswith("PCBNEW-BOARD") or head.startswith("(module"):
        return "legacy-pcbnew"
    if "|RECORD=" in head or head.startswith("\x00") or "Altium" in head[:512]:
        return "altium"
    if not head:
        return "empty"
    return "unknown"


def declared_version(text: str) -> str | None:
    """Extract the KiCad file-format version token (e.g. ``20231120``)."""
    match = _VERSION_RE.search(text[:4096])
    return match.group(1) if match else None


def classify_exception(exc: BaseException) -> str:
    """Map a parse exception onto a taxonomy bucket."""
    if isinstance(exc, RecursionError):
        return FAIL_RECURSION
    if isinstance(exc, MemoryError):
        return FAIL_MEMORY
    if isinstance(exc, UnicodeError):
        return FAIL_ENCODING
    if isinstance(exc, FileFormatError):
        return FAIL_WRONG_ROOT
    if isinstance(exc, SexpParseError):
        return FAIL_SEXPR_SYNTAX
    if isinstance(exc, KiCadToolsError):
        return FAIL_KCT
    if isinstance(exc, KeyError | IndexError):
        return FAIL_MISSING_NODE
    if isinstance(exc, AttributeError):
        return FAIL_TREE_SHAPE
    if isinstance(exc, ValueError | TypeError):
        return FAIL_BAD_VALUE
    return FAIL_OTHER


def signature_of(exc: BaseException) -> str:
    """Digit-normalised one-line exception signature, for grouping offenders.

    ``Expected atom at position 4172`` and ``Expected atom at position 91``
    are the same defect; collapsing the digits makes the "worst offenders"
    table count them together.
    """
    first_line = str(exc).strip().splitlines()[0] if str(exc).strip() else exc.__class__.__name__
    normalised = _DIGITS_RE.sub("N", first_line)
    return f"{exc.__class__.__name__}: {normalised[:160]}"


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------
def parse_payload(
    text: str,
    kind: str,
    scratch_dir: Path,
    stem: str,
    max_bytes: int,
) -> tuple[str, BaseException | None, float]:
    """Write ``text`` to a scratch file and load it with this repo's parser.

    Returns ``(outcome, exception_or_None, elapsed_ms)``. The scratch file is
    always removed; nothing is left behind outside ``scratch_dir``.
    """
    fmt = detect_format(text)
    size = len(text.encode("utf-8", errors="replace"))
    if fmt == "empty" or not text.strip():
        return SKIP_EMPTY, None, 0.0
    if size > max_bytes:
        return SKIP_OVERSIZE, None, 0.0

    expected = "kicad_sch" if kind == "schematic" else "kicad_pcb"
    if fmt != expected:
        # Legacy Eeschema, Altium, or a KiCad file of a different type: this
        # repo has no parser for these, so it is not a parser defect.
        return SKIP_NON_KICAD, None, 0.0

    suffix = ".kicad_sch" if kind == "schematic" else ".kicad_pcb"
    path = scratch_dir / f"{stem}{suffix}"
    started = time.perf_counter()
    try:
        path.write_text(text, encoding="utf-8")
        if kind == "schematic":
            Schematic.load(path)
        else:
            PCB.load(path)
    except BaseException as exc:  # the taxonomy IS the point: bucket, do not propagate
        if isinstance(exc, KeyboardInterrupt | SystemExit):
            raise
        return classify_exception(exc), exc, (time.perf_counter() - started) * 1000.0
    finally:
        path.unlink(missing_ok=True)
    return OK, None, (time.perf_counter() - started) * 1000.0


def probe_artifact(
    *,
    record_index: int,
    record_name: str,
    kind: str,
    slot: int,
    source: str,
    text: str,
    scratch_dir: Path,
    max_bytes: int,
) -> tuple[ArtifactResult, str | None]:
    """Parse one payload and build its :class:`ArtifactResult`.

    Returns the result plus the payload text when it should be considered for
    retention (i.e. it failed), so the caller can honour ``--keep-sources``.
    """
    stem = f"rec{record_index:07d}-{kind}{slot}"
    outcome, exc, elapsed = parse_payload(text, kind, scratch_dir, stem, max_bytes)
    result = ArtifactResult(
        record_index=record_index,
        record_name=record_name,
        kind=kind,
        slot=slot,
        source=source,
        detected_format=detect_format(text),
        declared_version=declared_version(text),
        size_bytes=len(text.encode("utf-8", errors="replace")),
        outcome=outcome,
        exception_type=type(exc).__name__ if exc is not None else None,
        message=str(exc).strip().splitlines()[0][:400] if exc is not None else None,
        signature=signature_of(exc) if exc is not None else None,
        elapsed_ms=round(elapsed, 2),
    )
    return result, (text if result.failed else None)


# ---------------------------------------------------------------------------
# Hugging Face access (stdlib + requests only -- no `datasets` dependency)
# ---------------------------------------------------------------------------
class HubError(RuntimeError):
    """A dataset request failed after all retries."""


def _requests_module() -> Any:
    try:
        # Imported lazily: --dry-run must work without it. The type-ignore keeps
        # the script clean under mypy without pulling types-requests into the
        # dev env (this file is outside the src/ baseline gate).
        import requests  # type: ignore[import-untyped]
    except ImportError as exc:  # pragma: no cover - dev envs always have it
        raise HubError(
            "the 'requests' package is required for network mode; "
            "run via `uv run python scripts/corpus/probe_open_schematics.py`, "
            "or use --dry-run for the offline path"
        ) from exc
    return requests


def hub_get_json(url: str, params: dict[str, Any], timeout: float, retries: int) -> dict[str, Any]:
    """GET a JSON endpoint with bounded retries and backoff."""
    requests = _requests_module()
    last: Exception | None = None
    for attempt in range(1, retries + 1):
        try:
            response = requests.get(
                url,
                params=params,
                timeout=timeout,
                headers={"User-Agent": USER_AGENT},
            )
            if response.status_code == 200:
                payload = response.json()
                if not isinstance(payload, dict):
                    raise HubError(f"{url}: expected a JSON object, got {type(payload).__name__}")
                return payload
            # 429/5xx are transient (datasets-server warms shards on demand).
            if response.status_code in (429, 500, 502, 503, 504):
                last = HubError(f"{url}: HTTP {response.status_code}")
            else:
                raise HubError(f"{url}: HTTP {response.status_code}: {response.text[:200]}")
        except HubError:
            raise
        except Exception as exc:  # requests raises a wide family of transport errors
            last = exc
        if attempt < retries:
            time.sleep(min(2.0 * attempt, 10.0))
    raise HubError(f"{url}: failed after {retries} attempts: {last}")


def dataset_revision(dataset: str, timeout: float, retries: int) -> str | None:
    """Resolve the dataset's current commit sha, so a report is reproducible."""
    try:
        info = hub_get_json(f"{HUB_API}/{dataset}", {}, timeout, retries)
    except HubError:
        return None
    sha = info.get("sha")
    return str(sha) if sha else None


def dataset_row_count(dataset: str, config: str, split: str, timeout: float, retries: int) -> int:
    """Total number of rows in the split (the sampling universe)."""
    info = hub_get_json(f"{DATASETS_SERVER}/info", {"dataset": dataset}, timeout, retries)
    configs: dict[str, Any] = info.get("dataset_info", {})
    entry: dict[str, Any] = configs.get(config) or next(iter(configs.values()), {})
    splits: dict[str, Any] = entry.get("splits", {})
    split_info: dict[str, Any] = splits.get(split) or next(iter(splits.values()), {})
    count = int(split_info.get("num_examples", 0))
    if count <= 0:
        raise HubError(f"{dataset}: could not determine row count for split '{split}'")
    return count


def fetch_row(
    dataset: str, config: str, split: str, offset: int, timeout: float, retries: int
) -> dict[str, Any]:
    """Fetch a single dataset row (one record) by absolute offset."""
    payload = hub_get_json(
        f"{DATASETS_SERVER}/rows",
        {
            "dataset": dataset,
            "config": config,
            "split": split,
            "offset": offset,
            "length": 1,
        },
        timeout,
        retries,
    )
    rows = payload.get("rows") or []
    if not rows:
        raise HubError(f"{dataset}: no row at offset {offset}")
    row = rows[0]
    return {
        "row": row.get("row", {}),
        "truncated_cells": list(row.get("truncated_cells") or []),
    }


# ---------------------------------------------------------------------------
# Probe drivers
# ---------------------------------------------------------------------------
def probe_hub_records(
    args: argparse.Namespace,
    offsets: list[int],
    scratch_dir: Path,
    retain: Path | None,
    keep_sources: str,
) -> list[RecordResult]:
    records: list[RecordResult] = []
    for position, offset in enumerate(offsets, start=1):
        _progress(args, f"[{position}/{len(offsets)}] record @offset {offset}")
        try:
            fetched = fetch_row(
                args.dataset, args.config, args.split, offset, args.timeout, args.retries
            )
        except HubError as exc:
            records.append(RecordResult(index=offset, name="", fetch_error=str(exc)))
            continue

        row = fetched["row"]
        truncated = fetched["truncated_cells"]
        record = RecordResult(
            index=offset,
            name=str(row.get("name") or f"offset-{offset}"),
            description=str(row.get("description") or "")[:300],
            extensions_used=[str(e) for e in (row.get("extensions_used") or [])],
            truncated_cells=truncated,
        )

        payloads: list[tuple[str, int, str]] = []
        if args.kinds in ("both", "schematic"):
            payloads.append(("schematic", 0, str(row.get("schematic") or "")))
        if args.kinds in ("both", "pcb"):
            for slot, pcb_text in enumerate(row.get("pcb_files") or []):
                payloads.append(("pcb", slot, str(pcb_text or "")))

        for kind, slot, text in payloads:
            cell = "schematic" if kind == "schematic" else "pcb_files"
            if cell in truncated:
                # The dataset API elided part of this cell; parsing it would
                # produce a bogus syntax error, so it is not a parser signal.
                record.artifacts.append(
                    ArtifactResult(
                        record_index=offset,
                        record_name=record.name,
                        kind=kind,
                        slot=slot,
                        source=f"row:{offset}",
                        detected_format=detect_format(text),
                        declared_version=declared_version(text),
                        size_bytes=len(text.encode("utf-8", errors="replace")),
                        outcome=SKIP_TRUNCATED,
                        message=f"datasets-server truncated cell '{cell}'",
                    )
                )
                continue
            result, failing_text = probe_artifact(
                record_index=offset,
                record_name=record.name,
                kind=kind,
                slot=slot,
                source=f"row:{offset}",
                text=text,
                scratch_dir=scratch_dir,
                max_bytes=args.max_bytes,
            )
            _retain(
                result, failing_text if keep_sources != "none" else None, text, retain, keep_sources
            )
            record.artifacts.append(result)
        records.append(record)
    return records


def local_candidates() -> list[Path]:
    """In-repo KiCad files used by ``--dry-run`` (no network required)."""
    roots = [REPO_ROOT / "boards", REPO_ROOT / "tests" / "fixtures"]
    found: list[Path] = []
    for root in roots:
        if not root.is_dir():
            continue
        for pattern in ("*.kicad_sch", "*.kicad_pcb"):
            found.extend(p for p in root.rglob(pattern) if p.is_file())
    return sorted(found)


def probe_local_records(
    args: argparse.Namespace,
    paths: list[Path],
    scratch_dir: Path,
    retain: Path | None,
    keep_sources: str,
) -> list[RecordResult]:
    records: list[RecordResult] = []
    for index, path in enumerate(paths):
        _progress(args, f"[{index + 1}/{len(paths)}] {path.relative_to(REPO_ROOT)}")
        kind = "schematic" if path.suffix == ".kicad_sch" else "pcb"
        record = RecordResult(
            index=index,
            name=str(path.relative_to(REPO_ROOT)),
            description="local dry-run fixture",
            extensions_used=[path.suffix],
        )
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            record.fetch_error = f"{type(exc).__name__}: {exc}"
            records.append(record)
            continue
        result, failing_text = probe_artifact(
            record_index=index,
            record_name=record.name,
            kind=kind,
            slot=0,
            source=str(path.relative_to(REPO_ROOT)),
            text=text,
            scratch_dir=scratch_dir,
            max_bytes=args.max_bytes,
        )
        _retain(result, failing_text, text, retain, keep_sources)
        record.artifacts.append(result)
        records.append(record)
    return records


def _retain(
    result: ArtifactResult,
    failing_text: str | None,
    text: str,
    retain: Path | None,
    keep_sources: str,
) -> None:
    """Persist a payload under the (gitignored) cache dir per ``--keep-sources``."""
    if retain is None or keep_sources == "none":
        return
    if keep_sources == "failures" and failing_text is None:
        return
    suffix = ".kicad_sch" if result.kind == "schematic" else ".kicad_pcb"
    target = retain / f"rec{result.record_index:07d}-{result.kind}{result.slot}{suffix}"
    try:
        target.write_text(text, encoding="utf-8")
    except OSError:
        return
    result.retained_path = str(target)


def _progress(args: argparse.Namespace, message: str) -> None:
    if not args.quiet:
        print(message, file=sys.stderr, flush=True)


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------
def build_report(
    args: argparse.Namespace,
    seed: int,
    revision: str | None,
    row_count: int,
    sampled: list[int] | list[str],
    records: list[RecordResult],
) -> dict[str, Any]:
    artifacts = [a for r in records for a in r.artifacts]
    by_class = Counter(a.outcome for a in artifacts)
    by_kind_class: dict[str, dict[str, int]] = {}
    for artifact in artifacts:
        by_kind_class.setdefault(artifact.kind, {})
        by_kind_class[artifact.kind][artifact.outcome] = (
            by_kind_class[artifact.kind].get(artifact.outcome, 0) + 1
        )

    attempted = [a for a in artifacts if a.outcome == OK or a.failed]
    failures = [a for a in artifacts if a.failed]
    signatures = Counter(a.signature for a in failures if a.signature)

    version_outcomes: dict[str, dict[str, int]] = {}
    for artifact in attempted:
        key = artifact.declared_version or "unknown"
        bucket = version_outcomes.setdefault(key, {"ok": 0, "failed": 0})
        bucket["failed" if artifact.failed else "ok"] += 1

    fetch_errors = [r for r in records if r.fetch_error]
    if fetch_errors:
        # A record we never received is its own taxonomy class -- it says
        # nothing about the parser, but it must not vanish from the counts.
        by_class[NET_ERROR] = len(fetch_errors)
    return {
        "schema_version": 1,
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "dataset": {
            "id": args.dataset,
            "config": args.config,
            "split": args.split,
            "revision": revision,
            "row_count": row_count,
            "license": "CC-BY-4.0",
            "url": f"https://huggingface.co/datasets/{args.dataset}",
        },
        "mode": "dry-run(local)" if args.dry_run else "hub",
        "sampling": {
            "seed": seed,
            "n_requested": args.n,
            "n_sampled": len(sampled),
            "kinds": args.kinds,
            "max_bytes": args.max_bytes,
            "sampled": sampled,
        },
        "totals": {
            "records_sampled": len(records),
            "records_fetch_failed": len(fetch_errors),
            "artifacts_seen": len(artifacts),
            "artifacts_parsed": len(attempted),
            "artifacts_ok": sum(1 for a in attempted if not a.failed),
            "artifacts_failed": len(failures),
            "parse_failure_rate": (round(len(failures) / len(attempted), 4) if attempted else None),
        },
        "by_class": dict(sorted(by_class.items(), key=lambda kv: (-kv[1], kv[0]))),
        "by_kind": by_kind_class,
        "by_declared_version": dict(sorted(version_outcomes.items())),
        "detected_formats": dict(Counter(a.detected_format for a in artifacts).most_common()),
        "top_signatures": [
            {
                "signature": sig,
                "count": count,
                "class": next(a.outcome for a in failures if a.signature == sig),
                "examples": [
                    {"record": a.record_name, "source": a.source, "kind": a.kind}
                    for a in failures
                    if a.signature == sig
                ][:3],
            }
            for sig, count in signatures.most_common(20)
        ],
        "fetch_errors": [{"index": r.index, "error": r.fetch_error} for r in fetch_errors],
        "records": [asdict(r) for r in records],
    }


def render_summary(report: dict[str, Any]) -> str:
    lines: list[str] = []
    dataset = report["dataset"]
    totals = report["totals"]
    sampling = report["sampling"]

    lines.append("=" * 78)
    lines.append("open-schematics corpus probe -- parser failure taxonomy")
    lines.append("=" * 78)
    lines.append(f"dataset      : {dataset['id']} ({dataset['license']})")
    lines.append(f"revision     : {dataset['revision'] or 'unknown'}")
    lines.append(f"mode         : {report['mode']}")
    lines.append(f"generated    : {report['generated_utc']}")
    lines.append(
        f"sampling     : n={sampling['n_sampled']}/{sampling['n_requested']} "
        f"of {dataset['row_count']} rows, seed={sampling['seed']}, kinds={sampling['kinds']}"
    )
    lines.append("")
    lines.append("-- totals " + "-" * 68)
    rate = totals["parse_failure_rate"]
    lines.append(
        f"records sampled     : {totals['records_sampled']} "
        f"({totals['records_fetch_failed']} fetch failures)"
    )
    lines.append(f"artifacts seen      : {totals['artifacts_seen']}")
    lines.append(f"artifacts parsed    : {totals['artifacts_parsed']}")
    lines.append(f"  parsed OK         : {totals['artifacts_ok']}")
    lines.append(
        f"  parse failures    : {totals['artifacts_failed']}"
        + (f" ({rate:.1%} of parsed)" if rate is not None else "")
    )
    lines.append("")
    lines.append("-- outcomes by class " + "-" * 57)
    for name, count in report["by_class"].items():
        marker = "FAIL" if name in FAILURE_CLASSES else ("ok  " if name == OK else "skip")
        lines.append(f"  [{marker}] {name:<34} {count:>6}")
    lines.append("")
    lines.append("-- outcomes by artifact kind " + "-" * 49)
    for kind, classes in sorted(report["by_kind"].items()):
        rendered = ", ".join(f"{k}={v}" for k, v in sorted(classes.items()))
        lines.append(f"  {kind:<12} {rendered}")
    lines.append("")
    lines.append("-- detected formats " + "-" * 58)
    for fmt, count in report["detected_formats"].items():
        lines.append(f"  {fmt:<28} {count:>6}")
    lines.append("")
    lines.append("-- parsed artifacts by declared KiCad file version " + "-" * 27)
    for version, counts in report["by_declared_version"].items():
        lines.append(f"  version {version:<12} ok={counts['ok']:<6} failed={counts['failed']}")
    lines.append("")
    lines.append("-- worst offenders (failure signatures) " + "-" * 38)
    if not report["top_signatures"]:
        lines.append("  (none -- every parsed artifact loaded cleanly)")
    for entry in report["top_signatures"]:
        lines.append(f"  {entry['count']:>4}x [{entry['class']}] {entry['signature']}")
        for example in entry["examples"]:
            lines.append(
                f"        e.g. {example['kind']} of {example['record']} ({example['source']})"
            )
    if report["fetch_errors"]:
        lines.append("")
        lines.append("-- fetch errors " + "-" * 62)
        for entry in report["fetch_errors"][:10]:
            lines.append(f"  offset {entry['index']}: {entry['error']}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="probe_open_schematics.py",
        description=(
            "Sample N random records from the bshada/open-schematics Hugging Face "
            "dataset, parse them with kicad_tools' own parsers, and emit a failure "
            "taxonomy report (JSON + human-readable). Local/opt-in: never run in CI."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Dataset: https://huggingface.co/datasets/bshada/open-schematics (CC-BY-4.0)\n"
            "Reports default to scripts/corpus/.cache/ (gitignored); sampled payloads\n"
            "are downloaded to a system temp dir that is removed on exit."
        ),
    )
    parser.add_argument("--n", type=int, default=50, help="records to sample (default: 50)")
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="RNG seed for reproducible sampling (default: random; the effective "
        "seed is recorded in the report so any run can be replayed)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help=f"report output directory (default: {DEFAULT_OUT_DIR.relative_to(REPO_ROOT)})",
    )
    parser.add_argument("--dataset", default=DEFAULT_DATASET, help="Hugging Face dataset id")
    parser.add_argument("--config", default="default", help="dataset config (default: default)")
    parser.add_argument("--split", default="train", help="dataset split (default: train)")
    parser.add_argument(
        "--kinds",
        choices=("both", "schematic", "pcb"),
        default="both",
        help="which payloads to parse per record (default: both)",
    )
    parser.add_argument(
        "--max-bytes",
        type=int,
        default=8_000_000,
        help="skip payloads larger than this many bytes (default: 8000000)",
    )
    parser.add_argument("--timeout", type=float, default=60.0, help="per-request timeout seconds")
    parser.add_argument("--retries", type=int, default=3, help="retries per HTTP request")
    parser.add_argument(
        "--keep-sources",
        choices=("none", "failures", "all"),
        default="failures",
        help="retain sampled payloads under <out>/sources/ for triage (default: failures)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="no network: sample in-repo KiCad files instead, exercising the same "
        "parse/classify/report path (useful offline or to smoke-test the script)",
    )
    parser.add_argument("--quiet", action="store_true", help="suppress per-record progress")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.n <= 0:
        print("error: --n must be positive", file=sys.stderr)
        return 2

    seed = args.seed if args.seed is not None else random.SystemRandom().randrange(2**32)
    rng = random.Random(seed)

    out_dir: Path = args.out.expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    retain_dir: Path | None = None
    if args.keep_sources != "none":
        retain_dir = out_dir / "sources"
        retain_dir.mkdir(parents=True, exist_ok=True)

    # Downloads land in a scratch dir OUTSIDE the repo, removed on exit.
    scratch_dir = Path(tempfile.mkdtemp(prefix="kct-corpus-probe-"))
    revision: str | None = None
    try:
        if args.dry_run:
            candidates = local_candidates()
            if not candidates:
                print("error: --dry-run found no in-repo KiCad files", file=sys.stderr)
                return 1
            chosen = rng.sample(candidates, min(args.n, len(candidates)))
            chosen.sort()
            sampled: list[int] | list[str] = [str(p.relative_to(REPO_ROOT)) for p in chosen]
            row_count = len(candidates)
            records = probe_local_records(args, chosen, scratch_dir, retain_dir, args.keep_sources)
        else:
            revision = dataset_revision(args.dataset, args.timeout, args.retries)
            row_count = dataset_row_count(
                args.dataset, args.config, args.split, args.timeout, args.retries
            )
            offsets = sorted(rng.sample(range(row_count), min(args.n, row_count)))
            sampled = offsets
            records = probe_hub_records(args, offsets, scratch_dir, retain_dir, args.keep_sources)
    except HubError as exc:
        print(f"error: {exc}", file=sys.stderr)
        print(
            "hint: re-run with --dry-run to exercise the parse/report path offline.",
            file=sys.stderr,
        )
        return 1
    except KeyboardInterrupt:
        print("interrupted", file=sys.stderr)
        return 130
    finally:
        shutil.rmtree(scratch_dir, ignore_errors=True)

    if not records:
        print("error: no records were sampled", file=sys.stderr)
        return 1

    report = build_report(args, seed, revision, row_count, sampled, records)
    summary = render_summary(report)

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    json_path = out_dir / f"probe-{stamp}.json"
    text_path = out_dir / f"probe-{stamp}.txt"
    json_path.write_text(json.dumps(report, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    text_path.write_text(summary + "\n", encoding="utf-8")

    print(summary)
    print(f"JSON report : {json_path}")
    print(f"text report : {text_path}")
    if retain_dir is not None:
        print(f"retained    : {retain_dir} (--keep-sources={args.keep_sources})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
