"""Packaged ``kct`` agent skills and their per-harness installer (issue #5950).

The skill sources live here as package data, in ``kct/*.md``, so a plain
``pip install kicad-tools`` carries them. This directory is the single source of
truth: the repo's ``.claude/commands/kct/`` is a byte-identical copy, kept in
step by ``scripts/sync_agent_skills.py`` and checked by
``tests/test_agent_skills_package.py``.

The sources use the harness-neutral placeholders of
:mod:`kicad_tools.agent_surfaces` (issue #5954). Installing renders them for
one harness and writes them in that harness's layout:

==============  ==========================  ======================================
Harness         Default target              Files written under the target
==============  ==========================  ======================================
``claude-code`` ``.claude/commands``        ``kct/<name>.md``, ``kct/README.md``
``codex``       ``.agents/skills``          ``kct-<name>/SKILL.md``,
                                            ``kct-help/README.md``
==============  ==========================  ======================================

A new harness (opencode, #5951) is one more :class:`HarnessLayout` in
:data:`LAYOUTS` plus its entry in :func:`kicad_tools.agent_surfaces.render`.
``kct skills install --harness`` takes its choices from :data:`LAYOUTS`.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from importlib import resources
from pathlib import Path

from kicad_tools.agent_surfaces import render

__all__ = [
    "DEFAULT_HARNESS",
    "LAYOUTS",
    "NAMESPACE",
    "NAMESPACE_README",
    "CheckReport",
    "HarnessLayout",
    "InstallReport",
    "SkillSource",
    "check_installed",
    "install_skills",
    "packaged_skill_sources",
    "planned_files",
    "resolve_target",
]

#: The skill namespace. Claude Code invokes these as ``/kct:<name>``.
NAMESPACE = "kct"

#: The namespace README ships alongside the skills but is not itself a skill.
NAMESPACE_README = "README.md"

#: The harness ``kct skills install`` targets when ``--harness`` is omitted.
DEFAULT_HARNESS = "claude-code"


@dataclass(frozen=True)
class SkillSource:
    """One packaged source file, before rendering."""

    filename: str
    text: str

    @property
    def is_readme(self) -> bool:
        return self.filename == NAMESPACE_README

    @property
    def name(self) -> str:
        """The skill name: the file stem (``tapeout`` for ``tapeout.md``)."""
        return self.filename.removesuffix(".md")


def packaged_skill_sources() -> list[SkillSource]:
    """Return every packaged ``kct/*.md`` source, sorted by filename."""
    root = resources.files(__name__).joinpath(NAMESPACE)
    sources = [
        SkillSource(entry.name, entry.read_text(encoding="utf-8"))
        for entry in root.iterdir()
        if entry.is_file() and entry.name.endswith(".md")
    ]
    if not sources:
        raise FileNotFoundError(f"no packaged skills found under {root}")
    return sorted(sources, key=lambda s: s.filename)


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Split ``---``-fenced YAML frontmatter from *text*.

    Only single-line ``key: value`` pairs are read, which is all the skill
    frontmatter uses. A ``---`` horizontal rule later in the body is left alone.
    Returns ``({}, text)`` when there is no frontmatter.
    """
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 3)
    if end == -1:
        return {}, text
    fields: dict[str, str] = {}
    for line in text[4:end].splitlines():
        key, sep, value = line.partition(":")
        if sep and key and not key.startswith((" ", "\t")):
            fields[key.strip()] = value.strip()
    return fields, text[end + len("\n---\n") :]


# --- per-harness layouts -----------------------------------------------------


def _claude_code_files(sources: list[SkillSource]) -> dict[str, str]:
    return {f"{NAMESPACE}/{s.filename}": render(s.text, "claude-code") for s in sources}


def _codex_skill_md(source: SkillSource) -> str:
    fields, body = split_frontmatter(source.text)
    name = fields.get("name") or source.name
    description = fields.get("description")
    if not description:
        raise ValueError(f"skill {source.filename} has no frontmatter 'description:'")
    # Codex's SKILL.md takes only name/description; the Claude Code dispatch keys
    # (invocation, suggestedModel) are dropped, as scripts/install-kct.sh does.
    return (
        "---\n"
        f"name: {NAMESPACE}-{name}\n"
        "description: >-\n"
        f"  {render(description, 'codex')}\n"
        "---\n"
        f"<!-- Generated by `kct skills install` from kicad_tools/agent_skills/"
        f"{NAMESPACE}/{source.filename} (kicad-tools). Edit the upstream original, "
        "not this file; re-running the installer overwrites it. -->\n"
        f"{render(body, 'codex').rstrip(chr(10))}\n"
    )


def _codex_files(sources: list[SkillSource]) -> dict[str, str]:
    files: dict[str, str] = {}
    for source in sources:
        if source.is_readme:
            # The namespace README sits beside the always-present help skill.
            files[f"{NAMESPACE}-help/README.md"] = render(source.text, "codex")
        else:
            files[f"{NAMESPACE}-{source.name}/SKILL.md"] = _codex_skill_md(source)
    return files


@dataclass(frozen=True)
class HarnessLayout:
    """Where and how one harness expects the ``kct`` skills."""

    harness: str
    #: Project-relative install root, used when neither --target nor --user.
    project_dir: str
    #: Home-relative install root for ``--user``.
    user_dir: str
    #: Globs (relative to the target) matching files this installer owns, used
    #: to spot stale files from an older install.
    managed_globs: tuple[str, ...]
    build: Callable[[list[SkillSource]], dict[str, str]] = field(repr=False)
    #: How a user invokes skill *name* in this harness.
    invocation: Callable[[str], str] = field(repr=False)

    def files(self, sources: list[SkillSource] | None = None) -> dict[str, str]:
        """Rendered content keyed by target-relative POSIX path."""
        return self.build(packaged_skill_sources() if sources is None else sources)


LAYOUTS: dict[str, HarnessLayout] = {
    "claude-code": HarnessLayout(
        harness="claude-code",
        project_dir=".claude/commands",
        user_dir=".claude/commands",
        managed_globs=(f"{NAMESPACE}/*.md",),
        build=_claude_code_files,
        invocation=lambda name: render(f"{{{{skill:{name}}}}}", "claude-code"),
    ),
    "codex": HarnessLayout(
        harness="codex",
        project_dir=".agents/skills",
        user_dir=".agents/skills",
        managed_globs=(f"{NAMESPACE}-*/SKILL.md", f"{NAMESPACE}-*/README.md"),
        build=_codex_files,
        invocation=lambda name: render(f"{{{{skill:{name}}}}}", "codex"),
    ),
}


def _layout(harness: str) -> HarnessLayout:
    try:
        return LAYOUTS[harness]
    except KeyError:
        raise ValueError(f"unknown harness {harness!r}; expected one of {tuple(LAYOUTS)}") from None


def planned_files(harness: str = DEFAULT_HARNESS) -> dict[str, str]:
    """Rendered files ``install_skills`` would write, keyed by relative path."""
    return _layout(harness).files()


def resolve_target(
    harness: str = DEFAULT_HARNESS,
    target: str | Path | None = None,
    *,
    user: bool = False,
    cwd: Path | None = None,
    home: Path | None = None,
) -> Path:
    """Resolve the install root for *harness*.

    ``target`` wins; ``user`` selects the home-directory root; otherwise the
    harness's project-relative root under *cwd*.
    """
    layout = _layout(harness)
    if target is not None and user:
        raise ValueError("--target and --user are mutually exclusive")
    if target is not None:
        return Path(target).expanduser()
    if user:
        return (home if home is not None else Path.home()) / layout.user_dir
    return (cwd if cwd is not None else Path.cwd()) / layout.project_dir


def _stale_files(layout: HarnessLayout, target: Path, planned: dict[str, str]) -> list[str]:
    found: set[str] = set()
    for pattern in layout.managed_globs:
        for path in target.glob(pattern):
            if path.is_file():
                found.add(path.relative_to(target).as_posix())
    return sorted(found - planned.keys())


@dataclass
class InstallReport:
    harness: str
    target: Path
    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    stale: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    dry_run: bool = False

    def to_dict(self) -> dict[str, object]:
        return {
            "harness": self.harness,
            "target": str(self.target),
            "dry_run": self.dry_run,
            "written": self.written,
            "unchanged": self.unchanged,
            "stale": self.stale,
            "removed": self.removed,
        }


def install_skills(
    target: Path,
    harness: str = DEFAULT_HARNESS,
    *,
    dry_run: bool = False,
    prune: bool = False,
) -> InstallReport:
    """Render the packaged skills for *harness* and write them under *target*.

    Files already identical are left untouched. Managed files that the package
    no longer ships are reported as ``stale`` and only deleted with *prune*.
    Nothing outside the layout's managed paths is ever touched.
    """
    layout = _layout(harness)
    planned = layout.files()
    report = InstallReport(harness=harness, target=target, dry_run=dry_run)
    for rel, content in sorted(planned.items()):
        dst = target / rel
        if dst.is_file() and dst.read_text(encoding="utf-8") == content:
            report.unchanged.append(rel)
            continue
        report.written.append(rel)
        if not dry_run:
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_text(content, encoding="utf-8")
    report.stale = _stale_files(layout, target, planned)
    if prune:
        for rel in report.stale:
            report.removed.append(rel)
            if not dry_run:
                (target / rel).unlink()
    return report


@dataclass
class CheckReport:
    harness: str
    target: Path
    ok: list[str] = field(default_factory=list)
    missing: list[str] = field(default_factory=list)
    drifted: list[str] = field(default_factory=list)
    stale: list[str] = field(default_factory=list)

    @property
    def in_sync(self) -> bool:
        return not (self.missing or self.drifted or self.stale)

    def to_dict(self) -> dict[str, object]:
        return {
            "harness": self.harness,
            "target": str(self.target),
            "in_sync": self.in_sync,
            "ok": self.ok,
            "missing": self.missing,
            "drifted": self.drifted,
            "stale": self.stale,
        }


def check_installed(target: Path, harness: str = DEFAULT_HARNESS) -> CheckReport:
    """Compare an installed skill tree against the packaged, rendered version."""
    layout = _layout(harness)
    planned = layout.files()
    report = CheckReport(harness=harness, target=target)
    for rel, content in sorted(planned.items()):
        dst = target / rel
        if not dst.is_file():
            report.missing.append(rel)
        elif dst.read_text(encoding="utf-8") != content:
            report.drifted.append(rel)
        else:
            report.ok.append(rel)
    report.stale = _stale_files(layout, target, planned)
    return report
