#!/usr/bin/env python3
"""Regenerate tests/ci_extended.txt from measured test times (Issue #6013).

    uv run python scripts/ci/update_ci_extended.py JUNIT.xml [JUNIT.xml ...] [--threshold 3.0]

Every test whose measured time is at least --threshold seconds is written to
tests/ci_extended.txt, slowest first. tests/conftest.py gives those tests the
`ci_extended` marker: the "Test" job deselects them so it fits a GitHub-hosted
runner on every PR, and the "Test (extended)" job runs them on main pushes and
the nightly schedule.

Inputs are JUnit XML files from `pytest --junitxml`. In CI, the "Retain test
timings" steps upload them (artifacts junit-bulk-* and junit-extended-*);
download both from one main run so the list covers the whole bulk pool. A test
measured in several files keeps its largest time.
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "tests" / "ci_extended.txt"
HEADER = """\
# Tests deselected from the "Test" job and run by "Test (extended)" instead
# (Issue #6013). Each line is a pytest node id; tests/conftest.py gives these
# tests the `ci_extended` marker. Generated by scripts/ci/update_ci_extended.py
# from measured times (threshold {threshold:g} s); regenerate rather than edit
# by hand. A listed id that no longer exists is ignored.
"""


def node_id(classname: str, name: str) -> str | None:
    """Map a JUnit (classname, name) pair back to a pytest node id."""
    parts = classname.split(".")
    for i in range(len(parts), 0, -1):
        path = "/".join(parts[:i]) + ".py"
        if (REPO / path).is_file():
            return path + "".join("::" + p for p in parts[i:]) + "::" + name
    return None


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("junit", nargs="+", type=Path)
    ap.add_argument("--threshold", type=float, default=3.0)
    args = ap.parse_args(argv)

    times: dict[str, float] = {}
    unresolved = 0
    for f in args.junit:
        for case in ET.parse(f).getroot().iter("testcase"):
            nid = node_id(case.get("classname", ""), case.get("name", ""))
            if nid is None:
                unresolved += 1
                continue
            times[nid] = max(times.get(nid, 0.0), float(case.get("time") or 0.0))

    chosen = sorted((t, n) for n, t in times.items() if t >= args.threshold)
    chosen.reverse()
    OUT.write_text(HEADER.format(threshold=args.threshold) + "".join(n + "\n" for _, n in chosen))
    total = sum(times.values())
    moved = sum(t for t, _ in chosen)
    print(
        f"{len(chosen)} of {len(times)} tests >= {args.threshold:g} s "
        f"({moved:.0f} of {total:.0f} test-seconds, {100 * moved / max(total, 1):.0f}%) "
        f"-> {OUT.relative_to(REPO)}; {unresolved} unresolved",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
