#!/usr/bin/env python3
"""Audit the kct machine-output idiom across every CLI leaf subcommand.

Walks the real argparse tree built by ``create_parser()`` (recursive walk of
``_SubParsersAction`` leaves) and classifies each leaf subcommand:

* ``format-json``   -- has ``--format`` with a ``json`` choice (canonical)
* ``both``          -- has ``--format json`` AND a legacy ``--json`` alias
* ``json-bool``     -- has only a boolean ``--json`` flag (legacy)
* ``format-nojson`` -- has ``--format`` but no ``json`` choice
* ``prose-only``    -- no machine-output flag at all

This is the measurement tool behind ``docs/reference/machine-output.md``
(issue #4543) and the mechanical-sweep backlog (#4674).  Re-run it whenever
the inventory in that document needs refreshing:

    uv run python scripts/audit_machine_output.py            # plain text
    uv run python scripts/audit_machine_output.py --markdown # doc tables

Note: the ``kct footprint generate`` leaf is an argv-passthrough stub -- its
real machine-output surface lives on the shape subparsers inside
``src/kicad_tools/cli/footprint_generate.py``, which this walk cannot see.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from collections.abc import Iterator

from kicad_tools.cli.parser import create_parser

BUCKET_ORDER = ("format-json", "both", "json-bool", "format-nojson", "prose-only")


def iter_leaves(
    parser: argparse.ArgumentParser, path: tuple[str, ...] = ()
) -> Iterator[tuple[tuple[str, ...], argparse.ArgumentParser]]:
    """Yield (command path, parser) for every leaf subparser."""
    subactions = [a for a in parser._actions if isinstance(a, argparse._SubParsersAction)]
    if not subactions:
        yield path, parser
        return
    for subaction in subactions:
        for name, sub in subaction.choices.items():
            yield from iter_leaves(sub, path + (name,))


def classify(parser: argparse.ArgumentParser) -> tuple[str, list[str] | None]:
    """Classify one leaf parser; returns (bucket, --format choices or None)."""
    has_format = has_format_json = has_json_bool = False
    format_choices: list[str] | None = None
    for action in parser._actions:
        opts = set(action.option_strings)
        if "--format" in opts:
            has_format = True
            format_choices = list(action.choices) if action.choices else None
            if action.choices and "json" in action.choices:
                has_format_json = True
        if "--json" in opts:
            has_json_bool = True
    if has_format_json and has_json_bool:
        return "both", format_choices
    if has_format_json:
        return "format-json", format_choices
    if has_json_bool:
        return "json-bool", format_choices
    if has_format:
        return "format-nojson", format_choices
    return "prose-only", format_choices


def git_head() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--markdown",
        action="store_true",
        help="Emit markdown tables suitable for docs/reference/machine-output.md",
    )
    opts = ap.parse_args(argv)

    buckets: dict[str, list[tuple[str, list[str] | None]]] = {k: [] for k in BUCKET_ORDER}
    for path, leaf in iter_leaves(create_parser()):
        bucket, choices = classify(leaf)
        buckets[bucket].append((" ".join(path), choices))
    for cmds in buckets.values():
        cmds.sort()

    total = sum(len(v) for v in buckets.values())
    sha = git_head()

    if opts.markdown:
        print(f"<!-- generated by scripts/audit_machine_output.py at {sha} -->")
        print(f"\nTotal leaf subcommands: **{total}**\n")
        print("| Idiom | Count |")
        print("|---|---|")
        for bucket in BUCKET_ORDER:
            print(f"| `{bucket}` | {len(buckets[bucket])} |")
        for bucket in BUCKET_ORDER:
            cmds = buckets[bucket]
            if not cmds:
                continue
            print(f"\n### {bucket} ({len(cmds)})\n")
            for cmd, choices in cmds:
                suffix = f" `[{','.join(choices)}]`" if choices else ""
                print(f"- `kct {cmd}`{suffix}")
    else:
        print(f"as of {sha}: {total} leaf subcommands")
        for bucket in BUCKET_ORDER:
            cmds = buckets[bucket]
            print(f"\n== {bucket} ({len(cmds)}) ==")
            for cmd, choices in cmds:
                suffix = f"  [{','.join(choices)}]" if choices else ""
                print(f"  {cmd}{suffix}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
