"""
PCB Autorouter module.

Provides A* pathfinding-based autorouting with:
- Net class awareness (power, clock, audio, digital)
- Multi-layer support with via management
- Congestion-aware routing with negotiated costs
- Pluggable heuristics (Manhattan, DirectionBias, CongestionAware, etc.)

Example::

    from kicad_tools.router import Autorouter, DesignRules

    rules = DesignRules(
        grid_resolution=0.1,
        trace_width=0.2,
        trace_clearance=0.2,
    )

    router = Autorouter(width=100, height=80, rules=rules)
    router.add_component("U1", pads=[...])
    result = router.route_all()
    print(f"Routed {result.routed_nets}/{result.total_nets} nets")
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .adaptive_grid import (
        AdaptiveGridResult,
        AdaptiveGridRouter,
        FinePitchEscapeFailure,
        identify_fine_pitch_components,
    )
    from .analysis import (
        BlockingObstacle,
        CongestionZone,
        NetRoutabilityReport,
        ObstacleType,
        RoutabilityAnalyzer,
        RoutabilityReport,
        RouteAlternative,
        RoutingFailureDiagnostic,
        RoutingSeverity,
        analyze_routing_failure,
    )
    from .block_router import BlockRouter, BlockRoutingResult
    from .bus import (
        BusGroup,
        BusRoutingConfig,
        BusRoutingMode,
        BusSignal,
        analyze_buses,
        detect_bus_signals,
        group_buses,
    )
    from .cache import (
        CachedNetRoute,
        CachedRoutingResult,
        CachedSubProblem,
        CacheKey,
        RoutingCache,
        SubProblemSignature,
        compute_pad_positions_hash,
        get_default_cache_path,
        normalize_routes_to_origin,
        transform_routes,
    )
    from .congestion_estimator import CongestionEstimator, NetBBox, TileGrid
    from .core import AdaptiveAutorouter, Autorouter, RoutingFailure
    from .cpp_backend import (
        CppGrid,
        CppPathfinder,
        create_hybrid_router,
        ensure_cpp_backend_available,
        get_backend_info,
        is_cpp_available,
    )
    from .diffpair import (
        DifferentialPair,
        DifferentialPairConfig,
        DifferentialPairRules,
        DifferentialPairType,
        DifferentialSignal,
        LengthMismatchWarning,
        analyze_differential_pairs,
        detect_differential_pairs,
        detect_differential_signals,
        group_differential_pairs,
    )
    from .drc_nudge import DRCNudgeResult, drc_verify_and_nudge
    from .escape import (
        EscapeDirection,
        EscapeRoute,
        EscapeRouter,
        PackageInfo,
        PackageType,
        detect_package_type,
        get_package_info,
        is_dense_package,
        is_fine_pitch_ssop,
        is_usb_c_class_connector,
    )
    from .failure_analysis import (
        BlockingElement,
        CongestionMap,
        FailureAnalysis,
        FailureCause,
        PathAttempt,
        RootCauseAnalyzer,
    )
    from .fine_pitch import (
        ComponentGridAnalysis,
        FinePitchReport,
        FinePitchSeverity,
        OffGridPad,
        analyze_fine_pitch_components,
    )
    from .fine_pitch_escape import (
        DEFAULT_ESCAPE_REGION_RADIUS_MM,
        ESCAPE_CLEARANCE_SAFETY_MARGIN_MM,
        FinePitchRegion,
        detect_fine_pitch_regions,
        geometry_needs_fine_pitch_escape,
        get_default_escape_clearance,
        resolve_clearance_with_escape_region,
    )
    from .global_router import CorridorAssignment, GlobalRouter, GlobalRoutingResult
    from .grid import RoutingGrid
    from .heuristics import (
        CongestionAwareHeuristic,
        DirectionBiasHeuristic,
        GreedyHeuristic,
        Heuristic,
        HeuristicContext,
        ManhattanHeuristic,
        WeightedCongestionHeuristic,
    )
    from .io import (
        ClearanceViolation,
        FineZone,
        GridAdjustment,
        GridAutoSelection,
        GridResolutionError,
        GridSafetyError,
        MultiResolutionGridPlan,
        PadPosition,
        PCBDesignRules,
        adjust_grid_for_compliance,
        auto_select_grid_resolution,
        compute_multi_resolution_plan,
        detect_layer_stack,
        extract_board_dimensions,
        extract_pad_positions,
        generate_netclass_setup,
        load_pads_for_analysis,
        load_pcb_for_routing,
        merge_routes_into_pcb,
        parse_pcb_design_rules,
        recommend_grid_for_board_size,
        route_pcb,
        validate_grid_resolution,
        validate_routes,
    )
    from .layers import (
        Layer,
        LayerDefinition,
        LayerStack,
        LayerType,
        ViaDefinition,
        ViaRules,
        ViaType,
    )
    from .length import (
        LengthTracker,
        LengthViolation,
        ViolationType,
        create_match_group,
    )
    from .match_group_detection import (
        BUS_GROUP_PATTERNS,
        detect_match_groups,
    )
    from .match_group_length import (
        MatchGroup,
        MatchGroupSource,
        MatchGroupTracker,
    )
    from .mfr_limits import (
        MFR_JLCPCB,
        MFR_LIMITS,
        MFR_OSHPARK,
        MFR_PCBWAY,
        MfrLimits,
        RelaxationTier,
        get_mfr_limits,
        get_relaxation_tiers,
    )
    from .net_class import (
        NET_CLASS_PATTERNS,
        SYMBOL_INDICATORS,
        NetClass,
        NetClassification,
        apply_net_class_rules,
        auto_classify_nets,
        classify_and_apply_rules,
        classify_from_name,
        classify_from_pin_type,
        classify_from_symbol,
        classify_net,
        find_differential_partner,
        is_differential_pair_name,
    )
    from .optimizer import (
        CollisionChecker,
        GridCollisionChecker,
        OptimizationConfig,
        OptimizationStats,
        TraceOptimizer,
        VectorCollisionChecker,
    )
    from .orchestrator import RoutingOrchestrator
    from .output import (
        format_failed_nets_summary,
        get_routing_diagnostics_json,
        print_routing_diagnostics_json,
        show_fine_pitch_warnings,
        show_routing_summary,
    )
    from .parallel import (
        BoundingBox,
        NetGroup,
        ParallelRouter,
        ParallelRoutingResult,
        find_independent_groups,
        find_route_conflicts,
        resolve_parallel_conflicts,
    )
    from .pathfinder import AStarNode, Router
    from .placement_delta import (
        PlacementDelta,
        delta_from_diagnosis,
        deltas_from_result,
        endpoint_align_deltas,
    )
    from .placement_feedback import (
        PlacementAdjustment,
        PlacementDeltaFeedbackLoop,
        PlacementDeltaFeedbackResult,
        PlacementDiffEntry,
        PlacementFeedbackLoop,
        PlacementFeedbackResult,
        detect_pf_stagnation,
        write_placement_delta_json,
    )
    from .preflight import (
        OffGridReport,
        PreflightOffGridPad,
        check_pad_grid_alignment,
    )
    from .primitives import GridCell, Obstacle, Pad, Point, Route, Segment, Via
    from .region_graph import Region, RegionEdge, RegionGraph
    from .rules import (
        DEFAULT_NET_CLASS_MAP,
        NET_CLASS_AUDIO,
        NET_CLASS_CLOCK,
        NET_CLASS_DEBUG,
        NET_CLASS_DEFAULT,
        NET_CLASS_DIGITAL,
        NET_CLASS_HIGH_CURRENT_SIGNAL,
        NET_CLASS_HIGH_SPEED,
        NET_CLASS_POWER,
        DesignRules,
        LengthConstraint,
        NetClassRouting,
        ZoneRules,
        create_net_class_map,
    )
    from .sparse import SparseRouter, SparseRoutingGraph, Waypoint
    from .strategies import (
        AlternativeStrategy,
        DRCViolation,
        PerformanceStats,
        RepairAction,
        RoutingMetrics,
        RoutingResult,
        RoutingStrategy,
    )
    from .subgrid import (
        SubGridAnalysis,
        SubGridEscape,
        SubGridPad,
        SubGridResult,
        SubGridRouter,
        compute_subgrid_resolution,
    )
    from .tuning import (
        COST_PROFILES,
        BoardCharacteristics,
        CostParams,
        CostProfile,
        RoutingQualityScore,
        TuningResult,
        analyze_board,
        create_adaptive_router,
        evaluate_routing_quality,
        quick_tune,
        select_profile,
        tune_parameters,
    )
    from .zones import (
        ConnectionType,
        FilledZone,
        ThermalRelief,
        ZoneFiller,
        ZoneManager,
        fill_zones_by_priority,
        get_connection_type,
    )

# Keep lightweight consumers from importing every routing engine.
_EXPORT_MODULES: dict[str, str] = {
    "AdaptiveGridResult": ".adaptive_grid",
    "AdaptiveGridRouter": ".adaptive_grid",
    "FinePitchEscapeFailure": ".adaptive_grid",
    "identify_fine_pitch_components": ".adaptive_grid",
    "BlockingObstacle": ".analysis",
    "CongestionZone": ".analysis",
    "NetRoutabilityReport": ".analysis",
    "ObstacleType": ".analysis",
    "RoutabilityAnalyzer": ".analysis",
    "RoutabilityReport": ".analysis",
    "RouteAlternative": ".analysis",
    "RoutingFailureDiagnostic": ".analysis",
    "RoutingSeverity": ".analysis",
    "analyze_routing_failure": ".analysis",
    "BlockRouter": ".block_router",
    "BlockRoutingResult": ".block_router",
    "BusGroup": ".bus",
    "BusRoutingConfig": ".bus",
    "BusRoutingMode": ".bus",
    "BusSignal": ".bus",
    "analyze_buses": ".bus",
    "detect_bus_signals": ".bus",
    "group_buses": ".bus",
    "CachedNetRoute": ".cache",
    "CachedRoutingResult": ".cache",
    "CachedSubProblem": ".cache",
    "CacheKey": ".cache",
    "RoutingCache": ".cache",
    "SubProblemSignature": ".cache",
    "compute_pad_positions_hash": ".cache",
    "get_default_cache_path": ".cache",
    "normalize_routes_to_origin": ".cache",
    "transform_routes": ".cache",
    "CongestionEstimator": ".congestion_estimator",
    "NetBBox": ".congestion_estimator",
    "TileGrid": ".congestion_estimator",
    "AdaptiveAutorouter": ".core",
    "Autorouter": ".core",
    "RoutingFailure": ".core",
    "CppGrid": ".cpp_backend",
    "CppPathfinder": ".cpp_backend",
    "create_hybrid_router": ".cpp_backend",
    "ensure_cpp_backend_available": ".cpp_backend",
    "get_backend_info": ".cpp_backend",
    "is_cpp_available": ".cpp_backend",
    "DifferentialPair": ".diffpair",
    "DifferentialPairConfig": ".diffpair",
    "DifferentialPairRules": ".diffpair",
    "DifferentialPairType": ".diffpair",
    "DifferentialSignal": ".diffpair",
    "LengthMismatchWarning": ".diffpair",
    "analyze_differential_pairs": ".diffpair",
    "detect_differential_pairs": ".diffpair",
    "detect_differential_signals": ".diffpair",
    "group_differential_pairs": ".diffpair",
    "DRCNudgeResult": ".drc_nudge",
    "drc_verify_and_nudge": ".drc_nudge",
    "EscapeDirection": ".escape",
    "EscapeRoute": ".escape",
    "EscapeRouter": ".escape",
    "PackageInfo": ".escape",
    "PackageType": ".escape",
    "detect_package_type": ".escape",
    "get_package_info": ".escape",
    "is_dense_package": ".escape",
    "is_fine_pitch_ssop": ".escape",
    "is_usb_c_class_connector": ".escape",
    "BlockingElement": ".failure_analysis",
    "CongestionMap": ".failure_analysis",
    "FailureAnalysis": ".failure_analysis",
    "FailureCause": ".failure_analysis",
    "PathAttempt": ".failure_analysis",
    "RootCauseAnalyzer": ".failure_analysis",
    "ComponentGridAnalysis": ".fine_pitch",
    "FinePitchReport": ".fine_pitch",
    "FinePitchSeverity": ".fine_pitch",
    "OffGridPad": ".fine_pitch",
    "analyze_fine_pitch_components": ".fine_pitch",
    "DEFAULT_ESCAPE_REGION_RADIUS_MM": ".fine_pitch_escape",
    "ESCAPE_CLEARANCE_SAFETY_MARGIN_MM": ".fine_pitch_escape",
    "FinePitchRegion": ".fine_pitch_escape",
    "detect_fine_pitch_regions": ".fine_pitch_escape",
    "geometry_needs_fine_pitch_escape": ".fine_pitch_escape",
    "get_default_escape_clearance": ".fine_pitch_escape",
    "resolve_clearance_with_escape_region": ".fine_pitch_escape",
    "CorridorAssignment": ".global_router",
    "GlobalRouter": ".global_router",
    "GlobalRoutingResult": ".global_router",
    "RoutingGrid": ".grid",
    "CongestionAwareHeuristic": ".heuristics",
    "DirectionBiasHeuristic": ".heuristics",
    "GreedyHeuristic": ".heuristics",
    "Heuristic": ".heuristics",
    "HeuristicContext": ".heuristics",
    "ManhattanHeuristic": ".heuristics",
    "WeightedCongestionHeuristic": ".heuristics",
    "ClearanceViolation": ".io",
    "FineZone": ".io",
    "GridAdjustment": ".io",
    "GridAutoSelection": ".io",
    "GridResolutionError": ".io",
    "GridSafetyError": ".io",
    "MultiResolutionGridPlan": ".io",
    "PadPosition": ".io",
    "PCBDesignRules": ".io",
    "adjust_grid_for_compliance": ".io",
    "auto_select_grid_resolution": ".io",
    "compute_multi_resolution_plan": ".io",
    "detect_layer_stack": ".io",
    "extract_board_dimensions": ".io",
    "extract_pad_positions": ".io",
    "generate_netclass_setup": ".io",
    "load_pads_for_analysis": ".io",
    "load_pcb_for_routing": ".io",
    "merge_routes_into_pcb": ".io",
    "parse_pcb_design_rules": ".io",
    "recommend_grid_for_board_size": ".io",
    "route_pcb": ".io",
    "validate_grid_resolution": ".io",
    "validate_routes": ".io",
    "Layer": ".layers",
    "LayerDefinition": ".layers",
    "LayerStack": ".layers",
    "LayerType": ".layers",
    "ViaDefinition": ".layers",
    "ViaRules": ".layers",
    "ViaType": ".layers",
    "LengthTracker": ".length",
    "LengthViolation": ".length",
    "ViolationType": ".length",
    "create_match_group": ".length",
    "BUS_GROUP_PATTERNS": ".match_group_detection",
    "detect_match_groups": ".match_group_detection",
    "MatchGroup": ".match_group_length",
    "MatchGroupSource": ".match_group_length",
    "MatchGroupTracker": ".match_group_length",
    "MFR_JLCPCB": ".mfr_limits",
    "MFR_LIMITS": ".mfr_limits",
    "MFR_OSHPARK": ".mfr_limits",
    "MFR_PCBWAY": ".mfr_limits",
    "MfrLimits": ".mfr_limits",
    "RelaxationTier": ".mfr_limits",
    "get_mfr_limits": ".mfr_limits",
    "get_relaxation_tiers": ".mfr_limits",
    "NET_CLASS_PATTERNS": ".net_class",
    "SYMBOL_INDICATORS": ".net_class",
    "NetClass": ".net_class",
    "NetClassification": ".net_class",
    "apply_net_class_rules": ".net_class",
    "auto_classify_nets": ".net_class",
    "classify_and_apply_rules": ".net_class",
    "classify_from_name": ".net_class",
    "classify_from_pin_type": ".net_class",
    "classify_from_symbol": ".net_class",
    "classify_net": ".net_class",
    "find_differential_partner": ".net_class",
    "is_differential_pair_name": ".net_class",
    "CollisionChecker": ".optimizer",
    "GridCollisionChecker": ".optimizer",
    "OptimizationConfig": ".optimizer",
    "OptimizationStats": ".optimizer",
    "TraceOptimizer": ".optimizer",
    "VectorCollisionChecker": ".optimizer",
    "RoutingOrchestrator": ".orchestrator",
    "format_failed_nets_summary": ".output",
    "get_routing_diagnostics_json": ".output",
    "print_routing_diagnostics_json": ".output",
    "show_fine_pitch_warnings": ".output",
    "show_routing_summary": ".output",
    "BoundingBox": ".parallel",
    "NetGroup": ".parallel",
    "ParallelRouter": ".parallel",
    "ParallelRoutingResult": ".parallel",
    "find_independent_groups": ".parallel",
    "find_route_conflicts": ".parallel",
    "resolve_parallel_conflicts": ".parallel",
    "AStarNode": ".pathfinder",
    "Router": ".pathfinder",
    "PlacementDelta": ".placement_delta",
    "delta_from_diagnosis": ".placement_delta",
    "deltas_from_result": ".placement_delta",
    "endpoint_align_deltas": ".placement_delta",
    "PlacementAdjustment": ".placement_feedback",
    "PlacementDeltaFeedbackLoop": ".placement_feedback",
    "PlacementDeltaFeedbackResult": ".placement_feedback",
    "PlacementDiffEntry": ".placement_feedback",
    "PlacementFeedbackLoop": ".placement_feedback",
    "PlacementFeedbackResult": ".placement_feedback",
    "detect_pf_stagnation": ".placement_feedback",
    "write_placement_delta_json": ".placement_feedback",
    "OffGridReport": ".preflight",
    "PreflightOffGridPad": ".preflight",
    "check_pad_grid_alignment": ".preflight",
    "GridCell": ".primitives",
    "Obstacle": ".primitives",
    "Pad": ".primitives",
    "Point": ".primitives",
    "Route": ".primitives",
    "Segment": ".primitives",
    "Via": ".primitives",
    "Region": ".region_graph",
    "RegionEdge": ".region_graph",
    "RegionGraph": ".region_graph",
    "DEFAULT_NET_CLASS_MAP": ".rules",
    "NET_CLASS_AUDIO": ".rules",
    "NET_CLASS_CLOCK": ".rules",
    "NET_CLASS_DEBUG": ".rules",
    "NET_CLASS_DEFAULT": ".rules",
    "NET_CLASS_DIGITAL": ".rules",
    "NET_CLASS_HIGH_CURRENT_SIGNAL": ".rules",
    "NET_CLASS_HIGH_SPEED": ".rules",
    "NET_CLASS_POWER": ".rules",
    "DesignRules": ".rules",
    "LengthConstraint": ".rules",
    "NetClassRouting": ".rules",
    "ZoneRules": ".rules",
    "create_net_class_map": ".rules",
    "SparseRouter": ".sparse",
    "SparseRoutingGraph": ".sparse",
    "Waypoint": ".sparse",
    "AlternativeStrategy": ".strategies",
    "DRCViolation": ".strategies",
    "PerformanceStats": ".strategies",
    "RepairAction": ".strategies",
    "RoutingMetrics": ".strategies",
    "RoutingResult": ".strategies",
    "RoutingStrategy": ".strategies",
    "SubGridAnalysis": ".subgrid",
    "SubGridEscape": ".subgrid",
    "SubGridPad": ".subgrid",
    "SubGridResult": ".subgrid",
    "SubGridRouter": ".subgrid",
    "compute_subgrid_resolution": ".subgrid",
    "COST_PROFILES": ".tuning",
    "BoardCharacteristics": ".tuning",
    "CostParams": ".tuning",
    "CostProfile": ".tuning",
    "RoutingQualityScore": ".tuning",
    "TuningResult": ".tuning",
    "analyze_board": ".tuning",
    "create_adaptive_router": ".tuning",
    "evaluate_routing_quality": ".tuning",
    "quick_tune": ".tuning",
    "select_profile": ".tuning",
    "tune_parameters": ".tuning",
    "ConnectionType": ".zones",
    "FilledZone": ".zones",
    "ThermalRelief": ".zones",
    "ZoneFiller": ".zones",
    "ZoneManager": ".zones",
    "fill_zones_by_priority": ".zones",
    "get_connection_type": ".zones",
}

__all__ = [
    # Block routing (Issue #1589)
    "BlockRouter",
    "BlockRoutingResult",
    # High-level API
    "Autorouter",
    "AdaptiveAutorouter",
    "RoutingFailure",
    # C++ backend
    "is_cpp_available",
    "ensure_cpp_backend_available",
    "get_backend_info",
    "create_hybrid_router",
    "CppGrid",
    "CppPathfinder",
    # Bus routing
    "BusGroup",
    "BusRoutingConfig",
    "BusRoutingMode",
    "BusSignal",
    "analyze_buses",
    "detect_bus_signals",
    "group_buses",
    # Differential pair routing
    "DifferentialPair",
    "DifferentialPairConfig",
    "DifferentialPairRules",
    "DifferentialPairType",
    "DifferentialSignal",
    "LengthMismatchWarning",
    "analyze_differential_pairs",
    "detect_differential_pairs",
    "detect_differential_signals",
    "group_differential_pairs",
    # Grid
    "RoutingGrid",
    # Sparse routing (performance optimizations)
    "SparseRouter",
    "SparseRoutingGraph",
    "Waypoint",
    # Hierarchical routing (Issue #1095)
    "RegionGraph",
    "Region",
    "RegionEdge",
    "GlobalRouter",
    "GlobalRoutingResult",
    "CorridorAssignment",
    # Routing orchestration (Issue #1138)
    "RoutingOrchestrator",
    "RoutingStrategy",
    "RoutingResult",
    "RoutingMetrics",
    "PerformanceStats",
    "AlternativeStrategy",
    "RepairAction",
    "DRCViolation",
    # Parallel routing
    "ParallelRouter",
    "ParallelRoutingResult",
    "BoundingBox",
    "NetGroup",
    "find_independent_groups",
    "find_route_conflicts",
    "resolve_parallel_conflicts",
    # Cost tuning
    "CostParams",
    "CostProfile",
    "COST_PROFILES",
    "BoardCharacteristics",
    "RoutingQualityScore",
    "TuningResult",
    "analyze_board",
    "quick_tune",
    "tune_parameters",
    "select_profile",
    "create_adaptive_router",
    "evaluate_routing_quality",
    # Pathfinding
    "Router",
    "AStarNode",
    # Heuristics
    "Heuristic",
    "HeuristicContext",
    "ManhattanHeuristic",
    "DirectionBiasHeuristic",
    "CongestionAwareHeuristic",
    "WeightedCongestionHeuristic",
    "GreedyHeuristic",
    # Layers
    "Layer",
    "LayerType",
    "LayerStack",
    "LayerDefinition",
    "ViaType",
    "ViaDefinition",
    "ViaRules",
    # Primitives
    "Point",
    "GridCell",
    "Via",
    "Segment",
    "Route",
    "Pad",
    "Obstacle",
    # Rules
    "DesignRules",
    "LengthConstraint",
    "NetClassRouting",
    "ZoneRules",
    "create_net_class_map",
    "DEFAULT_NET_CLASS_MAP",
    "NET_CLASS_POWER",
    "NET_CLASS_HIGH_CURRENT_SIGNAL",
    "NET_CLASS_CLOCK",
    "NET_CLASS_HIGH_SPEED",
    "NET_CLASS_AUDIO",
    "NET_CLASS_DIGITAL",
    "NET_CLASS_DEBUG",
    "NET_CLASS_DEFAULT",
    # Length tracking
    "LengthTracker",
    "LengthViolation",
    "ViolationType",
    "create_match_group",
    # Match-group length tracking (Epic #2661 Phase 1B / Issue #2688)
    "MatchGroup",
    "MatchGroupSource",
    "MatchGroupTracker",
    # Match-group detection (Epic #2661 Phase 1C / Issue #2689)
    "BUS_GROUP_PATTERNS",
    "detect_match_groups",
    # I/O
    "route_pcb",
    "load_pcb_for_routing",
    "detect_layer_stack",
    "generate_netclass_setup",
    "merge_routes_into_pcb",
    "ClearanceViolation",
    "FineZone",
    "GridAdjustment",
    "GridAutoSelection",
    "GridResolutionError",
    "GridSafetyError",
    "MultiResolutionGridPlan",
    "PCBDesignRules",
    "PadPosition",
    "adjust_grid_for_compliance",
    "auto_select_grid_resolution",
    "compute_multi_resolution_plan",
    "extract_board_dimensions",
    "extract_pad_positions",
    "load_pads_for_analysis",
    "recommend_grid_for_board_size",
    "parse_pcb_design_rules",
    "validate_grid_resolution",
    "validate_routes",
    # DRC nudge
    "DRCNudgeResult",
    "drc_verify_and_nudge",
    # Optimizer
    "TraceOptimizer",
    "OptimizationConfig",
    "OptimizationStats",
    "CollisionChecker",
    "GridCollisionChecker",
    "VectorCollisionChecker",
    # Zones
    "ZoneManager",
    "ZoneFiller",
    "FilledZone",
    "ThermalRelief",
    "ConnectionType",
    "fill_zones_by_priority",
    "get_connection_type",
    # Analysis
    "RoutabilityAnalyzer",
    "RoutabilityReport",
    "NetRoutabilityReport",
    "RoutingFailureDiagnostic",
    "BlockingObstacle",
    "CongestionZone",
    "RouteAlternative",
    "ObstacleType",
    "RoutingSeverity",
    "analyze_routing_failure",
    # Failure Analysis (Root Cause)
    "FailureCause",
    "FailureAnalysis",
    "BlockingElement",
    "PathAttempt",
    "CongestionMap",
    "RootCauseAnalyzer",
    # Placement-Routing Feedback
    "PlacementFeedbackLoop",
    "PlacementFeedbackResult",
    "PlacementAdjustment",
    "PlacementDiffEntry",
    "detect_pf_stagnation",
    # Classifier-driven placement-delta feedback (#4467)
    "PlacementDeltaFeedbackLoop",
    "PlacementDeltaFeedbackResult",
    "PlacementDelta",
    "delta_from_diagnosis",
    "deltas_from_result",
    "endpoint_align_deltas",
    "write_placement_delta_json",
    # Escape Routing (dense packages)
    "EscapeRouter",
    "EscapeRoute",
    "EscapeDirection",
    "PackageType",
    "PackageInfo",
    "is_dense_package",
    "is_fine_pitch_ssop",
    "is_usb_c_class_connector",
    "detect_package_type",
    "get_package_info",
    # Net Class Auto-Detection (Issue #634)
    "NetClass",
    "NetClassification",
    "SYMBOL_INDICATORS",
    "NET_CLASS_PATTERNS",
    "classify_from_symbol",
    "classify_from_pin_type",
    "classify_from_name",
    "classify_net",
    "auto_classify_nets",
    "apply_net_class_rules",
    "classify_and_apply_rules",
    "is_differential_pair_name",
    "find_differential_partner",
    # Output and Diagnostics
    "format_failed_nets_summary",
    "show_fine_pitch_warnings",
    "show_routing_summary",
    "get_routing_diagnostics_json",
    "print_routing_diagnostics_json",
    # Manufacturer Limits and Adaptive Rules
    "MfrLimits",
    "RelaxationTier",
    "MFR_LIMITS",
    "MFR_JLCPCB",
    "MFR_OSHPARK",
    "MFR_PCBWAY",
    "get_mfr_limits",
    "get_relaxation_tiers",
    # Fine-Pitch Component Analysis (Issue #1008)
    "FinePitchReport",
    "FinePitchSeverity",
    "ComponentGridAnalysis",
    "OffGridPad",
    "analyze_fine_pitch_components",
    # Fine-Pitch Escape Predicates (Issue #3371 P_FP1)
    "ESCAPE_CLEARANCE_SAFETY_MARGIN_MM",
    "geometry_needs_fine_pitch_escape",
    "get_default_escape_clearance",
    # Fine-Pitch Escape Region Detector (Issue #3371 P_FP2)
    "DEFAULT_ESCAPE_REGION_RADIUS_MM",
    "FinePitchRegion",
    "detect_fine_pitch_regions",
    "resolve_clearance_with_escape_region",
    # Sub-Grid Routing for Fine-Pitch Components (Issue #1109)
    "SubGridRouter",
    "SubGridAnalysis",
    "SubGridEscape",
    "SubGridPad",
    "SubGridResult",
    "compute_subgrid_resolution",
    # Adaptive Grid Routing (Issue #1135)
    "AdaptiveGridRouter",
    "AdaptiveGridResult",
    "FinePitchEscapeFailure",
    "identify_fine_pitch_components",
    # Routing Cache (Issue #1071)
    "RoutingCache",
    "CacheKey",
    "CachedRoutingResult",
    "CachedNetRoute",
    "CachedSubProblem",
    "SubProblemSignature",
    "compute_pad_positions_hash",
    "get_default_cache_path",
    "normalize_routes_to_origin",
    "transform_routes",
    # Congestion estimation
    "CongestionEstimator",
    "NetBBox",
    "TileGrid",
    # Preflight checks (Issue #2497)
    "OffGridReport",
    "PreflightOffGridPad",
    "check_pad_grid_alignment",
]


def __getattr__(name: str) -> Any:
    """Resolve a public export once, retaining the defining module's object."""
    try:
        module_name = _EXPORT_MODULES[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
